### ISSUE TITLE
Building simple Qt application after installation

### ISSUE THREAD

**Issue by usernameiwantedwasalreadytaken** [Microsoft/vcpkg#1442]
I've installed the qt5 module and I'm trying to build a simple project with just one file:

```
#include <QtWidgets/QApplication.h>
#include <QtWidgets/QMainWindow.h>

int main(int argc, char** argv) {
	QApplication app { argc, argv };
	QMainWindow mainWindow;

	mainWindow.show();
	return app.exec();
}
```

Visual Studio can compile fine, but gives me the following error when linking:

```
1>------ Build started: Project: Basic, Configuration: Release Win32 ------
1>main.cpp
1>Qt5AxServer.lib(qaxserver.obj) : error LNK2001: unresolved external symbol "class QAxFactory * __cdecl qax_instantiate(void)" (?qax_instantiate@@YAPAVQAxFactory@@XZ)
1>C:\Tests\Qt\QtSamples\Release\Basic.exe : fatal error LNK1120: 1 unresolved externals
1>Done building project "Basic.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

Any ideas how I might solve this?

P.S.: With a Debug build I've got many more linking errors...

Thanks in advance.

**Comment by usernameiwantedwasalreadytaken** [comment]
This error happens because vcpkg is linking to `Qt5AxServer.lib` which is an ActiveX library from Qt. I wonder if this was needed since, for this example, the code was not using anything from ActiveX...

**Comment by usernameiwantedwasalreadytaken** [comment]
So, if I delete `Qt5AxServer.lib` from `<vcpkg>\installed\*\lib` everything works.

**Comment by ShinNoNoir** [comment]
I'd like to add that for the Debug configuration, `<vcpkg>\installed\*\debug\lib\Qt5Bootstrap.lib` should also be deleted. `Qt5Bootstrap.lib` is linked with MD_DynamicRelease and is only meant for Release builds.

**Comment by ShinNoNoir** [comment]
Reading a bit more about Qt, it seems that depending on your use case, you either:
 * Link `qtmain.lib` (rel) or `qtmaind.lib` (dbg);
 * Or link `Qt5AxServer.lib` (rel) or `Qt5AxServerd.lib` (dbg).

Source: http://doc.qt.io/qt-5/activeqt-server.html

Does vcpkg offer any way of selecting which libs will be included in the linking process?

**Comment by ShinNoNoir** [comment]
> Does vcpkg offer any way of selecting which libs will be included in the linking process?

Okay, after browsing through some source files and other `portfile.cmake`s, I think the following probably should happen:

 * `debug\lib\Qt5Bootstrap.lib` must be deleted;
 * `Qt5AxServer.lib` should be moved from `lib` to `lib\manual-link`;
 * `Qt5AxServerd.lib` should be moved from `debug\lib` to `debug\lib\manual-link`;
 * `qtmain.lib` should be moved from `lib` to `lib\manual-link`;
 * `qtmaind.lib` should be moved from `debug\lib` to `debug\lib\manual-link`;

Users need to:
 * Explicitly add `qtmain.lib`/`qtmaind.lib` as a dependency for Qt desktop applications for release/debug configurations.
 * Explicitly add `Qt5AxServer.lib`/`Qt5AxServerd.lib` as a dependency for Qt ActiveX server applications for release/debug configurations.

**Comment by JackBoosY** [comment]
Hi @usernameiwantedwasalreadytaken, thanks for reporting this issue.
Since qt5 has been upgraded to 5.12.5, this issue may be fixed.
So please update vcpkg and rebuild qt5.

Thanks.

**Comment by JackBoosY** [comment]
@Neumann-A I think this issue is resolved in some PRs, is it correct?

**Comment by Neumann-A** [comment]
@JackBoosY: I think this:
```
Qt5AxServer.lib should be moved from lib to lib\manual-link;
Qt5AxServerd.lib should be moved from debug\lib to debug\lib\manual-link;
```
still needs to be resolved

**Comment by DietmarSchulz** [comment]
After doing that the execution seems to bind to tesseract and the output is:
Starting java -Xms512m -Xmx1024m -Djava.library.path=. -jar ./ScrollView.jar
ScrollView: Waiting for server...
ScrollView: Waiting for server...

**Comment by JonLiu1993** [comment]
@Neumann-A, since qt5 has been upgraded to 5.12.5, could you please see if this issue is resolved in some PR?

**Comment by Neumann-A** [comment]
@JonLiu1993 just look at the file list. If the files mentioned by me above are in manual-link it is resolved otherwise it is not solved.

**Comment by arappazzo** [comment]
I've found the same issue in a VS solution of a CUDA project (I've pasted the error below just as reminder)

Qt5AxServer.lib(qaxserver.obj) : error LNK2001: unresolved external symbol "class QAxFactory * __cdecl qax_instantiate(void)" (?qax_instantiate@@YAPAVQAxFactory@@XZ)

I have the Qt plugin installed in my VS installation. Still, the CUDA project has nothing to do with Qt. I mean, is there a way to fully disable Qt plugins from VS? Is there a way to fix this?
