### ISSUE TITLE
[vcpkg] Build failure on MacOS

### ISSUE THREAD

**Issue by Prometheus88** [microsoft/vcpkg#15442]
**Host Environment**
- OS: [Mojave 10.14.6.]
- Compiler: revision

**To Reproduce**
`./bootstrap-vcpkg.sh`

**Failure logs** 
FAILED: CMakeFiles/vcpkglib.dir/src/vcpkg/base/chrono.cpp.o 
/usr/local/bin/g++-10 -DVCPKG_USE_STD_FILESYSTEM=1 -I../include -O3 -DNDEBUG -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk -include /Users/DorisMac/vcpkg/toolsrc/include/pch.h -std=c++17 -MD -MT CMakeFiles/vcpkglib.dir/src/vcpkg/base/chrono.cpp.o -MF CMakeFiles/vcpkglib.dir/src/vcpkg/base/chrono.cpp.o.d -o CMakeFiles/vcpkglib.dir/src/vcpkg/base/chrono.cpp.o -c ../src/vcpkg/base/chrono.cpp
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/wchar.h:90,
                 from /usr/local/Cellar/gcc/10.2.0_1/include/c++/10.2.0/cwchar:44,
                 from /usr/local/Cellar/gcc/10.2.0_1/include/c++/10.2.0/bits/postypes.h:40,
                 from /usr/local/Cellar/gcc/10.2.0_1/include/c++/10.2.0/bits/char_traits.h:40,
                 from /usr/local/Cellar/gcc/10.2.0_1/include/c++/10.2.0/string:40,
                 from ../include/vcpkg/base/cstringview.h:4,
                 from ../include/vcpkg/base/checks.h:3,
                 from ../include/vcpkg/base/expected.h:3,
                 from ../include/vcpkg/base/files.h:3,
                 from /Users/DorisMac/vcpkg/toolsrc/include/pch.h:5,
                 from <command-line>:
/usr/local/Cellar/gcc/10.2.0_1/lib/gcc/10/gcc/x86_64-apple-darwin18/10.2.0/include-fixed/stdio.h:219:10: fatal error: _ctermid.h: No such file or directory
  219 | #include <_ctermid.h>
      |          ^~~~~~~~~~~~
compilation terminated.
ninja: build stopped: subcommand failed.

**Additional context**
Have followed the exact steps on the vckpg install page from Microsoft for MacOS. 
I have downloaded the vcpkg package via homebrew: brew install vcpkg 
then i used cd vcpkg to go to the root directory and executed the command as shown above.
I tried to run brew upgrade but it didn't helped.

Any ideas?

**Comment by JackBoosY** [comment]
I strongly recommend that you use `git clone https://github.com/microsoft/vcpkg.git` to download vcpkg and use `git pull` to update vcpkg to the latest.
Because vcpkg in brew may not be the latest, this issue may have been fixed on the master branch.

Thanks.

**Comment by Prometheus88** [comment]
> I strongly recommend that you use `git clone https://github.com/microsoft/vcpkg.git` to download vcpkg and use `git pull` to update vcpkg to the latest.
> Because vcpkg in brew may not be the latest, this issue may have been fixed on the master branch.
> 
> Thanks.

Have done that. 

I ran` rm -r vcpkg `and then` git clone https://github.com/microsoft/vcpkg.git `
just for good measurement git pull (which stated that already everything is up to date) and then
`git clone https://github.com/microsoft/vcpkg.git`

and then 
`./bootstrap-vcpkg.sh`

however, i get the exact same error as in the OP.

**Comment by JackBoosY** [comment]
@strega-nil Can you please take a look?

Thanks.

**Comment by strega-nil** [comment]
@Prometheus88 we don't support macOS earlier than latest, and it seems like perhaps brew doesn't either? it seems like this is an issue with g++10 on macOS 10.14; I don't think there's something we can do about it.

Perhaps try the following:

```sh
$ cat >test.c <<EOF
#include <wchar.h>

int main() {}
EOF
$ gcc-10 test.c
```

and see what happens; additionally, if that works, please upload `/usr/local/Cellar/gcc/10.2.0_1/lib/gcc/10/gcc/x86_64-apple-darwin18/10.2.0/include-fixed/stdio.h` so that I can maybe see what's going on.

**Comment by Prometheus88** [comment]
> @Prometheus88 we don't support macOS earlier than latest, and it seems like perhaps brew doesn't either? it seems like this is an issue with g++10 on macOS 10.14; I don't think there's something we can do about it. However, I will try to help:
> 
> Try the following:
> 
> ```shell
> $ cat >test.c <<EOF
> #include <wchar.h>
> 
> int main() {}
> EOF
> $ gcc-10 test.c
> ```
> 
> and see what happens; additionally, if that works, please upload `/usr/local/Cellar/gcc/10.2.0_1/lib/gcc/10/gcc/x86_64-apple-darwin18/10.2.0/include-fixed/stdio.h` so that I can maybe see what's going on.

Hey! Thanks both for reaching out to me! 

I got it working! I ran `brew upgrade-reset` and afterwards I removed gcc via `brew uninstall gcc `

When i use now clang instead of gcc, it works just fine. 

However, i am still not able to install vcpkg as it is, as you already mentioned, not supported for my OS version that i am currently using, but that's fine. I also get now the message that tells me exactly that.  Here's just the log again, just in case:

```
MikeMacBookPro:vcpkg DorisMac$ ./bootstrap-vcpkg.sh
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting the C++ compiler in use
CMake Error at cmake/utilities.cmake:30 (message):
  Building the vcpkg tool requires support for the C++ Filesystem TS.

  macOS versions below 10.15 do not have support for it with Apple Clang.

  Please install gcc6 or newer from homebrew (brew install gcc).

  If you would like to try anyway, pass --allowAppleClang to bootstrap.sh.

Call Stack (most recent call first):
  CMakeLists.txt:50 (vcpkg_detect_compiler)


-- Configuring incomplete, errors occurred!
See also "/Users/DorisMac/vcpkg/toolsrc/build.rel/CMakeFiles/CMakeOutput.log".
```

I close it, as only wanted to have a working compiler for C++ on my machine.
