### ISSUE TITLE
Error: Building package msmpi:x64-windows failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by gaaguile** [Microsoft/vcpkg#1605]
Hi, I have this issue while installing the VTK package, it seems there is a newer version.

CMake Error at ports/msmpi/portfile.cmake:28 (message):
    The version of the installed MSMPI redistributable packages does not match the version to be installed
    Expected version: 8.0.12438.0
    Found version: 7.1.12437.25

Call Stack (most recent call first):
  scripts/ports.cmake:72 (include)
Error: Building package msmpi:x64-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: msmpi:x64-windows
  Vcpkg version: 0.0.81-

**Comment by alexkaratarakis** [comment]
It appears you have msmpi version 7.1 installed. The portfile for msmpi checks your installed version of the msmpi runtime (we can't do unatteded installation for that, only for the SDK).

Therefore, you need to update it.
Also, the message above states that "Expected version is 8.0" but a few minutes ago I merged an update that updates the msmpi version to 8.1. So, I recommend you do a `git pull` first. 

In sum:
1) `git pull`
2) `vcpkg install msmpi`. This will fail but will download the installer for msmpi in your `vcpkg\downloads\` folder
3) Run said installer
4) `vcpkg install msmpi` (optional step)
5) `vcpkg install vtk`

**Comment by gaaguile** [comment]
Thank you Alex,
I followed you instructions and VTK is installed and running in my VS 2017 project.

**Comment by amigo421** [comment]
it doesn't work for 2015up3, the installation via installer doesn't solve the problem
