### ISSUE TITLE
[wxWidgets] static triplet only debug/release library mixup

### ISSUE THREAD

**Issue by brad-anderson** [microsoft/vcpkg#16545]
**Describe the bug**
When using wxWidgets supplied by vcpkg through CMake in a statically linked debug configuration project, the linker gets supplied with the release versions of the wxwidgets libraries instead of the debug versions.

**Environment**
- OS: Windows
- Compiler: cl.exe 19.28.29910

**To Reproduce**
1. ./vcpkg install wxwidgets:x64-windows-static
2. Use wxWidgets in a statically linked debug project
3. See error

I've attached a basic [CMakeLists.txt](https://github.com/microsoft/vcpkg/files/6087507/CMakeLists.txt) and the [wxWidget's reference hello world](https://github.com/microsoft/vcpkg/files/6087510/foo.cpp.txt) to reproduce. I'm using VS 2019 CMake support and specifying my CMake toolchain and vcpkg triplet in my CMakeSettings.json.

**Expected behavior**
Debug libraries should be provided. This works correctly on x64-windows.

**Failure logs** 
[wxwidgets-static-debrel-mixup.txt](https://github.com/microsoft/vcpkg/files/6087500/wxwidgets-static-debrel-mixup.txt)

**Additional context**
Getting to this point relies on a PR I made to fix an earlier issue with linking libpng: #16544

**Comment by JackBoosY** [comment]
Confirmed.

**Comment by JackBoosY** [comment]
Seems like `FindwxWidgets.cmake` doesn't find the debug libraries correctly.

**Comment by brad-anderson** [comment]
Some context, FindwxWidgets.cmake had never worked with vcpkg and only recently was made to work (see #4756). That change made it finally work but for reasons I haven't quite teased out it fails for the static triplets.

I'd love to get some proper CMake targets for wxWidgets but FindwxWidgets.cmake is >1k lines so I think most people, like myself, haven't found the time/courage to tackle it.

**Comment by JackBoosY** [comment]
Will be fixed in #16546.

**Comment by brad-anderson** [comment]
I don't believe this is fixed. Unfortunately I'm dealing with the cairo port getting all messed up recently so I haven't been able to give HEAD a proper test yet but there is nothing in the commit for #16546 that would have addressed this issue.

**Comment by JackBoosY** [comment]
@brad-anderson Please ping me if this issue is still exist.

**Comment by brad-anderson** [comment]
@JackBoosY I've confirmed this is still an issue.

**Comment by JackBoosY** [comment]
Will be fixed by https://github.com/microsoft/vcpkg/pull/17111.

**Comment by jdoubleu** [comment]
Unfortunately, #17111 hasn't been merged yet, so the issue still exists.

Trying to understand [`Finxwswidgets.cmake`](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindwxWidgets.cmake), it looks like it does not honor the `debug/lib` directory at all but rather expects the debug library path to be at `wsmud/lib` ([`$WX_ROOT_DIR`](https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindwxWidgets.cmake#L570) might be `${WX_BASE_DIR}/${wxWidgets_CONFIGURATION}`).

I think the main issue is with the folder structure of the wxWidgets VCPKG package not being compatible with CMake's expected structure, which might also be the structure from wxWidgets' [distributed binaries](http://wxwidgets.org/downloads/).
