### ISSUE TITLE
[vk-bootstrap] Missing import target when building on Linux

### ISSUE THREAD

**Issue by spnda** [microsoft/vcpkg#22067]
**Host Environment**
- OS: x86_64 Linux 5.8.0-43-generic
- Compiler: g++-11 (Ubuntu 11.1.0-1ubuntu1~20.04)

**To Reproduce**
This happens when trying to configure a cmake project depending on `vk-bootstrap` while on Linux.
```cmake
find_package(vk-bootstrap CONFIG REQUIRED)
target_link_libraries(carbon PUBLIC vk-bootstrap::vk-bootstrap)
```

`./vcpkg install vk-bootstrap`
`mkdir build && cd build`
`cmake ..`

**Failure logs** 
```
CMake Error in src/carbon/CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "vk-bootstrap::vk-bootstrap"
  configuration "Debug".


CMake Error in src/carbon/CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "vk-bootstrap::vk-bootstrap"
  configuration "Debug".


CMake Error in src/carbon/CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "vk-bootstrap::vk-bootstrap"
  configuration "Debug".
```

**Additional context**
I know I made the `vk-bootstrap` port but it seems like it only worked on Windows, even though it's the same CMake project I'm testing right now. I'm no expert in CMake, but this seems like it's a pretty simple fix that I am just missing.

**Comment by FrankXie05** [comment]
@spnda Thanks for posting this issue. Could you please provide this file:
````
src/carbon/CMakeLists.txt
````

**Comment by spnda** [comment]
I have worked around this for now but this is the older version `src/carbon/CMakeLists.txt` which still targets `vk-bootstrap` from vcpkg:

https://github.com/spnda/krypton_engine/blob/8cc5b89fa92780cc95b5f834951916731e222beb/src/carbon/CMakeLists.txt

**Comment by FrankXie05** [comment]
We should fix this issue completely.

**Comment by FrankXie05** [comment]
@spnda sorry for the late reply，I checked your `CMakeLists.txt` and found that about '`target_include_directories("./")'`, you should use relative paths to avoid such problems : 
```
target_include_directories(carbon PUBLIC
$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/src>
$<INSTALL_INTERFACE:include>)
```
 Of course, your solution is to add between paths to the build. This problem can also be solved. :)

**Comment by FrankXie05** [comment]
@spnda Is the problem still there? Feel free to re-open if it continues to work.

**Comment by spnda** [comment]
Hi, sorry I missed your previous comment 17 days ago.

No, nothing has ever fixed this issue. The target include directories have nothing to do with this. Please re-open this issue. Take the following cmakelists as an example:
```cmake
cmake_minimum_required(VERSION 3.21)

project("cmake_test")

add_executable(cmake_test "main.cpp")

find_package(vk-bootstrap CONFIG REQUIRED)
target_link_libraries(cmake_test PUBLIC vk-bootstrap::vk-bootstrap)
```
Using this CMakeLists.txt I still get the following error when running on Ubuntu (WSL in this case). No error on Windows. I am using CMake 3.22.1 on both platforms with vcpkg at master.
```
CMake Error in CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "vk-bootstrap::vk-bootstrap".
```

**Comment by FrankXie05** [comment]
@spnda confirm

**Comment by mvonkeil** [comment]
Seems like this issue still exists:

```
find_package(vk-bootstrap CONFIG REQUIRED)
target_link_libraries(main PRIVATE vk-bootstrap::vk-bootstrap)
```

results in

```
CMake Error in CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "vk-bootstrap::vk-bootstrap"
  configuration "Debug".


CMake Error in CMakeLists.txt:
  IMPORTED_LOCATION not set for imported target "vk-bootstrap::vk-bootstrap"
  configuration "Debug".
```

**Comment by dg0yt** [comment]
@aaaaaaaaaaargh Please test #32330.
