### ISSUE TITLE
[openssl] Unable to build arm64 iphonesimulator libraries

### ISSUE THREAD

**Issue by johnwason** [microsoft/vcpkg#24468]
**Describe the bug**
The openssl package currently is unable to build arm64 iphonesimulator libraries. The following triplet is working successfully with other packages:

```
# arm64-iphonesimulator.cmake
set(VCPKG_TARGET_ARCHITECTURE arm64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE static)
set(VCPKG_CMAKE_SYSTEM_NAME iOS)
set(VCPKG_OSX_SYSROOT iphonesimulator)
set(CMAKE_OSX_SYSROOT iphonesimulator)
```
However in XCode, an error is returned saying that libssl.a and libcrypto.a were built for iOS and not the simulator.

The problem is here, in `ports/openssl/unix/CMakeLists.txt`

```
    if(VCPKG_TARGET_ARCHITECTURE MATCHES "arm64")
        set(PLATFORM ios64-xcrun)
    elseif(VCPKG_TARGET_ARCHITECTURE MATCHES "arm")
        set(PLATFORM ios-xcrun)
    elseif(VCPKG_TARGET_ARCHITECTURE MATCHES "x86" OR
           VCPKG_TARGET_ARCHITECTURE MATCHES "x64")
        set(PLATFORM iossimulator-xcrun)
    else()
        message(FATAL_ERROR "Unknown iOS target architecture: ${VCPKG_TARGET_ARCHITECTURE}")
    endif()
```

Replacing with a block that checks for "iPhoneSimulator" in the `CMAKE_OSX_SYSROOT` fixes the problem.

```
    if(VCPKG_TARGET_ARCHITECTURE MATCHES "arm64")
        if(CMAKE_OSX_SYSROOT MATCHES ".*iPhoneSimulator.*")
            set(PLATFORM iossimulator-xcrun)
        else()
            set(PLATFORM ios64-xcrun)
        endif()
    elseif(VCPKG_TARGET_ARCHITECTURE MATCHES "arm")
        set(PLATFORM ios-xcrun)
    elseif(VCPKG_TARGET_ARCHITECTURE MATCHES "x86" OR
           VCPKG_TARGET_ARCHITECTURE MATCHES "x64")
        set(PLATFORM iossimulator-xcrun)
    else()
        message(FATAL_ERROR "Unknown iOS target architecture: ${VCPKG_TARGET_ARCHITECTURE}")
    endif()
```

I can create a pull request, but it would also add the `arm64-iphonesimulator` triplet, so I am not sure how to proceed.

Branch with updates: https://github.com/johnwason/vcpkg/tree/fix_openssl_arm64_iphonesimulator

**Environment**
- OS: iOS
- Compiler: XCode 13.3.1

**Comment by Stannieman** [comment]
How does this PR also add the triplet? Seems like you can just fix the OpenSSL script and not inclide the new triplet file?

**Comment by dg0yt** [comment]
https://github.com/microsoft/vcpkg/compare/master...johnwason:vcpkg:fix_openssl_arm64_iphonesimulator

I would suggest to create two separate PRs.

**Comment by johnwason** [comment]
It turns out that even on m1 the simulator is still building for x64. The arm64 port I created was building for x64 anyway. I haven't followed up on this because I am even more confused and didn't have time to sort out what was going on.

**Comment by Stannieman** [comment]
Is ".*iPhoneSimulator.*" correct? If this is case sensitive then it might not match and build for the wrong thing instead.

**Comment by johnwason** [comment]
Here is the script:

https://github.com/johnwason/robotraconteur/blob/ios_build_script/packaging/scripts/build_ios_xcframework.py

And here are the resource files:

https://github.com/johnwason/robotraconteur/tree/ios_build_script/packaging/ios

I haven't looked at this for a while so I don't remember the exact details.

**Comment by Cheney-W** [comment]
This issue hasn’t been updated in 3 month, if it is still an issue, please reopen this issue.

**Comment by j-bruel** [comment]
We facing exactly the same issue. Can we re-open it ?

**Comment by AzanovAA** [comment]
I faced the same issue. 
`ld: in /Users/aaa/Work/wsnet/tools/temp/build/SIMULATORARM64/vcpkg_installed/arm64-iphonesimulator/lib/libssl.a(libssl-lib-bio_ssl.o), building for iOS Simulator, but linking in object file built for iOS`

For some reason, vcpkg is building openssl for iOS architecture instead of the ARM64 simulator. There are no problems with all other vcpkg packages, except openssl. So the problem is in the openssl port.

BTW, It is possible to build openssl for the ARM64 simulator architecture just building openssl without vcpkg.

**Comment by dg0yt** [comment]
So you are willing and able to test a PR? I can't test iOS, but I could make a proposal.

**Comment by johnwason** [comment]
> So you are willing and able to test a PR? I can't test iOS, but I could make a proposal.

Yes, I can test a PR.

I think the problem is in openssl itself rather than vcpkg.

**Comment by dg0yt** [comment]
> I think the problem is in openssl itself rather than vcpkg.

I see: There is https://github.com/openssl/openssl/commit/3ced3a44e8b2f5bb6ee3a61ae3d281061fc711f8 but it is not in the 3.1 branch.

**Comment by dg0yt** [comment]
Maybe the backport just works?
https://github.com/dg0yt/vcpkg/commit/48efd8f2e4c7896c90ae88fe37197ab3f2916664

**Comment by johnwason** [comment]
Currently I am using the x64 simulator and running the arm64 version as an app on Mac OS, since it is now possible to run iOS apps without emulation on arm64 macs. I can test a patch, but I don't have availability to work on developing one.

**Comment by dg0yt** [comment]
https://github.com/dg0yt/vcpkg/commit/48efd8f2e4c7896c90ae88fe37197ab3f2916664 *is* the patch.
Just cherry-pick it, or checkout openssl-simulator from https://github.com/dg0yt/vcpkg.

**Comment by Nolanlemahn** [comment]
Hi - I'm not sure who to ping (yet) but are we sure this is fixed?

Ignoring the fact that we need to be more vigilant about versioning, I run into the following on my own system:

```
...
    openssl:arm64-ios-simulator@3.2.1 -- /Users/build/.cache/vcpkg/registries/git-trees/53fb72a19981a3439cd569f58b722ca6cd26e23d
  * openssl:arm64-osx@3.1.2#1  -- /Users/build/.cache/vcpkg/registries/git-trees/5a99562f8ac47a68a58efba5f0d40259fedeecc5
...
...
ld: warning: object file (vcpkg_installed/arm64-ios-simulator/debug/lib/libprotobufd.a[85](wrappers.pb.cc.o)) was built for newer 'iOS-simulator' version (17.2) than being linked (16.1)
ld: building for 'iOS-simulator', but linking in object file (vcpkg_installed/arm64-ios-simulator/debug/lib/libssl.a[3](libssl-lib-d1_lib.o)) built for 'iOS'
```

For whatever reason, OpenSSL seems to be the only object file in my flow building this way, and I'm not sure why that is.

**Comment by ronald-baldonado** [comment]
> [dg0yt@48efd8f](https://github.com/dg0yt/vcpkg/commit/48efd8f2e4c7896c90ae88fe37197ab3f2916664) _is_ the patch. Just cherry-pick it, or checkout openssl-simulator from https://github.com/dg0yt/vcpkg.

I tried checking out the `openssl-simulator` branch and building openssl, but `libssl.a` is still being treated like an iOS lib and not an ios-simulator lib. Also tried on the vcpkg master branch and still the same behavior.
