### ISSUE TITLE
angle build failure

### ISSUE THREAD

**Issue by xiaozhuai** [microsoft/vcpkg#24704]
**Host Environment**
- OS: win10 21h2
- Compiler: Visual Studio 17.2.0  MSVC 19.32.31328.0

**To Reproduce**
`./vcpkg install angle:x64-windows`

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8690160/install-x64-windows-dbg-out.log)

**Comment by Neumann-A** [comment]
vcpkg cannot do anything about an ICE (Error 1001). Upstream might have a workaround.

**Comment by xiaozhuai** [comment]
@Neumann-A Thanks. Should I report this to angle or Visual Studio? I succeed with vs 17.1.6 before. And Yesterday, I upgrade my vs to 17.2, it broken.

**Comment by JonLiu1993** [comment]
@xiaozhuai ,Thanks for posting this issue, I can't repo this issue on my local machine:
````
-- Using source at F:/Feature-test/pcapplusplus/vcpkg/buildtrees/angle/src/8ee76d4a8e-44c1f13803.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/Feature-test/pcapplusplus/vcpkg/packages/angle_x64-windows/share/angle/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\AppData\Local\vcpkg\archives\ea\ea2a7f7e57d56b5d9acb23f6f17f41f131faa9a0c50b80622b8665dd0a103136.zip
Elapsed time to handle angle:x64-windows: 6.826 min

Total elapsed time: 7.439 min

angle provides CMake targets:
    # this is heuristically generated, and may not be correct
    find_package(unofficial-angle CONFIG REQUIRED)
    # note: 9 additional targets are not displayed.    target_link_libraries(main PRIVATE unofficial::angle::libEGL unofficial::angle::libANGLE unofficial::angle::libGLESv2 unofficial::angle::angle_common)

````
Could you please install the Visual Studio with English lanage package and try again?

**Comment by xiaozhuai** [comment]
@JonLiu1993 I can suc build it on vs 17.1.6. Then I upgrade to 17.2, it broken.
I've switch to English language pack, here is the log.

[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8698443/install-x64-windows-dbg-out.log)

**Comment by JackBoosY** [comment]
```
D:\vcpkg\vcpkg\buildtrees\angle\src\ee2b7d070a-83a419ab43.clean\src\compiler/translator/StaticType.h(156): fatal error C1001: Internal compiler error.
(compiler file 'msc1.cpp', line 1693)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
```

**Comment by JackBoosY** [comment]
This issue was fixed by Visual Studio 2022 dev branch but have not published yet.

**Comment by xiaozhuai** [comment]
I upgrade to Visual Studio LTSC 17.2.1 and still got the same problem.

**Comment by BillyONeal** [comment]
This is a compiler bug which means it should be reported through Developer Community. https://developercommunity.visualstudio.com/search?space=62

I know of an internal bug reported about this but don't know how to point you folks to it. I know the compiler team is looking at it because it breaks all the webkit/chromium forks.

**Comment by johnco3** [comment]
OS Version Windows 11 22H2
Note I tweaked my x64-windows triplet by adding `set(VCPKG_PLATFORM_TOOLSET v143)`
I'm also encountering the same issue using compiler version 17.2.1.   hopefully the compiler team will address this issue shortly as my application build is now broken (I assume the fault is compiler related and vcpkg) 
[install-x64-windows-dbg-out.log](https://github.com/microsoft/vcpkg/files/8759107/install-x64-windows-dbg-out.log)

**Comment by johnco3** [comment]
Note I just updated to 17.2.2 which was released earlier today and the bug still persists.

**Comment by DramaDesu** [comment]
It still doesn't work (Upgraded to the lastest version of compiler and vcpkg)

**Comment by jeremy-visionaid** [comment]
Still not working in 17.2.3

**Comment by mattgirv** [comment]
Still seems to be an issue in 17.2.4 as well.

**Comment by nil-is-lin** [comment]
error: building angle:x64-windows failed with: BUILD_FAILED
package: angle[core]:x64-windows -> chromium_4472#3
vcpkg-tool version: 2022-03-30-692785ac944e81417840c6de244fb3e18a4b35eb
vcpkg-scripts version: 3d8f78171 2022-06-15 (14 hours ago)

Microsoft Visual Studio Community 2022 (64-bit) - Current
Version 17.2.4

**Comment by JonLiu1993** [comment]
I install successfully in 17.3.0-pre.2.0
````
PS F:\Feature-test\angle\vcpkg> ./vcpkg install angle:x64-windows
Computing installation plan...
The following packages will be built and installed:
    angle[core]:x64-windows -> chromium_4472#3
Detecting compiler hash for triplet "x64-windows"...
Restored 0 packages from C:\Users\vzhli17\AppData\Local\vcpkg\archives in 228.2 us. Use --debug to see more details.
Installing 1/1 angle:x64-windows...
Building angle[core]:x64-windows...
-- Using cached google-angle-d15be77864e18f407c317be6f6bc06ee2b7d070a.tar.gz.
-- Cleaning sources at F:/Feature-test/angle/vcpkg/buildtrees/angle/src/ee2b7d070a-83a419ab43.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/Feature-test/angle/vcpkg/downloads/google-angle-d15be77864e18f407c317be6f6bc06ee2b7d070a.tar.gz
-- Applying patch 001-fix-uwp.patch
-- Applying patch 002-fix-builder-error.patch
-- Applying patch 003-fix-mingw.patch
-- Using source at F:/Feature-test/angle/vcpkg/buildtrees/angle/src/ee2b7d070a-83a419ab43.clean
-- Using cached F:/Feature-test/angle/vcpkg/downloads/angle-09490503d0f201b81e03f5ca0ab8ba8ee76d4a8e.tar.gz
-- Extracting source F:/Feature-test/angle/vcpkg/downloads/angle-09490503d0f201b81e03f5ca0ab8ba8ee76d4a8e.tar.gz
-- Applying patch third-party-zlib-far-undef.patch
-- Using source at F:/Feature-test/angle/vcpkg/buildtrees/angle/src/8ee76d4a8e-895bfc7289.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
PS F:\Feature-test\angle\vcpkg> ./vcpkg install angle:x64-windows --debug
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Failed to open: F:\Feature-test\angle\vcpkg\vcpkg-bundle.json
[DEBUG] Using scripts-root: F:\Feature-test\angle\vcpkg\scripts
[DEBUG] Bundle config: readonly=0, usegitregistry=0, embeddedsha=nullopt
[DEBUG] Using builtin-ports: F:\Feature-test\angle\vcpkg\ports
[DEBUG] Using installed-root: F:\Feature-test\angle\vcpkg\installed
[DEBUG] Using buildtrees-root: F:\Feature-test\angle\vcpkg\buildtrees
[DEBUG] Using packages-root: F:\Feature-test\angle\vcpkg\packages
[DEBUG] Using vcpkg-root: F:\Feature-test\angle\vcpkg
[DEBUG] Using scripts-root: F:\Feature-test\angle\vcpkg\scripts
[DEBUG] Using builtin-registry: F:\Feature-test\angle\vcpkg\versions
[DEBUG] Using downloads-root: F:\Feature-test\angle\vcpkg\downloads
[DEBUG] Default binary cache path is: C:\Users\vzhli17\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] CreateProcessW("F:\Feature-test\angle\vcpkg\downloads\tools\cmake-3.22.2-windows\cmake-3.22.2-windows-i386\bin\cmake.exe" --version)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after    44571 us
[DEBUG] CreateProcessW("F:\Feature-test\angle\vcpkg\downloads\tools\cmake-3.22.2-windows\cmake-3.22.2-windows-i386\bin\cmake.exe" -DVCPKG_ROOT_DIR=F:/Feature-test/angle/vcpkg -DPACKAGES_DIR=F:/Feature-test/angle/vcpkg/packages -DBUILDTREES_DIR=F:/Feature-test/angle/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=F:/Feature-test/angle/vcpkg/installed -DDOWNLOADS=F:/Feature-test/angle/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "F:\Feature-test\angle\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after    20858 us
The following packages will be built and installed:
    angle[core]:x64-windows -> chromium_4472#3
[DEBUG] CreateProcessW("C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -all -prerelease -legacy -products * -format xml)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after    33588 us
Detecting compiler hash for triplet "x64-windows"...
[DEBUG] Found path: C:\Program Files\Git\cmd\git.exe
[DEBUG] CreateProcessW("C:\Program Files\Git\cmd\git.exe" --version)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after    30931 us
[DEBUG] CreateProcessW("F:\Feature-test\angle\vcpkg\downloads\tools\powershell-core-7.2.3-windows\pwsh.exe" --version)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after   175927 us
[DEBUG] command line: cmd /c "C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary/Build\vcvarsall.bat" -vcvars_ver=14.33.31517 amd64   2>&1 <NUL  & echo cdARN4xjKueKScMy9C6H & set
[DEBUG] CreateProcessW(cmd /c "C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary/Build\vcvarsall.bat" -vcvars_ver=14.33.31517 amd64   2>&1 <NUL  & echo cdARN4xjKueKScMy9C6H & set)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after   903805 us
[DEBUG] **********************************************************************
** Visual Studio 2022 Developer Command Prompt v17.3.0-pre.2.0
** Copyright (c) 2022 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x64'
cdARN4xjKueKScMy9C6H
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\vzhli17\AppData\Roaming
CommandPromptType=Native
CommonProgramFiles=C:\Program Files (x86)\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=vzhli17002
ComSpec=C:\WINDOWS\system32\cmd.exe
DevEnvDir=C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\
ExtensionSdkDir=C:\Program Files (x86)\Microsoft SDKs\Windows Kits\10\ExtensionSDKs
EXTERNAL_INCLUDE=C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31517\include;C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31517\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.20348.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.20348.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.20348.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.20348.0\\cppwinrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um
Framework40Version=v4.0
FrameworkDir=C:\Windows\Microsoft.NET\Framework64\
FrameworkDir64=C:\Windows\Microsoft.NET\Framework64\
FrameworkVersion=v4.0.30319
FrameworkVersion64=v4.0.30319
HOMEDRIVE=C:
HOMEPATH=\Users\vzhli17
INCLUDE=C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31517\include;C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31517\ATLMFC\include;C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Auxiliary\VS\include;C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\ucrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.20348.0\\um;C:\Program Files (x86)\Windows Kits\10\\include\10.0.20348.0\\shared;C:\Program Files (x86)\Windows Kits\10\\include\10.0.20348.0\\winrt;C:\Program Files (x86)\Windows Kits\10\\include\10.0.20348.0\\cppwinrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um
LIB=C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31517\ATLMFC\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31517\lib\x64;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\lib\um\x64;C:\Program Files (x86)\Windows Kits\10\lib\10.0.20348.0\ucrt\x64;C:\Program Files (x86)\Windows Kits\10\\lib\10.0.20348.0\\um\x64
LIBPATH=C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31517\ATLMFC\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31517\lib\x64;C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31517\lib\x86\store\references;C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.20348.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.20348.0;C:\Windows\Microsoft.NET\Framework64\v4.0.30319
LOCALAPPDATA=C:\Users\vzhli17\AppData\Local
LOGONSERVER=\\vzhli17002
NETFXSDKDir=C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\
NUMBER_OF_PROCESSORS=8
OS=Windows_NT
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
Platform=x64
PROCESSOR_ARCHITECTURE=x86
PROCESSOR_ARCHITEW6432=AMD64
PROCESSOR_IDENTIFIER=AMD64 Family 25 Model 1 Stepping 1, AuthenticAMD
PROCESSOR_LEVEL=25
PROCESSOR_REVISION=0101
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files (x86)
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=C:\Users\vzhli17\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules;C:\Program Files\Microsoft Monitoring Agent\Agent\PowerShell\
PUBLIC=C:\Users\Public
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\vzhli17\AppData\Local\Temp
TMP=C:\Users\vzhli17\AppData\Local\Temp
UCRTVersion=10.0.20348.0
UniversalCRTSdkDir=C:\Program Files (x86)\Windows Kits\10\
USERDOMAIN=vzhli17002
USERDOMAIN_ROAMINGPROFILE=vzhli17002
USERNAME=vzhli17
USERPROFILE=C:\Users\vzhli17
VCIDEInstallDir=C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\VC\
VCINSTALLDIR=C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\
VCToolsInstallDir=C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31517\
VCToolsRedistDir=C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Redist\MSVC\14.32.31326\
VCToolsVersion=14.33.31517
VisualStudioVersion=17.0
VS170COMNTOOLS=C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\Tools\
VSCMD_ARG_app_plat=Desktop
VSCMD_ARG_HOST_ARCH=x64
VSCMD_ARG_TGT_ARCH=x64
VSCMD_ARG_VCVARS_VER=14.33.31517
VSCMD_VER=17.3.0-pre.2.0
VSINSTALLDIR=C:\Program Files\Microsoft Visual Studio\2022\Preview\
windir=C:\WINDOWS
CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7
NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
VULKAN_SDK=C:\VulkanSDK\1.2.182.0
PATH=C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools\MSVC\14.33.31517\bin\HostX64\x64;C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\VC\VCPackages;C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\bin\Roslyn;C:\Program Files\Microsoft Visual Studio\2022\Preview\Team Tools\Performance Tools\x64;C:\Program Files\Microsoft Visual Studio\2022\Preview\Team Tools\Performance Tools;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\\x64;C:\Program Files (x86)\Microsoft Visual Studio\Shared\Common\VSPerfCollectionTools\vs2019\;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\Extensions\Microsoft\CodeCoverage.Console;C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\\x64;C:\Program Files (x86)\Windows Kits\10\bin\\x64;C:\Program Files\Microsoft Visual Studio\2022\Preview\\MSBuild\Current\Bin\amd64;C:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\;C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\Tools\;F:\Feature-test\angle\vcpkg\downloads\tools\powershell-core-7.2.3-windows;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\Wbem;C:\WINDOWS\system32\WindowsPowerShell\v1.0\;C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja;C:\Program Files\Microsoft Visual Studio\2022\Preview\Common7\IDE\VC\Linux\bin\ConnectionManagerExe
VSLANG=1033
VSCMD_SKIP_SENDTELEMETRY=1
VCPKG_COMMAND=F:/Feature-test/angle/vcpkg/vcpkg.exe
WindowsLibPath=C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.20348.0;C:\Program Files (x86)\Windows Kits\10\References\10.0.20348.0
WindowsSdkBinPath=C:\Program Files (x86)\Windows Kits\10\bin\
WindowsSdkDir=C:\Program Files (x86)\Windows Kits\10\
WindowsSDKLibVersion=10.0.20348.0\
WindowsSdkVerBinPath=C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\
WindowsSDKVersion=10.0.20348.0\
WindowsSDK_ExecutablePath_x64=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\
WindowsSDK_ExecutablePath_x86=C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\
X_VCPKG_RECURSIVE_DATA={}

__DOTNET_ADD_64BIT=1
__DOTNET_PREFERRED_BITNESS=64
__VSCMD_PREINIT_PATH=F:\Feature-test\angle\vcpkg\downloads\tools\powershell-core-7.2.3-windows;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\Wbem;C:\WINDOWS\system32\WindowsPowerShell\v1.0\

[DEBUG] CreateProcessW("F:\Feature-test\angle\vcpkg\downloads\tools\cmake-3.22.2-windows\cmake-3.22.2-windows-i386\bin\cmake.exe" -DCURRENT_PORT_DIR=F:/Feature-test/angle/vcpkg/scripts/detect_compiler -DCURRENT_BUILDTREES_DIR=F:/Feature-test/angle/vcpkg/buildtrees/detect_compiler -DCURRENT_PACKAGES_DIR=F:/Feature-test/angle/vcpkg/packages/detect_compiler_x64-windows -D_HOST_TRIPLET=x64-windows -DCMD=BUILD -DDOWNLOADS=F:/Feature-test/angle/vcpkg/downloads -DTARGET_TRIPLET=x64-windows -DTARGET_TRIPLET_FILE=F:/Feature-test/angle/vcpkg/triplets/x64-windows.cmake -DVCPKG_BASE_VERSION=2022-06-17 -DVCPKG_CONCURRENCY=9 -DVCPKG_PLATFORM_TOOLSET=v143 "-DGIT=C:/Program Files/Git/cmd/git.exe" -DVCPKG_ROOT_DIR=F:/Feature-test/angle/vcpkg -DPACKAGES_DIR=F:/Feature-test/angle/vcpkg/packages -DBUILDTREES_DIR=F:/Feature-test/angle/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=F:/Feature-test/angle/vcpkg/installed -DDOWNLOADS=F:/Feature-test/angle/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "F:\Feature-test\angle\vcpkg\scripts\ports.cmake")
[DEBUG] -- Found external ninja('1.10.2').
[DEBUG] -- Configuring x64-windows
[DEBUG] [1/1] cmd /c "cd .. && "F:/Feature-test/angle/vcpkg/downloads/tools/cmake-3.22.2-windows/cmake-3.22.2-windows-i386/bin/cmake.exe" "F:/Feature-test/angle/vcpkg/scripts/detect_compiler" "-G" "Ninja" "-DCMAKE_BUILD_TYPE=Release" "-DCMAKE_INSTALL_PREFIX=F:/Feature-test/angle/vcpkg/packages/detect_compiler_x64-windows" "-DCMAKE_MAKE_PROGRAM=C:/Program Files/Microsoft Visual Studio/2022/Preview/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" "-DBUILD_SHARED_LIBS=ON" "-DVCPKG_CHAINLOAD_TOOLCHAIN_FILE=F:/Feature-test/angle/vcpkg/scripts/toolchains/windows.cmake" "-DVCPKG_TARGET_TRIPLET=x64-windows" "-DVCPKG_SET_CHARSET_FLAG=ON" "-DVCPKG_PLATFORM_TOOLSET=v143" "-DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_PACKAGE_REGISTRY=ON" "-DCMAKE_FIND_PACKAGE_NO_SYSTEM_PACKAGE_REGISTRY=ON" "-DCMAKE_INSTALL_SYSTEM_RUNTIME_LIBS_SKIP=TRUE" "-DCMAKE_VERBOSE_MAKEFILE=ON" "-DVCPKG_APPLOCAL_DEPS=OFF" "-DCMAKE_TOOLCHAIN_FILE=F:/Feature-test/angle/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DCMAKE_ERROR_ON_ABSOLUTE_INSTALL_DESTINATION=ON" "-DVCPKG_CXX_FLAGS=" "-DVCPKG_CXX_FLAGS_RELEASE=" "-DVCPKG_CXX_FLAGS_DEBUG=" "-DVCPKG_C_FLAGS=" "-DVCPKG_C_FLAGS_RELEASE=" "-DVCPKG_C_FLAGS_DEBUG=" "-DVCPKG_CRT_LINKAGE=dynamic" "-DVCPKG_LINKER_FLAGS=" "-DVCPKG_LINKER_FLAGS_RELEASE=" "-DVCPKG_LINKER_FLAGS_DEBUG=" "-DVCPKG_TARGET_ARCHITECTURE=x64" "-DCMAKE_INSTALL_LIBDIR:STRING=lib" "-DCMAKE_INSTALL_BINDIR:STRING=bin" "-D_VCPKG_ROOT_DIR=F:/Feature-test/angle/vcpkg" "-DZ_VCPKG_ROOT_DIR=F:/Feature-test/angle/vcpkg" "-D_VCPKG_INSTALLED_DIR=F:/Feature-test/angle/vcpkg/installed" "-DVCPKG_MANIFEST_INSTALL=OFF""
[DEBUG] -- The C compiler identification is MSVC 19.33.31517.0
[DEBUG] -- The CXX compiler identification is MSVC 19.33.31517.0
[DEBUG] #COMPILER_HASH#b7cece5b71ff153d91ec2ab31d43cc08bbf064c7
[DEBUG] #COMPILER_C_HASH#8e0c6fdfdd332a2c20d9fbd97f1078e91f997262
[DEBUG] #COMPILER_C_VERSION#19.33.31517.0
[DEBUG] #COMPILER_C_ID#MSVC
[DEBUG] #COMPILER_CXX_HASH#8e0c6fdfdd332a2c20d9fbd97f1078e91f997262
[DEBUG] #COMPILER_CXX_VERSION#19.33.31517.0
[DEBUG] #COMPILER_CXX_ID#MSVC
[DEBUG] -- Configuring done
[DEBUG] -- Generating done
[DEBUG] CMake Warning:
[DEBUG]   Manually-specified variables were not used by the project:
[DEBUG]
[DEBUG]     BUILD_SHARED_LIBS
[DEBUG]     CMAKE_INSTALL_BINDIR
[DEBUG]     CMAKE_INSTALL_LIBDIR
[DEBUG]     _VCPKG_ROOT_DIR
[DEBUG]
[DEBUG]
[DEBUG] -- Build files have been written to: F:/Feature-test/angle/vcpkg/buildtrees/detect_compiler/x64-windows-rel
[DEBUG]
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after  1315549 us
[DEBUG]
[DEBUG] Detected compiler hash for triplet x64-windows: b7cece5b71ff153d91ec2ab31d43cc08bbf064c7
[DEBUG] <abientries for angle:x64-windows>
[DEBUG]   001-fix-uwp.patch|1e89a9e67d6b91f43da9fb91e0d4d572559cf9607a60acc5b64cc9621aec603c
[DEBUG]   002-fix-builder-error.patch|ed6fd734073cb700917a940dcf421eaa02e529a6407ab77c8ed56072e367102e
[DEBUG]   003-fix-mingw.patch|67f12c439b0237b03baf6fbc14ccf8563134b91d8a0643bc9d78d0176360e6ff
[DEBUG]   CMakeLists.txt|ac792e7dd55b01a9e5193116e43abb39b3b5aac4952fe793c0dcf6e8b036b825
[DEBUG]   angle_commit.h|55480e2a599e318176a606eb7d970424fc8b14545ea4af5484c8116621ac5e54
[DEBUG]   cmake|3.22.2
[DEBUG]   egl-registry|5ca86991d84606190cd48d146f6f9182ab62ba98d0749b09f573e2b944b12e59
[DEBUG]   features|core
[DEBUG]   opengl-registry|ee616e7fce36e7fe263305032f5ac901a798d92eaf9fe7dd73d18ad39b14c372
[DEBUG]   portfile.cmake|0416974444beb255ad7775ef89940c738a89b04e8f9ea07d40ba7c5d23dbb33f
[DEBUG]   ports.cmake|366c60b768113102408b32ac1d7c7b48ef7d30a477af2a220ecc222d9ffa3166
[DEBUG]   post_build_checks|2
[DEBUG]   powershell|7.2.3
[DEBUG]   third-party-zlib-far-undef.patch|d3401187d7dd3276960a8e8ca008cda942c358683a92f5e19e7a9f274c717e81
[DEBUG]   triplet|x64-windows
[DEBUG]   triplet_abi|e856e91ff3a0473d3637cbfb3759b371a5888979594a08d646493ed634204ea8-c0600b35e024ce0485ed253ef5419f3686f7257cfb58cb6a24febcb600fc4b4c-b7cece5b71ff153d91ec2ab31d43cc08bbf064c7
[DEBUG]   vcpkg.json|e38f5cef58a1df69f03d773a7740b6d1c0aa36721d82419d93f0c21e720a03be
[DEBUG]   vcpkg_configure_cmake|d0c91ccd76e01a9ec2f3a497e0102bbedc1a54a304e89892833ee00f09cbba35
[DEBUG]   vcpkg_copy_pdbs|d57e4f196c82dc562a9968c6155073094513c31e2de475694143d3aa47954b1c
[DEBUG]   vcpkg_fixup_cmake_targets|7f777f83ca76540ed573d986ee53d1b3da1e45f49f3856c44c0773fec71cb49f
[DEBUG]   vcpkg_from_git|0aab20e34e84d52ba4763f009e539bfa8f418c41c918c8cf700156f1a8551a10
[DEBUG]   vcpkg_from_github|b743742296a114ea1b18ae99672e02f142c4eb2bef7f57d36c038bedbfb0502f
[DEBUG]   vcpkg_install_cmake|6119891902c6ad9e9ed1d9b073eb9969159b553f9d6f5bee529cde91769355ff
[DEBUG]   zlib|5a267831d194098826fb5f554738843b17cec1f0fc456952f6cd5562752c3191
[DEBUG] </abientries>
Restored 0 packages from C:\Users\vzhli17\AppData\Local\vcpkg\archives in 219.7 us. Use --debug to see more details.
Installing 1/1 angle:x64-windows...
Building angle[core]:x64-windows...
[DEBUG] CreateProcessW("F:\Feature-test\angle\vcpkg\downloads\tools\cmake-3.22.2-windows\cmake-3.22.2-windows-i386\bin\cmake.exe" -DALL_FEATURES= -DCURRENT_PORT_DIR=F:/Feature-test/angle/vcpkg/ports/angle -D_HOST_TRIPLET=x64-windows -DFEATURES=core -DPORT=angle -DVCPKG_USE_HEAD_VERSION=0 -D_VCPKG_DOWNLOAD_TOOL=BUILT_IN -D_VCPKG_EDITABLE=0 -D_VCPKG_NO_DOWNLOADS=0 -DZ_VCPKG_CHAINLOAD_TOOLCHAIN_FILE=F:/Feature-test/angle/vcpkg/scripts/toolchains/windows.cmake -DCMD=BUILD -DDOWNLOADS=F:/Feature-test/angle/vcpkg/downloads -DTARGET_TRIPLET=x64-windows -DTARGET_TRIPLET_FILE=F:/Feature-test/angle/vcpkg/triplets/x64-windows.cmake -DVCPKG_BASE_VERSION=2022-06-17 -DVCPKG_CONCURRENCY=9 -DVCPKG_PLATFORM_TOOLSET=v143 "-DGIT=C:/Program Files/Git/cmd/git.exe" -DVCPKG_ROOT_DIR=F:/Feature-test/angle/vcpkg -DPACKAGES_DIR=F:/Feature-test/angle/vcpkg/packages -DBUILDTREES_DIR=F:/Feature-test/angle/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=F:/Feature-test/angle/vcpkg/installed -DDOWNLOADS=F:/Feature-test/angle/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "F:\Feature-test\angle\vcpkg\scripts\ports.cmake")
-- Using cached google-angle-d15be77864e18f407c317be6f6bc06ee2b7d070a.tar.gz.
-- Cleaning sources at F:/Feature-test/angle/vcpkg/buildtrees/angle/src/ee2b7d070a-83a419ab43.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source F:/Feature-test/angle/vcpkg/downloads/google-angle-d15be77864e18f407c317be6f6bc06ee2b7d070a.tar.gz
-- Applying patch 001-fix-uwp.patch
-- Applying patch 002-fix-builder-error.patch
-- Applying patch 003-fix-mingw.patch
-- Using source at F:/Feature-test/angle/vcpkg/buildtrees/angle/src/ee2b7d070a-83a419ab43.clean
-- Using cached F:/Feature-test/angle/vcpkg/downloads/angle-09490503d0f201b81e03f5ca0ab8ba8ee76d4a8e.tar.gz
-- Extracting source F:/Feature-test/angle/vcpkg/downloads/angle-09490503d0f201b81e03f5ca0ab8ba8ee76d4a8e.tar.gz
-- Applying patch third-party-zlib-far-undef.patch
-- Using source at F:/Feature-test/angle/vcpkg/buildtrees/angle/src/8ee76d4a8e-895bfc7289.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: F:/Feature-test/angle/vcpkg/packages/angle_x64-windows/share/angle/copyright
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after 331198760 us
-- Performing post-build validation
[DEBUG] CreateProcessW("C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools/MSVC\14.33.31517\bin/HostX86/x86\dumpbin.exe" /exports "F:\Feature-test\angle\vcpkg\packages\angle_x64-windows\debug\bin\libEGL.dll")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after   422003 us
[DEBUG] CreateProcessW("C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools/MSVC\14.33.31517\bin/HostX86/x86\dumpbin.exe" /exports "F:\Feature-test\angle\vcpkg\packages\angle_x64-windows\debug\bin\libGLESv2.dll")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after   210699 us
[DEBUG] CreateProcessW("C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools/MSVC\14.33.31517\bin/HostX86/x86\dumpbin.exe" /exports "F:\Feature-test\angle\vcpkg\packages\angle_x64-windows\bin\libEGL.dll")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after    49729 us
[DEBUG] CreateProcessW("C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools/MSVC\14.33.31517\bin/HostX86/x86\dumpbin.exe" /exports "F:\Feature-test\angle\vcpkg\packages\angle_x64-windows\bin\libGLESv2.dll")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after   161817 us
[DEBUG] CreateProcessW("C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools/MSVC\14.33.31517\bin/HostX86/x86\dumpbin.exe" /dependents "F:\Feature-test\angle\vcpkg\packages\angle_x64-windows\debug\bin\libEGL.dll")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after    22647 us
[DEBUG] CreateProcessW("C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools/MSVC\14.33.31517\bin/HostX86/x86\dumpbin.exe" /dependents "F:\Feature-test\angle\vcpkg\packages\angle_x64-windows\debug\bin\libGLESv2.dll")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after    22648 us
[DEBUG] CreateProcessW("C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools/MSVC\14.33.31517\bin/HostX86/x86\dumpbin.exe" /dependents "F:\Feature-test\angle\vcpkg\packages\angle_x64-windows\bin\libEGL.dll")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after    22938 us
[DEBUG] CreateProcessW("C:\Program Files\Microsoft Visual Studio\2022\Preview\VC\Tools/MSVC\14.33.31517\bin/HostX86/x86\dumpbin.exe" /dependents "F:\Feature-test\angle\vcpkg\packages\angle_x64-windows\bin\libGLESv2.dll")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after    23633 us
-- Performing post-build validation done
[DEBUG] CreateProcessW("F:\Feature-test\angle\vcpkg\downloads\tools\7zip-21.07-windows\7za.exe" a "F:\Feature-test\angle\vcpkg\buildtrees\angle\x64-windows.zip" "F:\Feature-test\angle\vcpkg\packages\angle_x64-windows\*")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 3736: cmd_execute_and_stream_data() returned 0 after 100928311 us
Stored binary cache: C:\Users\vzhli17\AppData\Local\vcpkg\archives\48\48bf782da7275a968d108f8efef29f96ebb58a2f36b17e753402d6c10f1ce07f.zip
Elapsed time to handle angle:x64-windows: 7.257 min

Total elapsed time: 7.3 min

angle provides CMake targets:
    # this is heuristically generated, and may not be correct
    find_package(unofficial-angle CONFIG REQUIRED)
    # note: 9 additional targets are not displayed.    target_link_libraries(main PRIVATE unofficial::angle::libEGL unofficial::angle::libANGLE unofficial::angle::libGLESv2 unofficial::angle::angle_common)

[DEBUG] D:\a\_work\1\s\src\vcpkg\install.cpp(1287):
[DEBUG] Time in subprocesses: 435588414 us
[DEBUG] Time in parsing JSON: 165 us
[DEBUG] Time in JSON reader: 139 us
[DEBUG] Time in filesystem: 52977 us
[DEBUG] Time in loading ports: 913 us
[DEBUG] Exiting after 7.3 min (438019836 us)
````

**Comment by xiaozhuai** [comment]
> I successfully installed in 17.3.0-pre.2.0

@JonLiu1993 Great! Waiting for a stable release.

**Comment by jeremy-visionaid** [comment]
Still broken in 17.2.6. 

In case anyone is still in need of a workaround, you could add the following to the desired triplet config:

`set(VCPKG_PLATFORM_TOOLSET v142)`

**Comment by mattgirv** [comment]
17.3.0 has dropped and Angle is now building successfully 👍 

`Building angle[core]:x64-windows...
-- Using cached google-angle-d15be77864e18f407c317be6f6bc06ee2b7d070a.tar.gz.
-- Cleaning sources at C:/vcpkg/buildtrees/angle/src/ee2b7d070a-83a419ab43.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/vcpkg/downloads/google-angle-d15be77864e18f407c317be6f6bc06ee2b7d070a.tar.gz
-- Applying patch 001-fix-uwp.patch
-- Applying patch 002-fix-builder-error.patch
-- Applying patch 003-fix-mingw.patch
-- Using source at C:/vcpkg/buildtrees/angle/src/ee2b7d070a-83a419ab43.clean
-- Using cached C:/vcpkg/downloads/angle-09490503d0f201b81e03f5ca0ab8ba8ee76d4a8e.tar.gz
-- Extracting source C:/vcpkg/downloads/angle-09490503d0f201b81e03f5ca0ab8ba8ee76d4a8e.tar.gz
-- Applying patch third-party-zlib-far-undef.patch
-- Using source at C:/vcpkg/buildtrees/angle/src/8ee76d4a8e-895bfc7289.clean
-- Found external ninja('1.10.2').
-- Configuring x64-windows
-- Building x64-windows-dbg
-- Building x64-windows-rel
-- Installing: C:/vcpkg/packages/angle_x64-windows/share/angle/copyright
-- Performing post-build validation
-- Performing post-build validation done
Stored binary cache: C:\Users\main\AppData\Local\vcpkg\archives\32\32bb9ef2653d30c7ca032714fbab5dede5fd71f459e2b8838658da4dac66b37e.zip
Elapsed time to handle angle:x64-windows: 2.717 min`
