### ISSUE TITLE
Failed to parse CMake console output to locate block start/end markers. (when I want to install literally anything)

### ISSUE THREAD

**Issue by aarmn** [microsoft/vcpkg#25950]
I am not sure is it a "me" problem or a vcpkg bug (or maybe sth else), so to be safe, I opened this in here

I did all steps of installing vcpkg but whenever I want to install any package (that I tested yet, including pybind11, boost, sqlite3, and some parts of boost discretely) I constantly get this error:

```
Computing installation plan...
Failed to parse CMake console output to locate block start/end markers.
```

vcpkg is installed in E drive inside the project (I changed its path, and it didn't affect result)

Am I doing sth wrong? I googled and found nothing remotely useful

**Comment by dg0yt** [comment]
Do you use (bootstrap) the latest version of vcpkg?
Is the cmake version managed by vcpkg?
In the past, problems occured with `CLICOLOR_FORCE=1`, but this should be resolved (#20430).

**Comment by aarmn** [comment]
I cloned it from GitHub yesterday, so I guess, it's new?!
"Is the cmake version managed by vcpkg?"
I'm not sure, but I'm sure cmake was installed prior to vcpkg, therefore I guess no, cmake is not managed by vcpkg

**Comment by aarmn** [comment]
I tested solutions offered on the other thread, non seem to work,
because it seems like it's a popen parse issue, just to inform, I'm using PowerShell, on a Windows device, with Windows Terminal, but error persisted in cmd in wt as well
It may be an old cmake tho (cmake version 3.22.3)
can it be the cause?

**Comment by dg0yt** [comment]
CMake 3.22.3 is fine. 
For more output, try `.\vcpkg install --debug --debug-env zlib`.

**Comment by aarmn** [comment]
[DEBUG] The following environment variables are currently set:
ALLUSERSPROFILE=C:\ProgramData
ANDROID_SDK_ROOT=C:\Users\\AppData\Local\Android\Sdk
APPDATA=C:\Users\aarmn\AppData\Roaming
ChocolateyInstall=C:\ProgramData\chocolatey
ChocolateyLastPathUpdate=132709909149260773
ChocolateyToolsLocation=C:\tools
CHROME_EXECUTABLE=C:\Program Files\Google\Chrome Dev\Application\chrome.exe
CLICOLOR=0 // due to test got added here (post note)
CommonProgramFiles=C:\Program Files (x86)\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
ComSpec=C:\WINDOWS\system32\cmd.exe
DriverData=C:\Windows\System32\Drivers\DriverData
GIT_INSTALL_ROOT=C:\Users\aarmn\scoop\apps\git\current
GOPATH=C:\Users\aarmn\go
GTK_BASEPATH=C:\Program Files (x86)\GtkSharp\2.12\
HAXEPATH=C:\HaxeToolkit\haxe
HOMEDRIVE=C:
HOMEPATH=\Users\aarmn
IntelliJ IDEA=d:\Program Files\JetBrains\IntelliJ IDEA 2020.3.2\bin;
IntelliJ IDEA Community Edition=C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.3.1\bin;
INTEL_DEV_REDIST=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\
JAVA_HOME=C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25
JetBrains Rider=d:\Program Files\JetBrains\JetBrains Rider 2020.3.2\bin;
LOCALAPPDATA=C:\Users\aarmn\AppData\Local
MIC_LD_LIBRARY_PATH=C:\Program Files (x86)\Common Files\Intel\Shared Libraries\compiler\lib\mic
NEKO_INSTPATH=C:\HaxeToolkit\neko
NUMBER_OF_PROCESSORS=12
NVTOOLSEXT_PATH=C:\Program Files\NVIDIA Corporation\NvToolsExt\
OS=Windows_NT
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.PY;.PYW;.CPL
PORTABLE_APPS=D:\Semi-Portable
POWERSHELL_DISTRIBUTION_CHANNEL=MSI:Windows 10 Pro
PROCESSOR_ARCHITECTURE=x86
PROCESSOR_ARCHITEW6432=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=a502
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files (x86)
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PSModulePath=C:\Users\aarmn\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
PyCharm=c:\Program Files\JetBrains\PyCharm 2020.3.3\bin;
PyCharm Community Edition=C:\Program Files\JetBrains\PyCharm Community Edition 2021.1\bin;
Qemu=C:\Program Files\qemu
SESSIONNAME=Console
STARSHIP_SESSION_KEY=olNucqvbmYL6ntSA
STARSHIP_SHELL=powershell
Startmenu=C:\ProgramData\Microsoft\Windows\Start Menu\Programs
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\aarmn\AppData\Local\Temp
TMP=C:\Users\aarmn\AppData\Local\Temp
USERNAME=aarmn
USERPROFILE=C:\Users\aarmn
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
VCPKG_COMMAND=E:/vcpkg/vcpkg/vcpkg.exe
VIRTUAL_ENV_DISABLE_PROMPT=1
windir=C:\WINDOWS
X_VCPKG_RECURSIVE_DATA={}


[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'manifests' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Failed to open: E:\vcpkg\vcpkg\vcpkg-bundle.json
[DEBUG] Using scripts-root: E:\vcpkg\vcpkg\scripts
[DEBUG] Bundle config: readonly=0, usegitregistry=0, embeddedsha=nullopt
[DEBUG] Using builtin-ports: E:\vcpkg\vcpkg\ports
[DEBUG] Using installed-root: E:\vcpkg\vcpkg\installed
[DEBUG] Using buildtrees-root: E:\vcpkg\vcpkg\buildtrees
[DEBUG] Using packages-root: E:\vcpkg\vcpkg\packages
[DEBUG] Using vcpkg-root: E:\vcpkg\vcpkg
[DEBUG] Using scripts-root: E:\vcpkg\vcpkg\scripts
[DEBUG] Using builtin-registry: E:\vcpkg\vcpkg\versions
[DEBUG] Using downloads-root: E:\vcpkg\vcpkg\downloads
[DEBUG] Default binary cache path is: C:\Users\aarmn\AppData\Local\vcpkg\archives
Computing installation plan...
[DEBUG] Found path: C:\Users\aarmn\AppData\Roaming\Python\Python39\Scripts\cmake.exe
[DEBUG] Found path: D:\Program Files\CMake\bin\cmake.exe
[DEBUG] CreateProcessW("C:\Users\aarmn\AppData\Roaming\Python\Python39\Scripts\cmake.exe" --version)
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 20112: cmd_execute_and_stream_data() returned 0 after   181924 us
[DEBUG] CreateProcessW("C:\Users\aarmn\AppData\Roaming\Python\Python39\Scripts\cmake.exe" -DVCPKG_ROOT_DIR=E:/vcpkg/vcpkg -DPACKAGES_DIR=E:/vcpkg/vcpkg/packages -DBUILDTREES_DIR=E:/vcpkg/vcpkg/buildtrees -D_VCPKG_INSTALLED_DIR=E:/vcpkg/vcpkg/installed -DDOWNLOADS=E:/vcpkg/vcpkg/downloads -DVCPKG_MANIFEST_INSTALL=OFF -P "E:\vcpkg\vcpkg\buildtrees\0.vcpkg_tags.cmake")
[DEBUG] ReadFile() finished with GetLastError(): 109
[DEBUG] 20112: cmd_execute_and_stream_data() returned 0 after    87674 us
Failed to parse CMake console output to locate block start/end markers.
[DEBUG] D:\a\_work\1\s\src\vcpkg\cmakevars.cpp(297):
[DEBUG] Time in subprocesses: 269598 us
[DEBUG] Time in parsing JSON: 49 us
[DEBUG] Time in JSON reader: 81 us
[DEBUG] Time in filesystem: 6847 us
[DEBUG] Time in loading ports: 3256 us
[DEBUG] Exiting after 445.4 ms (440483 us)

**Comment by aarmn** [comment]
Path env var is not up there because it's super big and messy and may contain some info that I don't want to share to the world
but probably nothing much is going on there (the cmake and vcpkg are checked, actually I run vcpkg by absolute path)

**Comment by autoantwort** [comment]
C:\Users\aarmn\AppData\Roaming\Python\Python39\Scripts\cmake.exe

Looks very strange and not like a normal cmake installation

**Comment by dg0yt** [comment]
> GIT_INSTALL_ROOT=C:\Users\aarmn\scoop\apps\git\current

Just another issue in the context of scoop.
https://github.com/microsoft/vcpkg/search?q=scoop&type=issues

**Comment by aarmn** [comment]
> > GIT_INSTALL_ROOT=C:\Users\aarmn\scoop\apps\git\current
> 
> Just another issue in the context of scoop. https://github.com/microsoft/vcpkg/search?q=scoop&type=issues

Ok, and how can I fix it? Should I uninstall cmake and git, then reinstall them directly by their setup (in case it's a scoop issue)
while writing, I didn't check the link because it seems it's a broad list of issues related to it.

I feel a bit confuse, what should be my next action to resolve?

**Comment by dg0yt** [comment]
I would start with getting `C:\Users\aarmn\AppData\Roaming\Python\Python39\Scripts` out of the `PATH`, so that vcpkg uses its own download, or otherwise ensure a trustable CMake.

**Comment by aarmn** [comment]
Ok, issue is resolved by moving cmake (freshly official install) priority higher in my path, I don't know what was the conflicting binary and at this point I don't care either!

I guess it had sth to do with scoop or python, as you said (I moved it over `C:\Users\aarmn\AppData\Roaming\Python\Python39\Scripts` and `C:\Users\aarmn\AppData\Roaming\Python\Python310\Scripts`)

anyway, thanks for your help
