### ISSUE TITLE
[openssl] Build error

### ISSUE THREAD

**Issue by RoyZhang2022** [microsoft/vcpkg#27013]
**Host Environment**

- OS: Amazon Linux2, kernel is 5.10.135-122.509.amzn2.x86_64
- Compiler: g++ (GCC) 7.3.1 20180712 (Red Hat 7.3.1-15)

**To Reproduce**

```
git clone https://github.com/Microsoft/vcpkg.git 
 ./vcpkg/bootstrap-vcpkg.sh 
 ./vcpkg/vcpkg install "aws-sdk-cpp[core,sts,timestream-query]" --recurse
```

**Failure logs**

- Cut and paste the appropriate build messages from the console output.
- Attach ***every failure log file*** mentioned in the console output.

[1/3] cd /home/ec2-user/amazon-timestream-odbc-driver/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.5-30ecfd0d02.clean && export PATH=/usr/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/bin:/home/ec2-user/amazon-timestream-odbc-driver/vcpkg/downloads/tools/ninja/1.10.2-linux && export CC=/usr/bin/cc && export AR=/usr/bin/ar && export LD=/usr/bin/ld && export RANLIB=/usr/bin/ranlib && export MAKE=/usr/bin/make && export MAKEDEPPROG=/usr/bin/cc && export WINDRES= && /usr/bin/perl Configure no-shared no-module enable-static-engine no-zlib no-ssl2 no-idea no-cast no-seed no-md2 no-tests linux-x86_64 --prefix=/home/ec2-user/amazon-timestream-odbc-driver/vcpkg/packages/openssl_x64-linux/debug --libdir=/home/ec2-user/amazon-timestream-odbc-driver/vcpkg/packages/openssl_x64-linux/debug/lib --openssldir=/etc/ssl "-fPIC -g" && /home/ec2-user/amazon-timestream-odbc-driver/vcpkg/downloads/tools/cmake-3.24.0-linux/cmake-3.24.0-linux-x86_64/bin/cmake -DDIR=/home/ec2-user/amazon-timestream-odbc-driver/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.5-30ecfd0d02.clean -P /home/ec2-user/amazon-timestream-odbc-driver/vcpkg/ports/openssl/unix/remove-deps.cmake
FAILED: nssl-3.0.5-30ecfd0d02.clean/Makefile /home/ec2-user/amazon-timestream-odbc-driver/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.5-30ecfd0d02.clean/Makefile
cd /home/ec2-user/amazon-timestream-odbc-driver/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.5-30ecfd0d02.clean && export PATH=/usr/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin:/usr/bin:/home/ec2-user/amazon-timestream-odbc-driver/vcpkg/downloads/tools/ninja/1.10.2-linux && export CC=/usr/bin/cc && export AR=/usr/bin/ar && export LD=/usr/bin/ld && export RANLIB=/usr/bin/ranlib && export MAKE=/usr/bin/make && export MAKEDEPPROG=/usr/bin/cc && export WINDRES= && /usr/bin/perl Configure no-shared no-module enable-static-engine no-zlib no-ssl2 no-idea no-cast no-seed no-md2 no-tests linux-x86_64 --prefix=/home/ec2-user/amazon-timestream-odbc-driver/vcpkg/packages/openssl_x64-linux/debug --libdir=/home/ec2-user/amazon-timestream-odbc-driver/vcpkg/packages/openssl_x64-linux/debug/lib --openssldir=/etc/ssl "-fPIC -g" && /home/ec2-user/amazon-timestream-odbc-driver/vcpkg/downloads/tools/cmake-3.24.0-linux/cmake-3.24.0-linux-x86_64/bin/cmake -DDIR=/home/ec2-user/amazon-timestream-odbc-driver/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.5-30ecfd0d02.clean -P /home/ec2-user/amazon-timestream-odbc-driver/vcpkg/ports/openssl/unix/remove-deps.cmake
Can't locate IPC/Cmd.pm in @INC (@INC contains: /home/ec2-user/amazon-timestream-odbc-driver/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.5-30ecfd0d02.clean/util/perl /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 . /home/ec2-user/amazon-timestream-odbc-driver/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.5-30ecfd0d02.clean/external/perl/Text-Template-1.56/lib) at /home/ec2-user/amazon-timestream-odbc-driver/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.5-30ecfd0d02.clean/util/perl/OpenSSL/config.pm line 18.
BEGIN failed--compilation aborted at /home/ec2-user/amazon-timestream-odbc-driver/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.5-30ecfd0d02.clean/util/perl/OpenSSL/config.pm line 18.
Compilation failed in require at Configure line 24.
BEGIN failed--compilation aborted at Configure line 24.
ninja: build stopped: subcommand failed.
~

**Additional context**

-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:129 (message):
    Command failed: /home/ec2-user/amazon-timestream-odbc-driver/vcpkg/downloads/tools/cmake-3.24.0-linux/cmake-3.24.0-linux-x86_64/bin/cmake --build . --config Debug --target install -- -v -j3
    Working Directory: /home/ec2-user/amazon-timestream-odbc-driver/vcpkg/buildtrees/openssl/x64-linux-dbg
    See logs for more information:
      /home/ec2-user/amazon-timestream-odbc-driver/vcpkg/buildtrees/openssl/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  ports/openssl/unix/portfile.cmake:21 (vcpkg_cmake_install)
  ports/openssl/portfile.cmake:39 (include)
  scripts/ports.cmake:147 (include)

error: building openssl:x64-linux failed with: BUILD_FAILED
error: Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
    https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+openssl
You can submit a new issue at:
    https://github.com/microsoft/vcpkg/issues/new?template=report-package-build-failure.md&title=[openssl]+Build+error
Include '[openssl] Build error' in your bug report title, the following version information in your bug description, and attach any relevant failure logs from above.
    vcpkg-tool version: 2022-09-20-522aa94e9d261c7d7b2f079bf2591ca62df5c714
    vcpkg-scripts version: 6ca56aeb4 2022-09-26 (25 hours ago)

Add any other context about the problem here, such as what you have already tried to resolve the issue.

**Comment by RoyZhang2022** [comment]
$ sudo yum install perl-IPC-Cmd
`
Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
Package 1:perl-IPC-Cmd-0.80-4.amzn2.noarch already installed and latest version
Nothing to do
`

**Comment by LilyWangLL** [comment]
Maybe you can try to update `perl-IPC-Cmd`, like comment https://github.com/microsoft/vcpkg/issues/25729#issuecomment-1200337695. I can't reproduce this issue locally. I have only Ubuntu machine.

**Comment by RoyZhang2022** [comment]
After check the log and google the error info, I got a solution "yum install perl-Data-Dumper". Now the problem is fixed. Thanks  for your support!

**Comment by GavinRay97** [comment]
I also got this error, doing `sudo dnf install perl` fixed it on Fedora 38 for me:

```
Can't locate IPC/Cmd.pm in @INC (you may need to install the IPC::Cmd module) (@INC contains: /home/user/projects/bustub-cpp-reimpl/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.5-30ecfd0d02.clean/util/perl /usr/local/lib64/perl5/
5.36 /usr/local/share/perl5/5.36 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 /home/user/projects/bustub-cpp-reimpl/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.5-30ecfd0d02.clean/external/perl/Text-Template-1.56/lib) at /home/user/projects/bustub-cpp-reimpl/vcpkg/buildtrees/openssl/x64-linux-dbg/nssl-3.0.5-30ecfd0d02.clean/util/perl/OpenSSL/config.pm line 18.
```

Prior to this, I got an error about the Perl `FindBin` module, which I did `dnf install perl-FindBin` but that didn't fix it so I just installed everything.
