### ISSUE TITLE
[draco] error: ‘uint8_t’ was not declared in this scope

### ISSUE THREAD

**Issue by skrede** [microsoft/vcpkg#31270]
### Operating system

Linux, EndeavourOS

### Compiler

GCC

### Steps to reproduce the behavior

```Shell
`./vcpkg install draco` (in this case on a fresh install of EndeavourOS)

Missing cstdint-include.
```

### Failure logs

Package: draco[core]:x64-linux -> 1.5.3

**Host Environment**

- Host: x64-linux
- Compiler: GNU 13.1.1
-    vcpkg-tool version: 2023-04-07-bedcba5172f5e4b91caac660ab7afe92c27a9895
    vcpkg-scripts version: 60e2c07d2 2023-05-04 (13 hours ago)

**To Reproduce**

`vcpkg install --x-feature=boost --x-feature=orocos --x-feature=threepp`

**Failure logs**

```
-- Downloading https://github.com/google/draco/archive/1.5.3.tar.gz -> google-draco-1.5.3.tar.gz...
-- Extracting source /home/als/Applications/vcpkg/downloads/google-draco-1.5.3.tar.gz
-- Applying patch fix-compile-error-uwp.patch
-- Applying patch fix-uwperror.patch
-- Applying patch disable-symlinks.patch
-- Using source at /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean
-- Found external ninja('1.10.2').
-- Configuring x64-linux
-- Building x64-linux-dbg
CMake Error at scripts/cmake/vcpkg_execute_build_process.cmake:134 (message):
    Command failed: /usr/bin/cmake --build . --config Debug --target install -- -v -j33
    Working Directory: /home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg
    See logs for more information:
      /home/als/Applications/vcpkg/buildtrees/draco/install-x64-linux-dbg-out.log

Call Stack (most recent call first):
  /home/als/Workspace/cortex/cmake-build-debug/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_build.cmake:74 (vcpkg_execute_build_process)
  /home/als/Workspace/cortex/cmake-build-debug/vcpkg_installed/x64-linux/share/vcpkg-cmake/vcpkg_cmake_install.cmake:16 (vcpkg_cmake_build)
  /home/als/.cache/vcpkg/registries/git-trees/b4f39e03fdf47c2c1e9a945b362ed52ec098a354/portfile.cmake:19 (vcpkg_cmake_install)
  scripts/ports.cmake:147 (include)



```
<details><summary>/home/als/Applications/vcpkg/buildtrees/draco/install-x64-linux-dbg-out.log</summary>

```
[1/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_bit_coders.dir/src/draco/compression/bit_coders/adaptive_rans_bit_decoder.cc.o -MF CMakeFiles/draco_compression_bit_coders.dir/src/draco/compression/bit_coders/adaptive_rans_bit_decoder.cc.o.d -o CMakeFiles/draco_compression_bit_coders.dir/src/draco/compression/bit_coders/adaptive_rans_bit_decoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/bit_coders/adaptive_rans_bit_decoder.cc
[2/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_bit_coders.dir/src/draco/compression/bit_coders/rans_bit_decoder.cc.o -MF CMakeFiles/draco_compression_bit_coders.dir/src/draco/compression/bit_coders/rans_bit_decoder.cc.o.d -o CMakeFiles/draco_compression_bit_coders.dir/src/draco/compression/bit_coders/rans_bit_decoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/bit_coders/rans_bit_decoder.cc
[3/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_bit_coders.dir/src/draco/compression/bit_coders/direct_bit_decoder.cc.o -MF CMakeFiles/draco_compression_bit_coders.dir/src/draco/compression/bit_coders/direct_bit_decoder.cc.o.d -o CMakeFiles/draco_compression_bit_coders.dir/src/draco/compression/bit_coders/direct_bit_decoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/bit_coders/direct_bit_decoder.cc
[4/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_bit_coders.dir/src/draco/compression/bit_coders/direct_bit_encoder.cc.o -MF CMakeFiles/draco_compression_bit_coders.dir/src/draco/compression/bit_coders/direct_bit_encoder.cc.o.d -o CMakeFiles/draco_compression_bit_coders.dir/src/draco/compression/bit_coders/direct_bit_encoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/bit_coders/direct_bit_encoder.cc
...
Skipped 177 lines
...

[50/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_attributes_enc.dir/src/draco/compression/attributes/sequential_normal_attribute_encoder.cc.o -MF CMakeFiles/draco_compression_attributes_enc.dir/src/draco/compression/attributes/sequential_normal_attribute_encoder.cc.o.d -o CMakeFiles/draco_compression_attributes_enc.dir/src/draco/compression/attributes/sequential_normal_attribute_encoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/sequential_normal_attribute_encoder.cc
In file included from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_geometric_normal_predictor_base.h:26,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_geometric_normal_predictor_area.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_geometric_normal_encoder.h:19,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/prediction_scheme_encoder_factory.h:23,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/sequential_normal_attribute_encoder.h:19,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/sequential_normal_attribute_encoder.cc:15:
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:25:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
   25 |     : public std::iterator<std::forward_iterator_tag, VertexIndex> {
      |                   ^~~~~~~~
In file included from /usr/include/c++/13.1.1/bits/stl_construct.h:61,
                 from /usr/include/c++/13.1.1/bits/stl_tempbuf.h:61,
                 from /usr/include/c++/13.1.1/memory:66,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/attributes/attribute_transform_data.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/attributes/attribute_transform.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/attributes/attribute_octahedron_transform.h:19,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/sequential_normal_attribute_encoder.h:18:
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:115:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
  115 |     : public std::iterator<std::forward_iterator_tag, FaceIndex> {
      |                   ^~~~~~~~
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:197:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
  197 |     : public std::iterator<std::forward_iterator_tag, CornerIndex> {
      |                   ^~~~~~~~
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
[51/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_attributes_enc.dir/src/draco/compression/attributes/sequential_integer_attribute_encoder.cc.o -MF CMakeFiles/draco_compression_attributes_enc.dir/src/draco/compression/attributes/sequential_integer_attribute_encoder.cc.o.d -o CMakeFiles/draco_compression_attributes_enc.dir/src/draco/compression/attributes/sequential_integer_attribute_encoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/sequential_integer_attribute_encoder.cc
In file included from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_geometric_normal_predictor_base.h:26,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_geometric_normal_predictor_area.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_geometric_normal_encoder.h:19,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/prediction_scheme_encoder_factory.h:23,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/sequential_integer_attribute_encoder.cc:17:
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:25:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
   25 |     : public std::iterator<std::forward_iterator_tag, VertexIndex> {
      |                   ^~~~~~~~
In file included from /usr/include/c++/13.1.1/bits/stl_construct.h:61,
                 from /usr/include/c++/13.1.1/bits/stl_tempbuf.h:61,
                 from /usr/include/c++/13.1.1/memory:66,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/attributes/point_attribute.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/prediction_scheme_interface.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/prediction_scheme_encoder_interface.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/prediction_scheme_encoder.h:20,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/sequential_integer_attribute_encoder.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/sequential_integer_attribute_encoder.cc:15:
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:115:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
  115 |     : public std::iterator<std::forward_iterator_tag, FaceIndex> {
      |                   ^~~~~~~~
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:197:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
  197 |     : public std::iterator<std::forward_iterator_tag, CornerIndex> {
      |                   ^~~~~~~~
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
[52/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_mesh_enc.dir/src/draco/compression/mesh/mesh_edgebreaker_encoder.cc.o -MF CMakeFiles/draco_compression_mesh_enc.dir/src/draco/compression/mesh/mesh_edgebreaker_encoder.cc.o.d -o CMakeFiles/draco_compression_mesh_enc.dir/src/draco/compression/mesh/mesh_edgebreaker_encoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/mesh/mesh_edgebreaker_encoder.cc
[53/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_attributes_dec.dir/src/draco/compression/attributes/sequential_integer_attribute_decoder.cc.o -MF CMakeFiles/draco_compression_attributes_dec.dir/src/draco/compression/attributes/sequential_integer_attribute_decoder.cc.o.d -o CMakeFiles/draco_compression_attributes_dec.dir/src/draco/compression/attributes/sequential_integer_attribute_decoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/sequential_integer_attribute_decoder.cc
In file included from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_geometric_normal_predictor_base.h:26,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_geometric_normal_predictor_area.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/mesh_prediction_scheme_geometric_normal_decoder.h:19,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/prediction_scheme_decoder_factory.h:24,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/sequential_integer_attribute_decoder.cc:17:
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:25:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
   25 |     : public std::iterator<std::forward_iterator_tag, VertexIndex> {
      |                   ^~~~~~~~
In file included from /usr/include/c++/13.1.1/bits/stl_construct.h:61,
                 from /usr/include/c++/13.1.1/bits/stl_tempbuf.h:61,
                 from /usr/include/c++/13.1.1/memory:66,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/attributes/point_attribute.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/prediction_scheme_interface.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/prediction_scheme_decoder_interface.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/prediction_schemes/prediction_scheme_decoder.h:20,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/sequential_integer_attribute_decoder.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/sequential_integer_attribute_decoder.cc:15:
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:115:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
  115 |     : public std::iterator<std::forward_iterator_tag, FaceIndex> {
      |                   ^~~~~~~~
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:197:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
  197 |     : public std::iterator<std::forward_iterator_tag, CornerIndex> {
      |                   ^~~~~~~~
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
[54/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_point_cloud_dec.dir/src/draco/compression/point_cloud/point_cloud_sequential_decoder.cc.o -MF CMakeFiles/draco_compression_point_cloud_dec.dir/src/draco/compression/point_cloud/point_cloud_sequential_decoder.cc.o.d -o CMakeFiles/draco_compression_point_cloud_dec.dir/src/draco/compression/point_cloud/point_cloud_sequential_decoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/point_cloud/point_cloud_sequential_decoder.cc
[55/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_io.dir/src/draco/io/stdio_file_writer.cc.o -MF CMakeFiles/draco_io.dir/src/draco/io/stdio_file_writer.cc.o.d -o CMakeFiles/draco_io.dir/src/draco/io/stdio_file_writer.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/stdio_file_writer.cc
[56/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_io.dir/src/draco/io/parser_utils.cc.o -MF CMakeFiles/draco_io.dir/src/draco/io/parser_utils.cc.o.d -o CMakeFiles/draco_io.dir/src/draco/io/parser_utils.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/parser_utils.cc
[57/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_io.dir/src/draco/io/stdio_file_reader.cc.o -MF CMakeFiles/draco_io.dir/src/draco/io/stdio_file_reader.cc.o.d -o CMakeFiles/draco_io.dir/src/draco/io/stdio_file_reader.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/stdio_file_reader.cc
[58/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_point_cloud_enc.dir/src/draco/compression/point_cloud/point_cloud_kd_tree_encoder.cc.o -MF CMakeFiles/draco_compression_point_cloud_enc.dir/src/draco/compression/point_cloud/point_cloud_kd_tree_encoder.cc.o.d -o CMakeFiles/draco_compression_point_cloud_enc.dir/src/draco/compression/point_cloud/point_cloud_kd_tree_encoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/point_cloud/point_cloud_kd_tree_encoder.cc
[59/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_attributes_enc.dir/src/draco/compression/attributes/kd_tree_attributes_encoder.cc.o -MF CMakeFiles/draco_compression_attributes_enc.dir/src/draco/compression/attributes/kd_tree_attributes_encoder.cc.o.d -o CMakeFiles/draco_compression_attributes_enc.dir/src/draco/compression/attributes/kd_tree_attributes_encoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/kd_tree_attributes_encoder.cc
In file included from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/kd_tree_attributes_encoder.cc:18:
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/point_d_vector.h:103:21: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
  103 |       : public std::iterator<std::random_access_iterator_tag, size_t, size_t> {
      |                     ^~~~~~~~
In file included from /usr/include/c++/13.1.1/bits/stl_algobase.h:65,
                 from /usr/include/c++/13.1.1/vector:62,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/attributes/attribute_quantization_transform.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/kd_tree_attributes_encoder.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/kd_tree_attributes_encoder.cc:15:
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
[60/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_mesh_enc.dir/src/draco/compression/mesh/mesh_sequential_encoder.cc.o -MF CMakeFiles/draco_compression_mesh_enc.dir/src/draco/compression/mesh/mesh_sequential_encoder.cc.o.d -o CMakeFiles/draco_compression_mesh_enc.dir/src/draco/compression/mesh/mesh_sequential_encoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/mesh/mesh_sequential_encoder.cc
[61/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_point_cloud_enc.dir/src/draco/compression/point_cloud/point_cloud_sequential_encoder.cc.o -MF CMakeFiles/draco_compression_point_cloud_enc.dir/src/draco/compression/point_cloud/point_cloud_sequential_encoder.cc.o.d -o CMakeFiles/draco_compression_point_cloud_enc.dir/src/draco/compression/point_cloud/point_cloud_sequential_encoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/point_cloud/point_cloud_sequential_encoder.cc
[62/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_point_cloud_enc.dir/src/draco/compression/point_cloud/point_cloud_encoder.cc.o -MF CMakeFiles/draco_compression_point_cloud_enc.dir/src/draco/compression/point_cloud/point_cloud_encoder.cc.o.d -o CMakeFiles/draco_compression_point_cloud_enc.dir/src/draco/compression/point_cloud/point_cloud_encoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/point_cloud/point_cloud_encoder.cc
[63/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_attributes_dec.dir/src/draco/compression/attributes/kd_tree_attributes_decoder.cc.o -MF CMakeFiles/draco_compression_attributes_dec.dir/src/draco/compression/attributes/kd_tree_attributes_decoder.cc.o.d -o CMakeFiles/draco_compression_attributes_dec.dir/src/draco/compression/attributes/kd_tree_attributes_decoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/attributes/kd_tree_attributes_decoder.cc
[64/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_attributes.dir/src/draco/attributes/point_attribute.cc.o -MF CMakeFiles/draco_attributes.dir/src/draco/attributes/point_attribute.cc.o.d -o CMakeFiles/draco_attributes.dir/src/draco/attributes/point_attribute.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/attributes/point_attribute.cc
[65/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_io.dir/src/draco/io/ply_encoder.cc.o -MF CMakeFiles/draco_io.dir/src/draco/io/ply_encoder.cc.o.d -o CMakeFiles/draco_io.dir/src/draco/io/ply_encoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/ply_encoder.cc
[66/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_entropy.dir/src/draco/compression/entropy/symbol_encoding.cc.o -MF CMakeFiles/draco_compression_entropy.dir/src/draco/compression/entropy/symbol_encoding.cc.o.d -o CMakeFiles/draco_compression_entropy.dir/src/draco/compression/entropy/symbol_encoding.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/entropy/symbol_encoding.cc
[67/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_io.dir/src/draco/io/stl_decoder.cc.o -MF CMakeFiles/draco_io.dir/src/draco/io/stl_decoder.cc.o.d -o CMakeFiles/draco_io.dir/src/draco/io/stl_decoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/stl_decoder.cc
[68/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_mesh.dir/src/draco/mesh/corner_table.cc.o -MF CMakeFiles/draco_mesh.dir/src/draco/mesh/corner_table.cc.o.d -o CMakeFiles/draco_mesh.dir/src/draco/mesh/corner_table.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table.cc
In file included from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table.cc:20:
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:25:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
   25 |     : public std::iterator<std::forward_iterator_tag, VertexIndex> {
      |                   ^~~~~~~~
In file included from /usr/include/c++/13.1.1/bits/stl_algobase.h:65,
                 from /usr/include/c++/13.1.1/array:43,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table.cc:15:
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:115:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
  115 |     : public std::iterator<std::forward_iterator_tag, FaceIndex> {
      |                   ^~~~~~~~
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:197:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
  197 |     : public std::iterator<std::forward_iterator_tag, CornerIndex> {
      |                   ^~~~~~~~
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
[69/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_io.dir/src/draco/io/obj_decoder.cc.o -MF CMakeFiles/draco_io.dir/src/draco/io/obj_decoder.cc.o.d -o CMakeFiles/draco_io.dir/src/draco/io/obj_decoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/obj_decoder.cc
[70/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_io.dir/src/draco/io/point_cloud_io.cc.o -MF CMakeFiles/draco_io.dir/src/draco/io/point_cloud_io.cc.o.d -o CMakeFiles/draco_io.dir/src/draco/io/point_cloud_io.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/point_cloud_io.cc
[71/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_io.dir/src/draco/io/mesh_io.cc.o -MF CMakeFiles/draco_io.dir/src/draco/io/mesh_io.cc.o.d -o CMakeFiles/draco_io.dir/src/draco/io/mesh_io.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/mesh_io.cc
[72/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_io.dir/src/draco/io/ply_reader.cc.o -MF CMakeFiles/draco_io.dir/src/draco/io/ply_reader.cc.o.d -o CMakeFiles/draco_io.dir/src/draco/io/ply_reader.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/ply_reader.cc
[73/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_io.dir/src/draco/io/obj_encoder.cc.o -MF CMakeFiles/draco_io.dir/src/draco/io/obj_encoder.cc.o.d -o CMakeFiles/draco_io.dir/src/draco/io/obj_encoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/obj_encoder.cc
[74/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_mesh_dec.dir/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc.o -MF CMakeFiles/draco_compression_mesh_dec.dir/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc.o.d -o CMakeFiles/draco_compression_mesh_dec.dir/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc
In file included from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc:28:
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:25:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
   25 |     : public std::iterator<std::forward_iterator_tag, VertexIndex> {
      |                   ^~~~~~~~
In file included from /usr/include/c++/13.1.1/bits/stl_algobase.h:65,
                 from /usr/include/c++/13.1.1/bits/hashtable_policy.h:36,
                 from /usr/include/c++/13.1.1/bits/hashtable.h:35,
                 from /usr/include/c++/13.1.1/bits/unordered_map.h:33,
                 from /usr/include/c++/13.1.1/unordered_map:41,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/mesh/mesh_edgebreaker_decoder_impl.cc:15:
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:115:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
  115 |     : public std::iterator<std::forward_iterator_tag, FaceIndex> {
      |                   ^~~~~~~~
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:197:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
  197 |     : public std::iterator<std::forward_iterator_tag, CornerIndex> {
      |                   ^~~~~~~~
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
[75/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_compression_mesh_enc.dir/src/draco/compression/mesh/mesh_edgebreaker_encoder_impl.cc.o -MF CMakeFiles/draco_compression_mesh_enc.dir/src/draco/compression/mesh/mesh_edgebreaker_encoder_impl.cc.o.d -o CMakeFiles/draco_compression_mesh_enc.dir/src/draco/compression/mesh/mesh_edgebreaker_encoder_impl.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/mesh/mesh_edgebreaker_encoder_impl.cc
In file included from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/mesh/mesh_edgebreaker_encoder_impl.cc:28:
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:25:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
   25 |     : public std::iterator<std::forward_iterator_tag, VertexIndex> {
      |                   ^~~~~~~~
In file included from /usr/include/c++/13.1.1/bits/stl_algobase.h:65,
                 from /usr/include/c++/13.1.1/bits/hashtable_policy.h:36,
                 from /usr/include/c++/13.1.1/bits/hashtable.h:35,
                 from /usr/include/c++/13.1.1/bits/unordered_map.h:33,
                 from /usr/include/c++/13.1.1/unordered_map:41,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/mesh/mesh_edgebreaker_encoder_impl.h:18,
                 from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/compression/mesh/mesh_edgebreaker_encoder_impl.cc:15:
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:115:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
  115 |     : public std::iterator<std::forward_iterator_tag, FaceIndex> {
      |                   ^~~~~~~~
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/mesh/corner_table_iterators.h:197:19: warning: ‘template<class _Category, class _Tp, class _Distance, class _Pointer, class _Reference> struct std::iterator’ is deprecated [-Wdeprecated-declarations]
  197 |     : public std::iterator<std::forward_iterator_tag, CornerIndex> {
      |                   ^~~~~~~~
/usr/include/c++/13.1.1/bits/stl_iterator_base_types.h:127:34: note: declared here
  127 |     struct _GLIBCXX17_DEPRECATED iterator
      |                                  ^~~~~~~~
[76/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_io.dir/src/draco/io/ply_decoder.cc.o -MF CMakeFiles/draco_io.dir/src/draco/io/ply_decoder.cc.o.d -o CMakeFiles/draco_io.dir/src/draco/io/ply_decoder.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/ply_decoder.cc
ninja: build stopped: subcommand failed.
```
</details>

### Additional context

```
[44/134] /usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_io.dir/src/draco/io/file_utils.cc.o -MF CMakeFiles/draco_io.dir/src/draco/io/file_utils.cc.o.d -o CMakeFiles/draco_io.dir/src/draco/io/file_utils.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/file_utils.cc
FAILED: CMakeFiles/draco_io.dir/src/draco/io/file_utils.cc.o 
/usr/bin/c++ -DDRACO_CMAKE=1 -DDRACO_FLAGS_SRCDIR=\"/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean\" -DDRACO_FLAGS_TMPDIR=\"/tmp\" -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean -I/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src -I/home/als/Applications/vcpkg/buildtrees/draco/x64-linux-dbg -fPIC -g -fdiagnostics-color=always -MD -MT CMakeFiles/draco_io.dir/src/draco/io/file_utils.cc.o -MF CMakeFiles/draco_io.dir/src/draco/io/file_utils.cc.o.d -o CMakeFiles/draco_io.dir/src/draco/io/file_utils.cc.o -c /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/file_utils.cc
In file included from /home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/file_utils.cc:15:
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/file_utils.h:61:35: error: ‘uint8_t’ was ot declared in this scope
   61 |                       std::vector<uint8_t> *buffer);
      |                                   ^~~~~~~
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/file_utils.h:20:1: note: ‘uint8_t’ is defined in header ‘<cstdint>’; did you forget to ‘#include <cstdint>’?
   19 | #include <vector>
  +++ |+#include <cstdint>
   20 | 
/home/als/Applications/vcpkg/buildtrees/draco/src/1.5.3-f6cecd9b35.clean/src/draco/io/file_utils.h:61:42: error: template argument 1 is invalid
   61 |                       std::vector<uint8_t> *buffer);
      |                                          ^
```

**Comment by FrankXie05** [comment]
Need to confirm if c++11 has been correctly transmitted to all targets.

**Comment by Bosma** [comment]
https://gcc.gnu.org/gcc-13/porting_to.html

"Some C++ Standard Library headers have been changed to no longer include other headers that were being used internally by the library. As such, C++ programs that used standard library components without including the right headers will no longer compile."

I noticed this with the IXWebsockets package too after upgrading to GCC 13, the libraries need to explicitly `include <cstdint>`.

**Comment by cbrl** [comment]
Draco 1.5.6 should fix this error, which vcpkg provides as of #31220.

**Comment by FrankXie05** [comment]
The latest version has been fixed this, please use the latest vcpkg. :)

```
test@test002:~/vcpkg$ ./vcpkg install draco
Computing installation plan...
The following packages will be built and installed:
    draco[core]:x64-linux -> 1.5.6
  * vcpkg-cmake[core]:x64-linux -> 2022-12-22
  * vcpkg-cmake-config[core]:x64-linux -> 2022-02-06#1
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-linux...
Restored 2 package(s) from /home/test/.cache/vcpkg/archives in 129 ms. Use --debug to see more details.
Installing 1/3 vcpkg-cmake:x64-linux...
Elapsed time to handle vcpkg-cmake:x64-linux: 1.12 ms
Installing 2/3 vcpkg-cmake-config:x64-linux...
Elapsed time to handle vcpkg-cmake-config:x64-linux: 801 us
Installing 3/3 draco:x64-linux...
Building draco[core]:x64-linux...
-- Downloading https://github.com/google/draco/archive/1.5.6.tar.gz -> google-draco-1.5.6.tar.gz...
-- Extracting source /home/test/vcpkg/downloads/google-draco-1.5.6.tar.gz
-- Applying patch fix-compile-error-uwp.patch
-- Applying patch fix-uwperror.patch
-- Applying patch fix-pkgconfig.patch
-- Applying patch disable-symlinks.patch
-- Using source at /home/test/vcpkg/buildtrees/draco/src/1.5.6-10e2ea789a.clean
-- Configuring x64-linux
-- Building x64-linux-dbg
-- Building x64-linux-rel
-- Fixing pkgconfig file: /home/test/vcpkg/packages/draco_x64-linux/lib/pkgconfig/draco.pc
-- Fixing pkgconfig file: /home/test/vcpkg/packages/draco_x64-linux/debug/lib/pkgconfig/draco.pc
-- Installing: /home/test/vcpkg/packages/draco_x64-linux/share/draco/copyright
-- Performing post-build validation
Stored binaries in 1 destinations.
Elapsed time to handle draco:x64-linux: 1.4 min
Total install time: 1.5 min
draco provides CMake targets:

    # this is heuristically generated, and may not be correct
    find_package(draco CONFIG REQUIRED)
    target_link_libraries(main PRIVATE draco::draco)

test@test002:~/vcpkg$
```

**Comment by skrede** [comment]
If nothing else I can confirm I tried this with GCC 12.2.1 and I had no problem, and the problem occurred with GCC 13.x. Will update vcpkg and try again on the occurring computer this week.

**Comment by FrankXie05** [comment]
> If nothing else I can confirm I tried this with GCC 12.2.1 and I had no problem, and the problem occurred with GCC 13.x. Will update vcpkg and try again on the occurring computer this week.

I will try it.

**Comment by skrede** [comment]
Updated vcpkg, set baseline to defe7b7fb383da1dd55fdef49a2344235d93001c and installed Draco version 1.5.6 on the occurring computer, it seems to work now.

**Comment by khanghugo** [comment]
I still have this issue. My work around so far is just to make a patch for it with the suggested include. It works for my project.

**Comment by FrankXie05** [comment]
@khanghugo Could you please provide your raw input and error log? And you can try to clear the vcpkg cache and try again.
