### ISSUE TITLE
[vcpkg upgrade] internal error: D:\a\_work\1\s\src\vcpkg\commands.build.cpp(889): Value was null

### ISSUE THREAD

**Issue by slvwagner** [microsoft/vcpkg#31908]
I was told to open a issiue so I do it... 

This is what I did.
```
PowerShell 7.3.4
PS C:\Users\slvwa> vcpkg install qt5:x64-windows
Computing installation plan...
The following packages are already installed:
    qt5[activeqt,core,declarative,essentials,imageformats,multimedia,networkauth,quickcontrols,quickcontrols2,svg,tools,translations,websockets]:x64-windows -> 5.15.9
qt5:x64-windows is already installed
Restored 0 package(s) from C:\Users\slvwa\AppData\Local\vcpkg\archives in 58.3 us. Use --debug to see more details.
Total install time: 186 us
PS C:\Users\slvwa> cd c:\src\vcpkg
PS C:\src\vcpkg> bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2023-04-07/vcpkg.exe -> C:\src\vcpkg\vcpkg.exe... done.
Validating signature... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
PS C:\src\vcpkg> vcpkg install integrate
warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
Computing installation plan...
error: while looking for integrate:x86-windows:
error: while loading integrate:
error: integrate does not exist
PS C:\src\vcpkg> git pull
remote: Enumerating objects: 243, done.
remote: Counting objects: 100% (234/234), done.
remote: Compressing objects: 100% (142/142), done.
remote: Total 243 (delta 112), reused 191 (delta 92), pack-reused 9
Receiving objects: 100% (243/243), 218.31 KiB | 5.60 MiB/s, done.
Resolving deltas: 100% (112/112), completed with 20 local objects.
From https://github.com/Microsoft/vcpkg
   1e334d770..638b1588b  master     -> origin/master
Updating 1e334d770..638b1588b
Fast-forward
 .github/workflows/stale.yml                       |   4 +-
 ports/allegro5/export-targets.patch               |  14 ++-
 ports/allegro5/vcpkg.json                         |   2 +-
 ports/flashlight-text/portfile.cmake              |  33 ++++++
 ports/flashlight-text/vcpkg.json                  |  25 +++++
 ports/imgui/CMakeLists.txt                        |   4 +-
 ports/imgui/imgui-config.cmake.in                 |   4 +
 ports/imgui/vcpkg.json                            |   1 +
 ports/kf5i18n/portfile.cmake                      |  11 ++
 ports/kf5i18n/vcpkg.json                          |   1 +
 ports/libmicrohttpd/portfile.cmake                |  29 ++++--
 ports/libmicrohttpd/vcpkg.json                    |  19 ++--
 ports/nanomsg/portfile.cmake                      |   3 +-
 ports/nanomsg/vcpkg.json                          |   1 +
 ports/nghttp2/portfile.cmake                      |   2 +-
 ports/nghttp2/vcpkg.json                          |   2 +-
 ports/qt5-3d/vcpkg.json                           |   2 +-
 ports/qt5-activeqt/portfile.cmake                 |   8 +-
 ports/qt5-activeqt/vcpkg.json                     |   5 +-
 ports/qt5-androidextras/vcpkg.json                |   2 +-
 ports/qt5-base/cmake/qt_download_submodule.cmake  |  13 +--
 ports/qt5-base/cmake/qt_port_hashes.cmake         |  82 +++++++--------
 ports/qt5-base/vcpkg.json                         |   3 +-
 ports/qt5-charts/vcpkg.json                       |   2 +-
 ports/qt5-connectivity/vcpkg.json                 |   2 +-
 ports/qt5-datavis3d/vcpkg.json                    |   2 +-
 ports/qt5-declarative/vcpkg.json                  |   3 +-
 ports/qt5-doc/vcpkg.json                          |   2 +-
 ports/qt5-gamepad/vcpkg.json                      |   2 +-
 ports/qt5-graphicaleffects/vcpkg.json             |   2 +-
 ports/qt5-imageformats/vcpkg.json                 |   3 +-
 ports/qt5-location/vcpkg.json                     |   3 +-
 ports/qt5-macextras/vcpkg.json                    |   2 +-
 ports/qt5-mqtt/vcpkg.json                         |   2 +-
 ports/qt5-multimedia/vcpkg.json                   |   2 +-
 ports/qt5-networkauth/vcpkg.json                  |   2 +-
 ports/qt5-purchasing/vcpkg.json                   |   2 +-
 ports/qt5-quickcontrols/vcpkg.json                |   2 +-
 ports/qt5-quickcontrols2/vcpkg.json               |   2 +-
 ports/qt5-remoteobjects/vcpkg.json                |   2 +-
 ports/qt5-script/vcpkg.json                       |   2 +-
 ports/qt5-scxml/vcpkg.json                        |   2 +-
 ports/qt5-sensors/vcpkg.json                      |   2 +-
 ports/qt5-serialbus/vcpkg.json                    |   2 +-
 ports/qt5-serialport/vcpkg.json                   |   2 +-
 ports/qt5-speech/vcpkg.json                       |   2 +-
 ports/qt5-svg/vcpkg.json                          |   3 +-
 ports/qt5-tools/vcpkg.json                        |   2 +-
 ports/qt5-translations/vcpkg.json                 |   2 +-
 ports/qt5-virtualkeyboard/vcpkg.json              |   3 +-
 ports/qt5-wayland/vcpkg.json                      |   2 +-
 ports/qt5-webchannel/vcpkg.json                   |   2 +-
 ports/qt5-webengine/vcpkg.json                    |   2 +-
 ports/qt5-webglplugin/vcpkg.json                  |   2 +-
 ports/qt5-websockets/vcpkg.json                   |   2 +-
 ports/qt5-webview/vcpkg.json                      |   2 +-
 ports/qt5-winextras/vcpkg.json                    |   2 +-
 ports/qt5-x11extras/vcpkg.json                    |   2 +-
 ports/qt5-xmlpatterns/vcpkg.json                  |   2 +-
 ports/qt5/vcpkg.json                              |   2 +-
 ports/qtbase/portfile.cmake                       |  16 +++
 ports/qtbase/vcpkg.json                           |   1 +
 ports/redis-plus-plus/portfile.cmake              |   1 +
 ports/redis-plus-plus/vcpkg.json                  |   1 +
 ports/vcpkg-cmake/vcpkg.json                      |   2 +-
 ports/vcpkg-cmake/vcpkg_cmake_configure.cmake     |   4 +
 ports/wt/portfile.cmake                           |   4 +-
 ports/wt/vcpkg.json                               |   1 +
 scripts/bootstrap.ps1                             |   2 +-
 scripts/bootstrap.sh                              |  10 +-
 scripts/ci.baseline.txt                           |   1 -
 scripts/cmake/vcpkg_common_definitions.cmake      |   4 +
 scripts/cmake/vcpkg_configure_cmake.cmake         |   4 +
 scripts/test_ports/cmake-user/portfile.cmake      |   4 +
 scripts/toolchains/xbox.cmake                     |   6 +-
 scripts/vcpkg_get_dep_info.cmake                  |  19 ----
 scripts/vcpkg_get_tags.cmake                      |  33 ------
 triplets/community/x64-xbox-scarlett-static.cmake |   8 +-
 triplets/community/x64-xbox-scarlett.cmake        |   8 +-
 triplets/community/x64-xbox-xboxone-static.cmake  |   8 +-
 triplets/community/x64-xbox-xboxone.cmake         |   8 +-
 versions/a-/allegro5.json                         |   5 +
 versions/baseline.json                            | 120 +++++++++++-----------
 versions/f-/flashlight-text.json                  |  14 +++
 versions/i-/imgui.json                            |   5 +
 versions/k-/kf5i18n.json                          |   5 +
 versions/l-/libmicrohttpd.json                    |   5 +
 versions/n-/nanomsg.json                          |   5 +
 versions/n-/nghttp2.json                          |   5 +
 versions/q-/qt5-3d.json                           |   5 +
 versions/q-/qt5-activeqt.json                     |   5 +
 versions/q-/qt5-androidextras.json                |   5 +
 versions/q-/qt5-base.json                         |   5 +
 versions/q-/qt5-charts.json                       |   5 +
 versions/q-/qt5-connectivity.json                 |   5 +
 versions/q-/qt5-datavis3d.json                    |   5 +
 versions/q-/qt5-declarative.json                  |   5 +
 versions/q-/qt5-doc.json                          |   5 +
 versions/q-/qt5-gamepad.json                      |   5 +
 versions/q-/qt5-graphicaleffects.json             |   5 +
 versions/q-/qt5-imageformats.json                 |   5 +
 versions/q-/qt5-location.json                     |   5 +
 versions/q-/qt5-macextras.json                    |   5 +
 versions/q-/qt5-mqtt.json                         |   5 +
 versions/q-/qt5-multimedia.json                   |   5 +
 versions/q-/qt5-networkauth.json                  |   5 +
 versions/q-/qt5-purchasing.json                   |   5 +
 versions/q-/qt5-quickcontrols.json                |   5 +
 versions/q-/qt5-quickcontrols2.json               |   5 +
 versions/q-/qt5-remoteobjects.json                |   5 +
 versions/q-/qt5-script.json                       |   5 +
 versions/q-/qt5-scxml.json                        |   5 +
 versions/q-/qt5-sensors.json                      |   5 +
 versions/q-/qt5-serialbus.json                    |   5 +
 versions/q-/qt5-serialport.json                   |   5 +
 versions/q-/qt5-speech.json                       |   5 +
 versions/q-/qt5-svg.json                          |   5 +
 versions/q-/qt5-tools.json                        |   5 +
 versions/q-/qt5-translations.json                 |   5 +
 versions/q-/qt5-virtualkeyboard.json              |   5 +
 versions/q-/qt5-wayland.json                      |   5 +
 versions/q-/qt5-webchannel.json                   |   5 +
 versions/q-/qt5-webengine.json                    |   5 +
 versions/q-/qt5-webglplugin.json                  |   5 +
 versions/q-/qt5-websockets.json                   |   5 +
 versions/q-/qt5-webview.json                      |   5 +
 versions/q-/qt5-winextras.json                    |   5 +
 versions/q-/qt5-x11extras.json                    |   5 +
 versions/q-/qt5-xmlpatterns.json                  |   5 +
 versions/q-/qt5.json                              |   5 +
 versions/q-/qtbase.json                           |   5 +
 versions/r-/redis-plus-plus.json                  |   5 +
 versions/v-/vcpkg-cmake.json                      |   5 +
 versions/w-/wt.json                               |   5 +
 134 files changed, 600 insertions(+), 283 deletions(-)
 create mode 100644 ports/flashlight-text/portfile.cmake
 create mode 100644 ports/flashlight-text/vcpkg.json
 delete mode 100644 scripts/vcpkg_get_dep_info.cmake
 delete mode 100644 scripts/vcpkg_get_tags.cmake
 create mode 100644 versions/f-/flashlight-text.json
PS C:\src\vcpkg> bootstrap-vcpkg.bat
Downloading https://github.com/microsoft/vcpkg-tool/releases/download/2023-06-07/vcpkg.exe -> C:\src\vcpkg\vcpkg.exe... done.
Validating signature... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md
PS C:\src\vcpkg> vcpkg install integrate
warning: Starting with the September 2023 release, the default triplet for vcpkg libraries will change from x86-windows to the detected host triplet (x64-windows). To resolve this message, add --triplet x86-windows to keep the same behavior.
Computing installation plan...
error: while looking for integrate:x86-windows:
error: while loading integrate:
error: integrate does not exist
PS C:\src\vcpkg> vcpkg upgrade
The following packages will be rebuilt:
  * armadillo:x64-windows -> 12.0.1
  * blas:x64-windows -> 2023-03-25
  * boost-algorithm:x64-windows -> 1.82.0#2
  * boost-container:x64-windows -> 1.82.0#2
  * boost-date-time:x64-windows -> 1.82.0#2
  * boost-exception:x64-windows -> 1.82.0#2
  * boost-lexical-cast:x64-windows -> 1.82.0#2
  * boost-math:x64-windows -> 1.82.0#2
  * boost-modular-build-helper:x64-windows -> 1.82.0#2
  * boost-multiprecision:x64-windows -> 1.82.0#2
  * boost-random:x64-windows -> 1.82.0#2
  * boost-range:x64-windows -> 1.82.0#2
  * boost-regex:x64-windows -> 1.82.0#2
  * boost-system:x64-windows -> 1.82.0#2
  * brotli:x64-windows -> 1.0.9#5
  * bzip2[core,tool]:x64-windows -> 1.0.8#4
  * bzip2[core,tool]:x86-windows -> 1.0.8#4
  * cimg:x64-windows -> 2.9.9
  * double-conversion:x64-windows -> 3.2.1#1
  * eigen3:x64-windows -> 3.4.0#2
  * expat:x64-windows -> 2.5.0#3
  * expat:x86-windows -> 2.5.0#3
  * ffmpeg[avcodec,avdevice,avfilter,avformat,core,swresample,swscale]:x64-windows -> 5.1.2#6
  * freeglut:x64-windows -> 3.4.0
  * freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.12.1#3
  * glad[core,loader]:x64-windows -> 0.1.36
  * glew:x64-windows -> 2.2.0#3
  * glew:x86-windows -> 2.2.0#3
  * glfw3:x64-windows -> 3.3.8#2
  * harfbuzz:x64-windows -> 7.3.0
  * imgui:x64-windows -> 1.89.6#1
  * imgui:x86-windows -> 1.89.6#1
  * implot:x64-windows -> 0.14#1
  * lapack:x64-windows -> 2022-02-22#2
  * lapack-reference[blas-select,core,noblas]:x64-windows -> 3.11.0#1
  * libdshowcapture:x64-windows -> 0.6.0#3
  * libffi:x64-windows -> 3.4.4#1
  * libffi:x86-windows -> 3.4.4#1
  * libjpeg-turbo:x86-windows -> 2.1.5.1#1
  * libjpeg-turbo:x64-windows -> 2.1.5.1#1
  * liblzma:x64-windows -> 5.4.1#1
  * liblzma:x86-windows -> 5.4.1#1
  * libpng:x64-windows -> 1.6.39#1
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows -> 1.3.0
  * matplotplusplus:x64-windows -> 2021-04-11#6
  * nanosvg:x64-windows -> 2022-12-04
  * nativefiledialog:x64-windows -> 2022-01-20
  * nlohmann-json:x64-windows -> 3.11.2
  * numcpp:x64-windows -> 2.10.1
  * openblas:x64-windows -> 0.3.23
  * opencv[core,default-features]:x64-windows -> 4.7.0#1
  * opencv2[core,default-features,eigen,jpeg,png,tiff]:x64-windows -> 2.4.13.7#18
  * opencv3[core,default-features,dnn,flann,jpeg,png,quirc,tiff,webp]:x64-windows -> 3.4.18#10
  * opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.7.0#6
  * openssl:x64-windows -> 3.1.1
  * openssl:x86-windows -> 3.1.1
  * pcre2[core,jit,platform-default-features]:x64-windows -> 10.40#2
  * pcre2[core,jit,platform-default-features]:x86-windows -> 10.40#2
  * protobuf:x64-windows -> 3.21.12
  * protobuf:x86-windows -> 3.21.12
  * python3:x86-windows -> 3.10.7#6
  * python3:x64-windows -> 3.10.7#6
  * qt5[activeqt,core,declarative,essentials,imageformats,multimedia,networkauth,quickcontrols,quickcontrols2,svg,tools,translations,websockets]:x64-windows -> 5.15.10
  * qt5-activeqt:x64-windows -> 5.15.10
  * qt5-base:x64-windows -> 5.15.10
  * qt5-declarative[core,d3d12,platform-default-features]:x64-windows -> 5.15.10
  * qt5-graphicaleffects:x64-windows -> 5.15.10
  * qt5-imageformats[core,tiff,webp]:x64-windows -> 5.15.10
  * qt5-multimedia:x64-windows -> 5.15.10
  * qt5-networkauth:x64-windows -> 5.15.10
  * qt5-quickcontrols:x64-windows -> 5.15.10
  * qt5-quickcontrols2:x64-windows -> 5.15.10
  * qt5-svg:x64-windows -> 5.15.10
  * qt5-tools:x64-windows -> 5.15.10
  * qt5-translations:x64-windows -> 5.15.10
  * qt5-websockets:x64-windows -> 5.15.10
  * quirc:x64-windows -> 1.1#3
  * quirc:x86-windows -> 1.1#3
  * sciplot:x64-windows -> 0.3.1#1
  * sciplot:x86-windows -> 0.3.1#1
  * soil:x64-windows -> 2021-04-22#2
  * sqlite3:x86-windows -> 3.40.1#3
  * sqlite3:x64-windows -> 3.40.1#3
  * symengine[core,integer-class-boostmp]:x64-windows -> 0.10.1
  * tiff[core,jpeg,lzma,zip]:x64-windows -> 4.5.0#3
  * tiff[core,jpeg,lzma,zip]:x86-windows -> 4.5.0#3
  * vcpkg-cmake:x64-windows -> 2023-05-04
  * vcpkg-cmake-get-vars:x64-windows -> 2023-03-02
  * vcpkg-tool-ninja:x64-windows -> 2022-03-31#1
  * wxwidgets[core,debug-support,sound]:x64-windows -> 3.2.2.1#2
  * xtensor:x64-windows -> 0.24.6
  * xtensor-io:x64-windows -> 0.13.0#1
  * xtl:x64-windows -> 0.7.5
  * zlib:x86-windows -> 1.2.13
  * zlib:x64-windows -> 1.2.13
  * zstd:x64-windows -> 1.5.5
Additional packages (*) will be modified to complete this operation.
If you are sure you want to rebuild the above packages, run this command with the --no-dry-run option.
PS C:\src\vcpkg> vcpkg upgrade --no-dry-run
The following packages will be rebuilt:
  * armadillo:x64-windows -> 12.0.1
  * blas:x64-windows -> 2023-03-25
  * boost-algorithm:x64-windows -> 1.82.0#2
  * boost-container:x64-windows -> 1.82.0#2
  * boost-date-time:x64-windows -> 1.82.0#2
  * boost-exception:x64-windows -> 1.82.0#2
  * boost-lexical-cast:x64-windows -> 1.82.0#2
  * boost-math:x64-windows -> 1.82.0#2
  * boost-modular-build-helper:x64-windows -> 1.82.0#2
  * boost-multiprecision:x64-windows -> 1.82.0#2
  * boost-random:x64-windows -> 1.82.0#2
  * boost-range:x64-windows -> 1.82.0#2
  * boost-regex:x64-windows -> 1.82.0#2
  * boost-system:x64-windows -> 1.82.0#2
  * brotli:x64-windows -> 1.0.9#5
  * bzip2[core,tool]:x64-windows -> 1.0.8#4
  * bzip2[core,tool]:x86-windows -> 1.0.8#4
  * cimg:x64-windows -> 2.9.9
  * double-conversion:x64-windows -> 3.2.1#1
  * eigen3:x64-windows -> 3.4.0#2
  * expat:x64-windows -> 2.5.0#3
  * expat:x86-windows -> 2.5.0#3
  * ffmpeg[avcodec,avdevice,avfilter,avformat,core,swresample,swscale]:x64-windows -> 5.1.2#6
  * freeglut:x64-windows -> 3.4.0
  * freetype[brotli,bzip2,core,png,zlib]:x64-windows -> 2.12.1#3
  * glad[core,loader]:x64-windows -> 0.1.36
  * glew:x64-windows -> 2.2.0#3
  * glew:x86-windows -> 2.2.0#3
  * glfw3:x64-windows -> 3.3.8#2
  * harfbuzz:x64-windows -> 7.3.0
  * imgui:x64-windows -> 1.89.6#1
  * imgui:x86-windows -> 1.89.6#1
  * implot:x64-windows -> 0.14#1
  * lapack:x64-windows -> 2022-02-22#2
  * lapack-reference[blas-select,core,noblas]:x64-windows -> 3.11.0#1
  * libdshowcapture:x64-windows -> 0.6.0#3
  * libffi:x64-windows -> 3.4.4#1
  * libffi:x86-windows -> 3.4.4#1
  * libjpeg-turbo:x86-windows -> 2.1.5.1#1
  * libjpeg-turbo:x64-windows -> 2.1.5.1#1
  * liblzma:x64-windows -> 5.4.1#1
  * liblzma:x86-windows -> 5.4.1#1
  * libpng:x64-windows -> 1.6.39#1
  * libwebp[core,libwebpmux,nearlossless,simd,unicode]:x64-windows -> 1.3.0
  * matplotplusplus:x64-windows -> 2021-04-11#6
  * nanosvg:x64-windows -> 2022-12-04
  * nativefiledialog:x64-windows -> 2022-01-20
  * nlohmann-json:x64-windows -> 3.11.2
  * numcpp:x64-windows -> 2.10.1
  * openblas:x64-windows -> 0.3.23
  * opencv[core,default-features]:x64-windows -> 4.7.0#1
  * opencv2[core,default-features,eigen,jpeg,png,tiff]:x64-windows -> 2.4.13.7#18
  * opencv3[core,default-features,dnn,flann,jpeg,png,quirc,tiff,webp]:x64-windows -> 3.4.18#10
  * opencv4[core,default-features,dnn,jpeg,png,quirc,tiff,webp]:x64-windows -> 4.7.0#6
  * openssl:x64-windows -> 3.1.1
  * openssl:x86-windows -> 3.1.1
  * pcre2[core,jit,platform-default-features]:x64-windows -> 10.40#2
  * pcre2[core,jit,platform-default-features]:x86-windows -> 10.40#2
  * protobuf:x64-windows -> 3.21.12
  * protobuf:x86-windows -> 3.21.12
  * python3:x86-windows -> 3.10.7#6
  * python3:x64-windows -> 3.10.7#6
  * qt5[activeqt,core,declarative,essentials,imageformats,multimedia,networkauth,quickcontrols,quickcontrols2,svg,tools,translations,websockets]:x64-windows -> 5.15.10
  * qt5-activeqt:x64-windows -> 5.15.10
  * qt5-base:x64-windows -> 5.15.10
  * qt5-declarative[core,d3d12,platform-default-features]:x64-windows -> 5.15.10
  * qt5-graphicaleffects:x64-windows -> 5.15.10
  * qt5-imageformats[core,tiff,webp]:x64-windows -> 5.15.10
  * qt5-multimedia:x64-windows -> 5.15.10
  * qt5-networkauth:x64-windows -> 5.15.10
  * qt5-quickcontrols:x64-windows -> 5.15.10
  * qt5-quickcontrols2:x64-windows -> 5.15.10
  * qt5-svg:x64-windows -> 5.15.10
  * qt5-tools:x64-windows -> 5.15.10
  * qt5-translations:x64-windows -> 5.15.10
  * qt5-websockets:x64-windows -> 5.15.10
  * quirc:x64-windows -> 1.1#3
  * quirc:x86-windows -> 1.1#3
  * sciplot:x64-windows -> 0.3.1#1
  * sciplot:x86-windows -> 0.3.1#1
  * soil:x64-windows -> 2021-04-22#2
  * sqlite3:x86-windows -> 3.40.1#3
  * sqlite3:x64-windows -> 3.40.1#3
  * symengine[core,integer-class-boostmp]:x64-windows -> 0.10.1
  * tiff[core,jpeg,lzma,zip]:x64-windows -> 4.5.0#3
  * tiff[core,jpeg,lzma,zip]:x86-windows -> 4.5.0#3
  * vcpkg-cmake:x64-windows -> 2023-05-04
  * vcpkg-cmake-get-vars:x64-windows -> 2023-03-02
  * vcpkg-tool-ninja:x64-windows -> 2022-03-31#1
  * wxwidgets[core,debug-support,sound]:x64-windows -> 3.2.2.1#2
  * xtensor:x64-windows -> 0.24.6
  * xtensor-io:x64-windows -> 0.13.0#1
  * xtl:x64-windows -> 0.7.5
  * zlib:x86-windows -> 1.2.13
  * zlib:x64-windows -> 1.2.13
  * zstd:x64-windows -> 1.5.5
Additional packages (*) will be modified to complete this operation.
Detecting compiler hash for triplet x64-windows...
Detecting compiler hash for triplet x86-windows...
Restored 0 package(s) from C:\Users\slvwa\AppData\Local\vcpkg\archives in 1.39 ms. Use --debug to see more details.
Removing 1/192 armadillo:x64-windows
Elapsed time to handle armadillo:x64-windows: 65.1 ms
Removing 2/192 lapack:x64-windows
Elapsed time to handle lapack:x64-windows: 1.86 ms
Removing 3/192 lapack-reference:x64-windows
Elapsed time to handle lapack-reference:x64-windows: 6.33 ms
Removing 4/192 blas:x64-windows
Elapsed time to handle blas:x64-windows: 1.91 ms
Removing 5/192 numcpp:x64-windows
Elapsed time to handle numcpp:x64-windows: 55.6 ms
Removing 6/192 boost-date-time:x64-windows
Elapsed time to handle boost-date-time:x64-windows: 15.4 ms
Removing 7/192 boost-algorithm:x64-windows
Elapsed time to handle boost-algorithm:x64-windows: 12.2 ms
Removing 8/192 symengine:x64-windows
Elapsed time to handle symengine:x64-windows: 22.4 ms
Removing 9/192 boost-multiprecision:x64-windows
Elapsed time to handle boost-multiprecision:x64-windows: 11.9 ms
Removing 10/192 boost-math:x64-windows
Elapsed time to handle boost-math:x64-windows: 60.7 ms
Removing 11/192 boost-lexical-cast:x64-windows
Elapsed time to handle boost-lexical-cast:x64-windows: 4.04 ms
Removing 12/192 boost-container:x64-windows
Elapsed time to handle boost-container:x64-windows: 18.7 ms
Removing 13/192 boost-exception:x64-windows
Elapsed time to handle boost-exception:x64-windows: 5.53 ms
Removing 14/192 boost-random:x64-windows
Elapsed time to handle boost-random:x64-windows: 12.9 ms
Removing 15/192 boost-system:x64-windows
Elapsed time to handle boost-system:x64-windows: 7.69 ms
Removing 16/192 boost-range:x64-windows
Elapsed time to handle boost-range:x64-windows: 19.3 ms
Removing 17/192 boost-regex:x64-windows
Elapsed time to handle boost-regex:x64-windows: 15.3 ms
Removing 18/192 boost-modular-build-helper:x64-windows
Elapsed time to handle boost-modular-build-helper:x64-windows: 2.47 ms
Removing 19/192 qt5:x64-windows
Elapsed time to handle qt5:x64-windows: 12.8 ms
Removing 20/192 qt5-translations:x64-windows
Elapsed time to handle qt5-translations:x64-windows: 61.6 ms
Removing 21/192 qt5-tools:x64-windows
Elapsed time to handle qt5-tools:x64-windows: 153 ms
Removing 22/192 qt5-activeqt:x64-windows
Elapsed time to handle qt5-activeqt:x64-windows: 15.1 ms
Removing 23/192 qt5-quickcontrols2:x64-windows
Elapsed time to handle qt5-quickcontrols2:x64-windows: 98.9 ms
Removing 24/192 qt5-quickcontrols:x64-windows
Elapsed time to handle qt5-quickcontrols:x64-windows: 79.9 ms
Removing 25/192 qt5-graphicaleffects:x64-windows
Elapsed time to handle qt5-graphicaleffects:x64-windows: 10.1 ms
Removing 26/192 qt5-multimedia:x64-windows
Elapsed time to handle qt5-multimedia:x64-windows: 34.1 ms
Removing 27/192 qt5-websockets:x64-windows
Elapsed time to handle qt5-websockets:x64-windows: 8.12 ms
Removing 28/192 qt5-declarative:x64-windows
Elapsed time to handle qt5-declarative:x64-windows: 127 ms
Removing 29/192 qt5-imageformats:x64-windows
Elapsed time to handle qt5-imageformats:x64-windows: 5.79 ms
Removing 30/192 qt5-networkauth:x64-windows
Elapsed time to handle qt5-networkauth:x64-windows: 6.8 ms
Removing 31/192 qt5-svg:x64-windows
Elapsed time to handle qt5-svg:x64-windows: 7.51 ms
Removing 32/192 qt5-base:x64-windows
Elapsed time to handle qt5-base:x64-windows: 472 ms
Removing 33/192 harfbuzz:x64-windows
Elapsed time to handle harfbuzz:x64-windows: 6.62 ms
Removing 34/192 freetype:x64-windows
Elapsed time to handle freetype:x64-windows: 11.9 ms
Removing 35/192 brotli:x64-windows
Elapsed time to handle brotli:x64-windows: 5.8 ms
Removing 36/192 wxwidgets:x64-windows
Elapsed time to handle wxwidgets:x64-windows: 170 ms
Removing 37/192 pcre2:x64-windows
Elapsed time to handle pcre2:x64-windows: 11.1 ms
Removing 38/192 python3:x86-windows
Elapsed time to handle python3:x86-windows: 278 ms
Removing 39/192 python3:x64-windows
Elapsed time to handle python3:x64-windows: 272 ms
Removing 40/192 bzip2:x64-windows
Elapsed time to handle bzip2:x64-windows: 4.44 ms
Removing 41/192 pcre2:x86-windows
Elapsed time to handle pcre2:x86-windows: 7.88 ms
Removing 42/192 bzip2:x86-windows
Elapsed time to handle bzip2:x86-windows: 9.53 ms
Removing 43/192 matplotplusplus:x64-windows
Elapsed time to handle matplotplusplus:x64-windows: 9.39 ms
Removing 44/192 cimg:x64-windows
Elapsed time to handle cimg:x64-windows: 2.32 ms
Removing 45/192 double-conversion:x64-windows
Elapsed time to handle double-conversion:x64-windows: 4.3 ms
Removing 46/192 opencv2:x64-windows
Elapsed time to handle opencv2:x64-windows: 38.7 ms
Removing 47/192 eigen3:x64-windows
Elapsed time to handle eigen3:x64-windows: 176 ms
Removing 48/192 expat:x64-windows
Elapsed time to handle expat:x64-windows: 3.84 ms
Removing 49/192 expat:x86-windows
Elapsed time to handle expat:x86-windows: 3.85 ms
Removing 50/192 ffmpeg:x64-windows
Elapsed time to handle ffmpeg:x64-windows: 31.7 ms
Removing 51/192 freeglut:x64-windows
Elapsed time to handle freeglut:x64-windows: 4.62 ms
Removing 52/192 glad:x64-windows
Elapsed time to handle glad:x64-windows: 3.87 ms
Removing 53/192 glew:x64-windows
Elapsed time to handle glew:x64-windows: 4.26 ms
Removing 54/192 glew:x86-windows
Elapsed time to handle glew:x86-windows: 4.4 ms
Removing 55/192 glfw3:x64-windows
Elapsed time to handle glfw3:x64-windows: 3.96 ms
Removing 56/192 implot:x64-windows
Elapsed time to handle implot:x64-windows: 2.84 ms
Removing 57/192 imgui:x64-windows
Elapsed time to handle imgui:x64-windows: 3.31 ms
Removing 58/192 imgui:x86-windows
Elapsed time to handle imgui:x86-windows: 3.35 ms
Removing 59/192 libdshowcapture:x64-windows
Elapsed time to handle libdshowcapture:x64-windows: 3.1 ms
Removing 60/192 libffi:x64-windows
Elapsed time to handle libffi:x64-windows: 3.75 ms
Removing 61/192 libffi:x86-windows
Elapsed time to handle libffi:x86-windows: 3.8 ms
Removing 62/192 opencv3:x64-windows
Elapsed time to handle opencv3:x64-windows: 49.4 ms
Removing 63/192 opencv:x64-windows
Elapsed time to handle opencv:x64-windows: 3.58 ms
Removing 64/192 opencv4:x64-windows
Elapsed time to handle opencv4:x64-windows: 44.6 ms
Removing 65/192 tiff:x64-windows
Elapsed time to handle tiff:x64-windows: 6.42 ms
Removing 66/192 libjpeg-turbo:x64-windows
Elapsed time to handle libjpeg-turbo:x64-windows: 4.88 ms
Removing 67/192 tiff:x86-windows
Elapsed time to handle tiff:x86-windows: 6.51 ms
Removing 68/192 libjpeg-turbo:x86-windows
Elapsed time to handle libjpeg-turbo:x86-windows: 5.19 ms
Removing 69/192 liblzma:x64-windows
Elapsed time to handle liblzma:x64-windows: 5.38 ms
Removing 70/192 liblzma:x86-windows
Elapsed time to handle liblzma:x86-windows: 5.63 ms
Removing 71/192 libpng:x64-windows
Elapsed time to handle libpng:x64-windows: 4.95 ms
Removing 72/192 libwebp:x64-windows
Elapsed time to handle libwebp:x64-windows: 11.2 ms
Removing 73/192 nanosvg:x64-windows
Elapsed time to handle nanosvg:x64-windows: 3.38 ms
Removing 74/192 nativefiledialog:x64-windows
Elapsed time to handle nativefiledialog:x64-windows: 2.98 ms
Removing 75/192 xtensor-io:x64-windows
Elapsed time to handle xtensor-io:x64-windows: 4.78 ms
Removing 76/192 xtensor:x64-windows
Elapsed time to handle xtensor:x64-windows: 11.3 ms
Removing 77/192 xtl:x64-windows
Elapsed time to handle xtl:x64-windows: 6.3 ms
Removing 78/192 nlohmann-json:x64-windows
Elapsed time to handle nlohmann-json:x64-windows: 8.81 ms
Removing 79/192 openblas:x64-windows
Elapsed time to handle openblas:x64-windows: 4.36 ms
Removing 80/192 openssl:x64-windows
Elapsed time to handle openssl:x64-windows: 16.5 ms
Removing 81/192 openssl:x86-windows
Elapsed time to handle openssl:x86-windows: 18.9 ms
Removing 82/192 protobuf:x86-windows
Elapsed time to handle protobuf:x86-windows: 21.6 ms
Removing 83/192 protobuf:x64-windows
Elapsed time to handle protobuf:x64-windows: 21 ms
Removing 84/192 quirc:x64-windows
Elapsed time to handle quirc:x64-windows: 3.37 ms
Removing 85/192 quirc:x86-windows
Elapsed time to handle quirc:x86-windows: 2.75 ms
Removing 86/192 sciplot:x64-windows
Elapsed time to handle sciplot:x64-windows: 6.42 ms
Removing 87/192 sciplot:x86-windows
Elapsed time to handle sciplot:x86-windows: 6.63 ms
Removing 88/192 soil:x64-windows
Elapsed time to handle soil:x64-windows: 2.94 ms
Removing 89/192 sqlite3:x64-windows
Elapsed time to handle sqlite3:x64-windows: 4.15 ms
Removing 90/192 sqlite3:x86-windows
Elapsed time to handle sqlite3:x86-windows: 4.18 ms
Removing 91/192 vcpkg-cmake-get-vars:x64-windows
Elapsed time to handle vcpkg-cmake-get-vars:x64-windows: 2.32 ms
Removing 92/192 vcpkg-tool-ninja:x64-windows
Elapsed time to handle vcpkg-tool-ninja:x64-windows: 2.26 ms
Removing 93/192 zlib:x64-windows
Elapsed time to handle zlib:x64-windows: 3.12 ms
Removing 94/192 zlib:x86-windows
Elapsed time to handle zlib:x86-windows: 3.36 ms
Removing 95/192 zstd:x64-windows
Elapsed time to handle zstd:x64-windows: 4.34 ms
Removing 96/192 vcpkg-cmake:x64-windows
Elapsed time to handle vcpkg-cmake:x64-windows: 2.12 ms
Installing 97/192 vcpkg-cmake:x64-windows...
Building vcpkg-cmake:x64-windows...
-- Installing: C:/src/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_configure.cmake
-- Installing: C:/src/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_build.cmake
-- Installing: C:/src/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg_cmake_install.cmake
-- Installing: C:/src/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/vcpkg-port-config.cmake
-- Installing: C:/src/vcpkg/packages/vcpkg-cmake_x64-windows/share/vcpkg-cmake/copyright
-- Performing post-build validation
internal error: D:\a\_work\1\s\src\vcpkg\commands.build.cpp(889): Value was null
Please open an issue at https://github.com/microsoft/vcpkg/issues/new?template=other-type-of-bug-report.md&labels=category:vcpkg-bug with detailed steps to reproduce the problem.
PS C:\src\vcpkg>
```

**Comment by SKNo** [comment]
Hi
I wont post the details but I got exactly the same internal error.
(after executing bootstrap.bat & git pull)

**Comment by Cheney-W** [comment]
@BillyONeal 
The `.\vcpkg.exe upgrade --no-dry-run` failed with below error in my side when I used the vcpkg.exe version higher than `2023-04-07`.
```
internal error: D:\a\_work\1\s\src\vcpkg\binarycaching.cpp(287): Value was null
```

@slvwagner  @SKNo
As a workaround, please modify the line 48 of `\vcpkg\scripts\bootstrap.ps1` file to `2023-04-07` and run `.\bootstrap-vcpkg.bat` again.

**Comment by izirku** [comment]
same issue, is there a way to kick off the post install tasks after downgrading to 2023-04-07 (if it's even needed)? or do we need to re-install all the packages manually?

**Comment by slvwagner** [comment]
I reinstalled everything and now it’s working

**Comment by GeorgePimpleton** [comment]
The update of vcpkg to 2023-06-15 still has the "value is null" error that aborts an update of installed libraries/packages.  After the installed libraries/packages are deleted before the attempt to install the updated libraries/packages is done.  That requires doing an install instead of updating.

The bug is still not squashed.  Reverting back to vcpkg 2023-06-07.

**Comment by aizuon** [comment]
Experiencing the same issue with 2023-06-15 version

**Comment by MSP-Greg** [comment]
Same issue, locally and on GitHub Actions.

**Comment by BillyONeal** [comment]
I've repro'd the problem and am investigating a fix.

**Comment by MSP-Greg** [comment]
@BillyONeal

Thank you.  JFYI, I built vcpkg.exe from your PR in vcpkg-tool, and OpenSSL built with it.

**Comment by autoantwort** [comment]
@dan-shaw you closed this issue accidentally

**Comment by autoantwort** [comment]
Is fixed after https://github.com/microsoft/vcpkg/pull/32180 is merged.

**Comment by GeorgePimpleton** [comment]
The current bootstrap.ps1 script has at line 48 $versionDate = '2023-06-15' so running bootstrap-vcpkg.bat retrieves an outdated vcpkg.  Doing an install packages upgrade with 2023-06-15 will still fail with error "value is null."

**Comment by autoantwort** [comment]
As I said you have to wait for https://github.com/microsoft/vcpkg/pull/32180. You can test if the error still happens with that PR

**Comment by BillyONeal** [comment]
Fixed in https://github.com/microsoft/vcpkg/pull/32180
