### ISSUE TITLE
Building package glew:x64-windows-static failed with: BUILD_FAILED

### ISSUE THREAD

**Issue by chradleengineering** [Microsoft/vcpkg#3390]
typed vcpkg install pcl:x64-windows-static
used cmake 3.10.2
-- Extracting source C:/vcpkg/downloads/glew-2.1.0.tgz
-- Extracting done
-- Configuring x64-windows-static
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:56 (message):
    Command failed: ninja;-v
    Working Directory: C:/vcpkg/buildtrees/glew/x64-windows-static-rel/vcpkg-parallel-configure
    See logs for more information:
      C:\vcpkg\buildtrees\glew\config-x64-windows-static-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:237 (vcpkg_execute_required_process)
  ports/glew/portfile.cmake:14 (vcpkg_configure_cmake)
  scripts/ports.cmake:72 (include)

Error: Building package glew:x64-windows-static failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: glew:x64-windows-static
  Vcpkg version: 0.0.110-2018-04-28-a9d989ec056246ea320a56ca7d02b161a6fee387

Additionally, attach any relevant sections from the log files above.

C:\vcpkg>vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

greetings chris

**Comment by olilarkin** [comment]
got the same problem

**Comment by kevz93** [comment]
Any luck guys ? Did anyone try a build from source ?

**Comment by kevz93** [comment]
C:\vcpkg\buildtrees\glew\config-x64-windows-static-out.log
Guys does log say it cannot find VS2015 or 17 ?

**Comment by Cheney-W** [comment]
@chradleengineering , I can install glew, glew:x64-windows and glew:x64-windows-static successfully with latest VCPKG: 2018.11.23-nohash and VS2017 15.9.7, I think this issue has been fixed, so close this issue.

**Comment by ssylvain** [comment]
I am using the same version of vcpkg and vs2017 and it doesn't work for me. @Cheney-W , did you install anything else or change parameters other than a clean install?

**Comment by Cheney-W** [comment]
@ssylvain , I am using the new vcpkg and only installed glew:x64-windows and glew:x64-windows-static. Could you provide us your error log?

**Comment by fps92** [comment]
Still have the same problem
Windows 7 Professional (6.1.7601 Service Pack 1 Build 7601)
Visual Studio 2017 15.9.13
