### ISSUE TITLE
[x264] build failure

### ISSUE THREAD

**Issue by jakubtyrcha** [microsoft/vcpkg#34676]
Package: x264[asm,core,default-features,gpl]:x64-windows -> 0.164.3107

**Host Environment**

- Host: x64-windows
- Compiler: MSVC 19.36.32538.0
-    vcpkg-tool version: 2023-10-18-27de5b69dac4b6fe8259d283cd4011e6d20a84ce
    vcpkg-scripts version: 830f86fb3 2023-10-20 (3 days ago)

**To Reproduce**

`vcpkg install x264`
**Failure logs**

```
-- Using cached mirror-x264-eaa68fad9e5d201d42fde51665f2d137ae96baf0.tar.gz.
-- Cleaning sources at C:/Veed/vcpkg/buildtrees/x264/src/37ae96baf0-6a8b74b3ff.clean. Use --editable to skip cleaning for the packages you specify.
-- Extracting source C:/Veed/vcpkg/downloads/mirror-x264-eaa68fad9e5d201d42fde51665f2d137ae96baf0.tar.gz
-- Applying patch uwp-cflags.patch
-- Applying patch parallel-install.patch
-- Applying patch allow-clang-cl.patch
-- Applying patch configure-as.patch
-- Using source at C:/Veed/vcpkg/buildtrees/x264/src/37ae96baf0-6a8b74b3ff.clean
-- Found external ninja('1.11.0').
-- Getting CMake variables for x64-windows
-- Getting CMake variables for x64-windows
-- Using cached msys2-autoconf-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-automake-wrapper-20221207-1-any.pkg.tar.zst.
-- Using cached msys2-binutils-2.40-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libtool-2.4.7-3-x86_64.pkg.tar.zst.
-- Using cached msys2-make-4.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-pkgconf-1.9.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-which-2.21-4-x86_64.pkg.tar.zst.
-- Using cached msys2-bash-5.2.015-1-x86_64.pkg.tar.zst.
-- Using cached msys2-coreutils-8.32-5-x86_64.pkg.tar.zst.
-- Using cached msys2-file-5.44-5-x86_64.pkg.tar.zst.
-- Using cached msys2-gawk-5.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-grep-1~3.0-6-x86_64.pkg.tar.zst.
-- Using cached msys2-gzip-1.12-2-x86_64.pkg.tar.zst.
-- Using cached msys2-diffutils-3.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-sed-4.9-1-x86_64.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using cached msys2-autoconf2.71-2.71-1-any.pkg.tar.zst.
-- Using cached msys2-automake1.16-1.16.5-1-any.pkg.tar.zst.
-- Using cached msys2-libiconv-1.17-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libintl-0.21-2-x86_64.pkg.tar.zst.
-- Using cached msys2-zlib-1.2.13-1-x86_64.pkg.tar.zst.
-- Using cached msys2-tar-1.34-3-x86_64.pkg.tar.zst.
-- Using cached msys2-findutils-4.9.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-gmp-6.2.1-2-x86_64.pkg.tar.zst.
-- Using cached msys2-gcc-libs-11.3.0-3-x86_64.pkg.tar.zst.
-- Using cached msys2-libbz2-1.0.8-4-x86_64.pkg.tar.zst.
-- Using cached msys2-liblzma-5.4.1-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libzstd-1.5.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libreadline-8.2.001-3-x86_64.pkg.tar.zst.
-- Using cached msys2-mpfr-4.2.0-2-x86_64.pkg.tar.zst.
-- Using cached msys2-libpcre-8.45-3-x86_64.pkg.tar.zst.
-- Using cached msys2-m4-1.4.19-2-x86_64.pkg.tar.zst.
-- Using cached msys2-perl-5.36.0-1-x86_64.pkg.tar.zst.
-- Using cached msys2-ncurses-6.4-1-x86_64.pkg.tar.zst.
-- Using cached msys2-libcrypt-2.1-4-x86_64.pkg.tar.zst.
-- Using msys root at C:/Veed/vcpkg/downloads/tools/msys2/d7266db249278763
CMake Warning at scripts/cmake/vcpkg_configure_make.cmake:269 (message):
  Unable to find system dir in the PATH variable! Appending required msys
  paths!
Call Stack (most recent call first):
  ports/x264/portfile.cmake:96 (vcpkg_configure_make)
  scripts/ports.cmake:168 (include)


-- Using cached mingw-w64-i686-pkgconf-1~1.8.0-2-any.pkg.tar.zst.
-- Using cached msys2-msys2-runtime-3.4.6-1-x86_64.pkg.tar.zst.
-- Using msys root at C:/Veed/vcpkg/downloads/tools/msys2/6f3fa1a12ef85a6f
-- Configuring x64-windows-dbg
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:112 (message):
    Command failed: C:/Veed/vcpkg/downloads/tools/msys2/d7266db249278763/usr/bin/bash.exe --noprofile --norc --debug -c "V=1 CPP='cl.exe -E' CC='cl.exe' CC_FOR_BUILD='cl.exe' CPP_FOR_BUILD='cl.exe -E' CXX_FOR_BUILD='cl.exe' CXX='cl.exe' RC='rc.exe' WINDRES='rc.exe' AR='lib.exe' LD='link.exe -verbose' RANLIB=':' STRIP=':' NM='dumpbin.exe -symbols -headers' DLLTOOL='link.exe -verbose -dll' CCAS=':' AS='C:/Veed/vcpkg/downloads/tools/nasm/nasm-2.16.01/nasm.exe' AS='C:/Veed/vcpkg/downloads/tools/nasm/nasm-2.16.01/nasm.exe' ./../src/37ae96baf0-6a8b74b3ff.clean/configure --build=x86_64-pc-mingw32 \"--disable-lavf\" \"--disable-swscale\" \"--disable-avs\" \"--disable-ffms\" \"--disable-gpac\" \"--disable-lsmash\" \"--disable-bashcompletion\" \"ac_cv_prog_ac_ct_STRIP=:\" \"gl_cv_double_slash_root=yes\" \"ac_cv_func_memmove=yes\" \"--disable-silent-rules\" \"--verbose\" \"--enable-shared\" \"--disable-static\" \"--enable-debug\" \"--disable-cli\" \"--prefix=/C/Veed/vcpkg/installed/x64-windows/debug\""
    Working Directory: C:/Veed/vcpkg/buildtrees/x264/x64-windows-dbg
    Error code: 2
    See logs for more information:
      C:\Veed\vcpkg\buildtrees\x264\config-x64-windows-dbg-err.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_make.cmake:838 (vcpkg_execute_required_process)
  ports/x264/portfile.cmake:96 (vcpkg_configure_make)
  scripts/ports.cmake:168 (include)



```
<details><summary>C:\Veed\vcpkg\buildtrees\x264\config-x64-windows-dbg-err.log</summary>

```
./../src/37ae96baf0-6a8b74b3ff.clean/configure: line 2: unset: `AS
': not a valid identifier
./../src/37ae96baf0-6a8b74b3ff.clean/configure: line 3: $'\r': command not found
./../src/37ae96baf0-6a8b74b3ff.clean/configure: line 65: syntax error near unexpected token `$'{\r''
./../src/37ae96baf0-6a8b74b3ff.clean/configure: line 65: `log_check() {
'
```
</details>

**Comment by FrankXie05** [comment]
>$'\r': command not found

AFAIK, all files installed by `vcpkg` on `windows` end with `CR LF(\r\n)`, and `LF(\n)` will only appear on `!Windows` by default.

**Comment by FrankXie05** [comment]
Could you please delete the cache and try again?

**Comment by jakubtyrcha** [comment]
> Could you please delete the cache and try again?

I deleted `buildtrees` and I have the same issue. Is there some other cache I can clear?

**Comment by dg0yt** [comment]
> CMake Warning at scripts/cmake/vcpkg_configure_make.cmake:269 (message):
>   Unable to find system dir in the PATH variable! Appending required msys
>   paths!

I thought this was fixed...
Given this warning, can we be sure that msys bash doesn't accidentally call incompatible tools when we expect to see msys tools - including further invocations of msys bash?

**Comment by jakubtyrcha** [comment]
> > CMake Warning at scripts/cmake/vcpkg_configure_make.cmake:269 (message):
> > Unable to find system dir in the PATH variable! Appending required msys
> > paths!
> 
> I thought this was fixed... Given this warning, can we be sure that msys bash doesn't accidentally call incompatible tools when we expect to see msys tools - including further invocations of msys bash?

My knowledge of vcpkg build system and msys bash is rather limited. Is there something I can do to answer this question? Is there a workaround for the problem I am seeing?

**Comment by dg0yt** [comment]
You might at least show your `PATH`.
(The relevant code change was made three months ago.)

**Comment by jakubtyrcha** [comment]
> You might at least show your `PATH`. (The relevant code change was made three months ago.)

```C:\Users\jakub\AppData\Local\Programs\Python\Python311\Scripts\;C:\Users\jakub\AppData\Local\Programs\Python\Python311\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v12.1\libnvvp;C:\Program Files\Microsoft MPI\Bin\;C:\VulkanSDK\1.2.182.0\Bin;C:\VulkanSDK\1.2.176.1\Bin;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\windows\System32\OpenSSH\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Yarn\bin\;C:\Users\jakub\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Program Files\CMake\bin;C:\Program Files\NVIDIA Corporation\Nsight Compute 2023.1.0\;C:\Program Files\Git\cmd;C:\Program Files\dotnet\;C:\Program Files\nodejs\;C:\Program Files\Docker\Docker\resources\bin;C:\Users\jakub\AppData\Local\pnpm;C:\Users\jakub\scoop\shims;C:\Users\jakub\.cargo\bin;C:\Users\jakub\AppData\Local\Microsoft\WindowsApps;C:\Users\jakub\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\jakub\AppData\Local\Yarn\bin;D:\ffmpeg-2021-07-06-git-758e2da289-full_build\bin;C:\Users\jakub\AppData\Roaming\nvm;D:\Users\jakub\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;D:\zig;C:\Users\jakub\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\jakub\AppData\Local\Programs\Python\Python311;C:\Users\jakub\AppData\Local\Programs\Python\Python311\Scripts;;C:\Users\jakub\AppData\Local\Programs\Julia-1.8.5\bin;C:\Users\jakub\AppData\Roaming\npm```

**Comment by jakubtyrcha** [comment]
I don't know what `$ENV{PATH}` is, but it doesn't seem to match my `$env:Path` at all.

The cmake one is:
```
CMake Warning at scripts/cmake/vcpkg_configure_make.cmake:256 (message):
  path_list:C:/Program Files/Microsoft Visual
  Studio/2022/Professional/VC/Tools/MSVC/14.36.32532/bin/HostX64/x64;C:/Program
  Files/Microsoft Visual
  Studio/2022/Professional/Common7/IDE/VC/VCPackages;C:/Program
  Files/Microsoft Visual
  Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TestWindow;C:/Program
  Files/Microsoft Visual
  Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/TeamFoundation/Team
  Explorer;C:/Program Files/Microsoft Visual
  Studio/2022/Professional/MSBuild/Current/bin/Roslyn;C:/Program
  Files/Microsoft Visual Studio/2022/Professional/Team Tools/Performance
  Tools/x64;C:/Program Files/Microsoft Visual Studio/2022/Professional/Team
  Tools/Performance Tools;C:/Program Files (x86)/Microsoft Visual
  Studio/Shared/Common/VSPerfCollectionTools/vs2019/x64;C:/Program Files
  (x86)/Microsoft Visual
  Studio/Shared/Common/VSPerfCollectionTools/vs2019/;C:/Program Files
  (x86)/Windows Kits/10/bin/10.0.22000.0/x64;C:/Program Files (x86)/Windows
  Kits/10/bin/x64;C:/Program Files/Microsoft Visual
  Studio/2022/Professional/MSBuild/Current/Bin/amd64;C:/Windows/Microsoft.NET/Framework64/v4.0.30319;C:/Program
  Files/Microsoft Visual Studio/2022/Professional/Common7/IDE/;C:/Program
  Files/Microsoft Visual
  Studio/2022/Professional/Common7/Tools/;C:/Repos/vcpkg/downloads/tools/powershell-core-7.2.11-windows;C:/windows/system32;C:/windows;C:/windows/system32/Wbem;C:/windows/system32/WindowsPowerShell/v1.0/;C:/Program
  Files/Microsoft Visual
  Studio/2022/Professional/VC/Tools/Llvm/x64/bin;C:/Program Files/Microsoft
  Visual
  Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/bin;C:/Program
  Files/Microsoft Visual
  Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja;C:/Program
  Files/Microsoft Visual
  Studio/2022/Professional/Common7/IDE/VC/Linux/bin/ConnectionManagerExe;C:/Program
  Files/Microsoft Visual
  Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja;C:/Program
  Files/Microsoft Visual
  Studio/2022/Professional/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja
```

I cleared the `buildtrees` and hardcoded the `vcpkg_configure_make.cmake` line to `cmake_path(CONVERT "$ENV{PATH};C:/Windows/System32" TO_CMAKE_PATH_LIST path_list NORMALIZE)` and I don't get the warning any more. The final error persists.

**Comment by dg0yt** [comment]
> ardcoded the `vcpkg_configure_make.cmake` line to `cmake_path(CONVERT "$ENV{PATH};C:/Windows/System32" TO_CMAKE_PATH_LIST path_list NORMALIZE)` and I don't get the warning any more. The final error persists.

Appending disables the warning, but doesn't change effective order. It would have been more interesting to replace `C:/windows/system32`. But I'm not optimistic about the result.

**Comment by jakubtyrcha** [comment]
> > ardcoded the `vcpkg_configure_make.cmake` line to `cmake_path(CONVERT "$ENV{PATH};C:/Windows/System32" TO_CMAKE_PATH_LIST path_list NORMALIZE)` and I don't get the warning any more. The final error persists.
> 
> Appending disables the warning, but doesn't change effective order. It would have been more interesting to replace `C:/windows/system32`. But I'm not optimistic about the result.

This `cmake_path(CONVERT "C:/Windows/System32;$ENV{PATH}" TO_CMAKE_PATH_LIST path_list NORMALIZE)` actually worked. Thanks, at least I have a workaround! Would be great if this was converted into a proper fix.
