### ISSUE TITLE
llvm toolchain - vcpkg integration - lld-linker error 

### ISSUE THREAD

**Issue by Neumann-A** [Microsoft/vcpkg#4359]
Using the lld-linker I get the following error:

1>lld-link.exe : error : could not open C:\Sources\Extern\vcpkg\installed\x64-windows-static\lib\*.lib: invalid argument

apparently the lld-linker does not like to include libraries by wildcards.

The problem lies within:
<vcpkgroot>\scripts\buildsystems\msbuild\vcpkg.targets
 line 62 & 63

where
      <AdditionalDependencies Condition="'$(VcpkgNormalizedConfiguration)' == 'Debug' and '$(VcpkgAutoLink)' != 'false'">%(AdditionalDependencies);$(VcpkgRoot)debug\lib\*.lib</AdditionalDependencies>
      <AdditionalDependencies Condition="'$(VcpkgNormalizedConfiguration)' == 'Release' and '$(VcpkgAutoLink)' != 'false'">%(AdditionalDependencies);$(VcpkgRoot)lib\*.lib</AdditionalDependencies>
is defined.

So it would be very nice if vcpkg would add and extra item for itself to the project configuration (like the llvm toolchain) so that I can easily change the values of $(VcpkgAutoLink), $(VcpkgTriplet), $(VcpkgEnabled) and maybe even $(VcpkgRoot).

**Comment by degski** [comment]
@Neumann-A A quick work-around is to simply change

    %(AdditionalDependencies);$(VcpkgRoot)debug\lib*.lib
    %(AdditionalDependencies);$(VcpkgRoot)lib*.lib

to

    %(AdditionalDependencies)
    %(AdditionalDependencies)

as lld-link does wild-card-linking by default, without specifying that. As long as it knows where to look, it will find the correct library to link.

lld-link has also an option `/lib` which supposedly makes `lld-link` behave as `lib`. I don't know what that entails, because `/lib` has to be the first command option passed, which seems to be hard to achieve from the VC-IDE, maybe you're able to work it out.

**Comment by degski** [comment]
The [LLVM Compiler Toolchain Plugin](https://marketplace.visualstudio.com/items?itemName=LLVMExtensions.llvm-toolchain) fixes the use of lld from the VS2017-IDE.

**Comment by degski** [comment]
Sorry, I did not realize you were working on [this](https://github.com/Microsoft/vcpkg/pull/4361). I guess that's not yet merged into master or what are the magic spells to end up with the vcpkg integration?

As to the wild-card issue, maybe it's an idea to report that on the clang dev list, as `link.exe` compatibility (for `lld-link.exe` is AFAIK an objective).

**Comment by Neumann-A** [comment]
@degski: https://bugs.llvm.org/show_bug.cgi?id=38985

**Comment by degski** [comment]
I see.

**Comment by szabolcshorvath-craft** [comment]
Why is this issue closed? It's mid 2021 and still I get the same message:
> 1>  lld-link : error : could not open 'C:\Users\szabolcs\vcpkg\scripts\buildsystems\msbuild\..\..\..\installed\x64-windows\debug\lib\*.lib': invalid argument

Environment:
Windows10, VS2019, C++, newly created Command Line Application project, Platform Toolset: llvm (clang-cl), vcpkg integration installed

Even though this issue may have been solved already, it's not clear for me, what to do to resolve this error.
Or should I open another issue for this?

**Comment by Neumann-A** [comment]
> Why is this issue closed? It's mid 2021 and still I get the same message:

old integration installed? Remove it and reinstall it. This issue was also mainly for the  toolset called `LLVM` which was installed by LLVM itself. The `ClangCL` toolset which gets installed by VS itself is probably not handled correctly.  

you may be able to adjust the check in https://github.com/microsoft/vcpkg/blob/5742e878fc71b4fcb9c019b50f1f887f22db58df/scripts/buildsystems/msbuild/vcpkg.props#L26

In the ClangCL toolset I have seen the boolean `ClangClMode` in `ClCompile`

` <VcpkgAutoLink Condition="'$(UseLldLink)' == 'true' or '%(ClCompile.ClangClMode)' == 'true'">false</VcpkgAutoLink> `

**Comment by szabolcshorvath-craft** [comment]
Thank you for the quick response! It's a new integration because a recent upgrade of vcpkg deleted all my previously installed packages, so I've decided to make a clean start over. But just to be sure, now I've reinstalled the integration and the problem still remains. Indeed, I'm using the LLVM platform toolset installed by VS itself. Also thank you for the tip, I will look into if I could adjust that check!

**Comment by tommitytom** [comment]
I'm getting this error on one of my AppVeyor builds too - google led me here.  Unsure whether it is an issue with how I've set up the CI, or whether it's how they create the CI image.  The project I'm building only contains a single .cpp file.  Log here if its of any use: https://ci.appveyor.com/api/buildjobs/yh8sm1bnq63a8kcd/log

**Comment by Ou7law007** [comment]
How is this not solved yet? Having to disable auto link and manually link libs is not practical!

**Comment by snealbli** [comment]
I am also having this problem, identical to https://github.com/microsoft/vcpkg/issues/4359#issuecomment-894114021

Is there a solution?

**Comment by drywolf** [comment]
Looks like the **temporary** fix done in #4573 no longer works ?
I am also getting the same error as mentioned by OP:

`1>lld-link : error : could not open 'C:\code\vcpkg\installed\\x64-windows\debug\lib\*.lib': invalid argument`

**Comment by gurachan** [comment]
this still an issue until this day .. xD omg..

**Comment by dstanfor350** [comment]
I found if in the build toolbar I had "Debug" **"x32"** I get the lld-link error.  Changing the "**x32"** to **'x64"** the error is gone, all is good.  If you really want to build x32, I suppose, out of luck for now.

**Comment by pudding186** [comment]
this error because you integrate vcpkg to Visual Studio , run command "vcpkg integrate remove" then everything is OK

**Comment by gurachan** [comment]
> this error because you integrate vcpkg to Visual Studio , run command "vcpkg integrate remove" then everything is OK

but thats a feature xD removing a feature its a not a fix. its a temp solution u have to import manually the include and libs if u dont integrate  it..

**Comment by M0n7y5** [comment]
So its a still an issue ...

**Comment by RT222** [comment]
I too can't build my projects with Clang without disabling the autolink feature. Is supporting both at the same time planned? It would be great, because the autolink feature is really convenient on projects with many dependencies. I thinks this issue should be reopened.

**Comment by dtroitskiy** [comment]
Just encountered it too.

**Comment by stxticOVFL** [comment]
> this error because you integrate vcpkg to Visual Studio , run command "vcpkg integrate remove" then everything is OK

Issue is still present, this "fix" still works.

**Comment by walbourn** [comment]
https://github.com/microsoft/vcpkg/pull/31239
