### ISSUE TITLE
CMake 4 build failures

### ISSUE THREAD

**Issue by LegalizeAdulthood** [microsoft/vcpkg#44783]
### Operating system

any

### Compiler

any

### Steps to reproduce the behavior

```Shell
The following ports contain an embedded CMakeLists.txt that specifies a cmake_minimum_required version < 3.5, without a version range, which is guaranteed to fail on CMake 4.0 that is deployed on github runners:

CPPUNIT\CMAKELISTS.TXT
cmake_minimum_required(VERSION 2.8.12)

CSPICE\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.1)

FREEIMAGE\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.4)

GAMMA\CMAKELISTS.TXT
cmake_minimum_required (VERSION 3.0)

HTTP-PARSER\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.4)

JACK2\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.1)

JBIGKIT\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.4)

JXRLIB\CMAKELISTS.TXT
cmake_minimum_required(VERSION 2.8)

LIBMODBUS\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.0)

LIBMPEG2\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.2)

LIBODB\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.0)

LIBODB-BOOST\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.0)

LIBODB-MYSQL\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.0)

LIBODB-PGSQL\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.0)

LIBODB-SQLITE\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.0)

LIBOPUSENC\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.4)

LIBPOPT\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.0)

LIBSTK\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.0)

LIBUSB-WIN32\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.0)

LIBUUID\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.0)

NLOHMANN-FIFO-MAP\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.1)

OPENCSG\CMAKELISTS.TXT
cmake_minimum_required (VERSION 3.4)

PLIB\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.3.0)

PLUSTACHE\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.1 FATAL_ERROR)

PQP\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.0)

RAGEL\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.0)

SDL1-NET\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.0)

SDL2-GFX\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.0)

SPEEXDSP\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.1)

TINYFILEDIALOGS\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.4)

TINYXML\CMAKELISTS.TXT
cmake_minimum_required(VERSION 3.4)

WREN\CMAKELISTS.TXT
cmake_minimum_required(VERSION 2.8.12)
```

### Failure logs

All the above supplied CMakeLists.txt will fail when using CMake 4.0

### Additional context

The above search was performed with commit 460551b0ec06be1ba6b918448bf3b0f44add813d checked out.

**Comment by LegalizeAdulthood** [comment]
libuuid fixed in PR #44747

**Comment by Cheney-W** [comment]
This issue should be fixed by PR https://github.com/microsoft/vcpkg/pull/44712

**Comment by LegalizeAdulthood** [comment]
> This issue should be fixed by PR #44712

Nope, all the CMakeLists.txt that I mentioned are supplied by the ports themselves and they all have to be updated.  Some are being individually updated and fixed in other PRs.

**Comment by LegalizeAdulthood** [comment]
This issue isn't fixed at all and shouldn't be closed.

**Comment by LegalizeAdulthood** [comment]
Hrm, maybe it **is** worked around, based on reading the documentation for this new 4.0 variable [CMAKE_POLICY_VERSION_MINIMUM](https://cmake.org/cmake/help/latest/variable/CMAKE_POLICY_VERSION_MINIMUM.html), but it feels like a work-around and not an actual fix.

**Comment by LegalizeAdulthood** [comment]
Another work-around is to use overlay ports and adjust the included `CMakeLists.txt` file in the overlay.

**Comment by Cheney-W** [comment]
I don't understand why you say that PR #44712 only fixes libuuid, while all the other libraries are still broken.
This PR modifies the port.cmake file, which is invoked during the installation of all ports. The change explicitly sets CMAKE_POLICY_VERSION_MINIMUM to 3.5 under CMake 4, thereby preventing the error from being triggered.

However, as you mentioned, this is indeed a temporary workaround. The real solution should still come from upstream fixing their respective CMakeLists.txt files. So if an upstream project makes such a fix, we will apply it by updating the corresponding port, rather than proactively patching every potentially affected port ourselves.

**Comment by LegalizeAdulthood** [comment]
> I don't understand why you say that PR #44712 only fixes libuuid

I misunderstood the use of this new variable that was introduced in 4.0 -- apparently, specifically to address this problem.

> However, as you mentioned, this is indeed a temporary workaround. The real solution should still come from upstream fixing their respective CMakeLists.txt files.

Agreed.  In this bug, **all the CMakeLists.txt are being provided by the port**, e.g. the "upstream" provider of these CMakeLists.txt is vcpkg itself.

**Comment by Cheney-W** [comment]
> Agreed. In this bug, **all the CMakeLists.txt are being provided by the port**, e.g. the "upstream" provider of these CMakeLists.txt is vcpkg itself.

I appreciate you pointing this out. I hadn’t noticed that these CMakeLists.txt files come from vcpkg itself. We’ll incorporate the necessary changes when we update the corresponding ports in the future.

**Comment by LegalizeAdulthood** [comment]
As I re-read my initial bug report, I didn't make it clear that these CMakeLists.txt are coming from vcpkg itself, sorry for not being more explicit about that.
