### ISSUE TITLE
[vcpkg-tool] cache fail in GHA

### ISSUE THREAD

**Issue by talregev** [microsoft/vcpkg#45073]
### Operating system

windows github action

### Compiler

msvc

### Steps to reproduce the behavior

```Shell
vcpkg install xxx
```

### Failure logs

https://github.com/curl/curl/pull/17069

More detail on curl PR.

**Comment by talregev** [comment]
CC @vszakats

**Comment by vszakats** [comment]
Some more experiments here:
https://github.com/curl/curl/pull/17071

Tried downgrading vcpkg-tool.
Tried dropping `windows-11-arm` runner from the workflow. (this started happening right when I added this runner yesterday.)

**Comment by vszakats** [comment]
Here's a `vcpkg --debug` log about trying to upload to the cache, then reporting that zero upload has been done:
```
Starting submission of vcpkg-cmake:x64-linux@2024-04-23 to 1 binary cache(s) in the background
[...]
[DEBUG] 1025: execute_process(curl -s -L -H "User-Agent: vcpkg/2025-03-13-7699e411ea11543de6abc0c7d5fd11cfe0039ae5 (curl)" -H "Accept: application/json;api-version=6.0-preview.1" -H "Content-Type: application/json" -H "Authorization: ***" -X POST --data-raw "{
  \"key\": \"vcpkg-cmake-420a1c6ff1038356b66b2ffb7212025ab6f913d0a057a948337a6e15e85ce226\",
  \"version\": \"420a1c6ff1038356b66b2ffb7212025ab6f913d0a057a948337a6e15e85ce226\",
  \"cacheSize\": 10087
}
"
https://acghubeus2.actions.githubusercontent.com/LBtO2h2PnCINU7gm3jjmEjodUj2g1Be2AKcmGQDkydACxmcFgb/_apis/artifactcache/caches)
[...]
Completed submission of vcpkg-cmake:x64-linux@2024-04-23 to 0 binary cache(s) in 127 ms
```
https://github.com/curl/curl/actions/runs/14492605120/job/40652434807?pr=17071#step:5:708

This happens with all packages sent up to the cache.

Packages not showing up in the cache: https://github.com/curl/curl/actions/caches

**Comment by jdpurcell** [comment]
Could be related to https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/ ?

**Comment by vszakats** [comment]
@jdpurcell Thanks for the pointer. It may be related. Our workflow does edit
`ACTIONS_CACHE_URL` and `ACTIONS_RUNTIME_TOKEN`. The page
suggests this means relying on an old cache API. This also explain the sudden
disappearance of these cache entries.

Our setup follows these instructions, which may be outdated in the light of
the GitHub announcement:
https://learn.microsoft.com/vcpkg/consume/binary-caching-github-actions-cache
https://learn.microsoft.com/vcpkg/reference/binarycaching#gha

I wonder if it means that the vcpkg binary cache feature fell into the cracks
of this deprecation and now unavailable? (The docs made it clear from the
get go that this feature may disappear anytime. This would nevertheless be
fatal for curl's use case.)

If still available, what action to take to keep using it?

**Comment by ADKaster** [comment]
This affects [LadybirdBrowser/ladybird](https://github.com/LadybirdBrowser/ladybird) in a very negative way as well, bringing our CI times from 10-20 minutes to over an hour per job. An update to the documentation on how to make`"VCPKG_BINARY_SOURCES": "clear;x-gha,readwrite"` work again would be much appreciated, and probably take a lot of minutes off of GHA runners for projects that were relying on this feature.

**Comment by talregev** [comment]
cc @BillyONeal

**Comment by HunterZ** [comment]
I think I'm seeing the same thing: https://github.com/microsoft/vcpkg-docs/issues/473#issuecomment-2816468599

**Comment by magnesj** [comment]
We use vcpg and cache artifacts, the build servers now use 2-3 hours to build the required vcpkg binaries. https://github.com/OPM/ResInsight

Please provide guidance on how to move forward.

**Comment by rustyconover** [comment]
Seems like I'm running into this as well building duckdb extensions that use vcpkg.

From a workflow:

```
[DEBUG] 1161: execute_process(curl -s -L -H "User-Agent: vcpkg/2024-11-12-eb492805e92a2c14a230f5c3deb3e89f6771c321 (curl)" -H "Accept: application/json;api-version=6.0-preview.1" -H "Content-Type: application/json" -H "Authorization: ***" -X POST --data-raw "{
  \"key\": \"vcpkg-boost-306daf81a520f4add175100ac70e74920e14e12d652a5b8c6a98de19e4d988c9\",
  \"version\": \"306daf81a520f4add175100ac70e74920e14e12d652a5b8c6a98de19e4d988c9\",
  \"cacheSize\": 5921
}
" https://acghubeus1.actions.githubusercontent.com/3e7hfOg6omJcp3e2ihsBHbIEVGL8M2XqyVr0FPSVNt5PURu7GQ/_apis/artifactcache/caches)
[DEBUG] 1161: cmd_execute_and_stream_data() returned 0 after   334077 us
Stored binaries in 0 destinations in 342 ms.
```

The indication seems to be "Stored binaries in 0 destinations".

**Comment by sohitgore** [comment]
+1 
```
[DEBUG] 1241: cmd_execute_and_stream_data() returned 0 after  2325524 us
-- Performing post-build validation
[DEBUG] 1242: execute_process(cd /github_workspace/ebpf_sensor/tools/vcpkg/vcpkg-src/packages/libuuid_x64-linux && zip --quiet -y -r /github_workspace/ebpf_sensor/tools/vcpkg/vcpkg-src/packages/libuuid_x64-linux.zip * --exclude .DS_Store)
[DEBUG] 1242: cmd_execute_and_stream_data() returned 0 after     6649 us
[DEBUG] 1243: execute_process(curl -s -L -H "User-Agent: vcpkg/2024-07-10-d2dfc73769081bdd9b782d08d27794780b7a99b9 (curl)" -H "Accept: application/json;api-version=6.0-preview.1" -H "Content-Type: application/json" -H "Authorization: ***" -X POST --data-raw "***
  \"key\": \"libuuid-320ce6ebe7e8b1732e26ea8df3203987df20257e5a3dd3e2ab2c805632a6f4b0\",
  \"version\": \"320ce6ebe7e8b1732e26ea8df3203987df20257e5a3dd3e2ab2c805632a6f4b0\",
  \"cacheSize\": 33464
***
" https://acghubeus1.actions.githubusercontent.com/IhmGkW4ttwa5pLDWIghNT6yx5tnl9ZxHFwUb2PbUgdTuFh0fXZ/_apis/artifactcache/caches)
[DEBUG] 1243: cmd_execute_and_stream_data() returned 0 after   114622 us
Stored binaries in 0 destinations in 121 ms.
```

**Comment by wench** [comment]
Until the underlying issue is fixed, i have modified my workflows to use the action cache to to save and restore the `vcpkg_installed` directories of my projects. It seems to work well and has eliminated the hour long package builds I was experiencing on every push, Only issue I noticed is that if the version of vcpkg installed in the runner image changes then vcpkg tends to want to rebuild the packages. I decided to add the git hash of the installed vcpkg in the runner image as part of my cache keys so caches are specific for the vcpkg versions. I'm sure there is a better way to do this but it's a good enough solution for me for now.

**Comment by andrewward22** [comment]
Workaround for manifest mode:

```
- name: Restore vcpkg cache
  uses: actions/cache/restore@v4
  with:
    path: ~/.cache/vcpkg/archives
    key: some-build-specific-key
    
<Run CMake here>

- name: Save vcpkg cache
  uses: actions/cache/save@v4
  with:
    path: ~/.cache/vcpkg/archives
    key: some-build-specific-key
```

**Comment by JasonDictos** [comment]
How would one use the artifact cache v4 thing when the build is ocurring within a docker container? We had used the --secret features of docker to forward the action cache env over into the build, allowing it to http out to post/fetch artifacts.

**Comment by talregev** [comment]
For all the people that subscribe to this issue.
vcpkg team decided to remove support in gha.
So this issue will be not relevant soon. 
https://github.com/microsoft/vcpkg-tool/pull/1662

I already see this alternative, https://github.com/microsoft/vcpkg/issues/45073#issuecomment-2828284201
But it not so good as `gha binary cache provider` was. mainly because if you the cache is invalid, all the needed ports need to be install, instead that only the updated port was installed.

Can we think on other alternative?

**Comment by JasonDictos** [comment]
Switch to nuget provider, u basically need a PAT classic token and then you're off to the races.

https://github.com/OPM/ResInsight/pull/12407/files

https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility

Note for those using vcpkg caching from within a docker container you'll have to use a static nuget config pointing to clear text env bars for the token that you can export from a docker secret arg so it is not persistent on the image.

**Comment by talregev** [comment]
I see your PR.
Can you elaborate the json file that you mention here?
```
      VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/ceetronsolutions/index.json,readwrite"

```

**Comment by ADKaster** [comment]
In https://github.com/LadybirdBrowser/ladybird/pull/4461, we went with the "cache the built artifacts" approach, rather than trying to cache `$CMAKE_BINARY_DIR/vcpkg_installed/`.

The most important part is to set `VCPKG_BINARY_SOURCES` to the same `files` source we use for local builds.
   - In ./CMakePresets.json, that's `"environment": { "VCPKG_BINARY_SOURCES": "clear;files,${fileDir}/Build/caches/vcpkg-binary-cache,readwrite;$penv${VCPKG_BINARY_SOURCES}" },`
   - In workflows, that's `${{ github.workspace }}/Build/caches/vcpkg-binary-cache` (after a checkout action)

Though I can't speak to how good of an idea it is to cache the files source for VCPKG_BINARY_SOURCES. In theory this should do the same thing as the per-package cache entries `x-gha` was doing, but I also don't know anything about the eviction policies for that vcpkg-tool feature (will it grow indefinitely?) or how well this responds to a vcpkg baseline bump in `vcpkg.json` (will it see the hash change and force a full rebuild, even though many package versions have not changed?).

**Comment by talregev** [comment]
> we went with the "cache the built artifacts" approach

on the comment I link, it also the cache the built artifacts approach.

>  In theory this should do the same thing as the per-package cache entries x-gha was doing.

It not the same. when you invalidate the cache, all the packages need to rebuild. on x-gha, no need to invalidate the cache (you don't have a key for that also), only the updated packages was updating, and I i don't mistaken in the x-gha, after 30 days that the packages didn't restore (due it old), then it automatics deleted.

**Comment by JasonDictos** [comment]
> I see your PR. Can you elaborate the json file that you mention here?
> 
> ```
>       VCPKG_BINARY_SOURCES: "clear;nuget,https://nuget.pkg.github.com/ceetronsolutions/index.json,readwrite"
> ```

No my pr; I work on a closed repo, that was what I used as a guide though.

That json file isn't something you edit thats just the endpoint that comes with the github product for stashing nuget packages. If you're building directly in github actions that pr has everything you need, however we build within docker so we had to forward the token into the container using a secret like so:

```
else ifdef GH_PACKAGES_TOKEN
image: Dockerfile
  DOCKER_BUILDKIT=1 docker build -t $(IMAGE_PATH) . -f Dockerfile \
          --secret id=gh_pkg_token,env=GH_PACKAGES_TOKEN\
          --secret id=gh_token,env=BOT_ACCESS_TOKEN --progress plain
else

```

Then in the docker build step:

```
# Install pre-packaged ports for the image
RUN --mount=type=ssh \
    --mount=type=secret,id=gh_pkg_token vcpkg ....
```

And somewhere you have to set the binary sources env:
```
    export VCPKG_BINARY_SOURCES="clear;nuget,GitHubPackages,readwrite"
```

You will need to install mono-complete and dotnet-sdk-9.0, and then nuget will work by prefixing it with 'mono'. 

The way we got around persistently storing the token in the docker image is we used a config template:
```
COPY resource/NuGet.Config /root/.config/NuGet/NuGet.Config

```
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
    <add key="GitHubPackages" value="https://nuget.pkg.github.com/%GH_PACKAGES_USER%/index.json" />
  </packageSources>
  <packageSourceCredentials>
    <GitHubPackages>
        <add key="Username" value="%GH_PACKAGES_USER%" />
        <add key="ClearTextPassword" value="%GH_PACKAGES_TOKEN%" />
      </GitHubPackages>
  </packageSourceCredentials>
  <apikeys>
    <add key="https://nuget.pkg.github.com/%GH_PACKAGES_USER%/index.json" value="%GH_PACKAGES_TOKEN%" />
  </apikeys>
</configuration>
~                    
```

So by loading the secret from /run/secrets/gh_pkg_token into the GH_PACKAGES_TOKEN_ENV, and by setting your github user name env GH_PACKAGES_USER nuget will authenticate...

**Comment by talregev** [comment]
@JasonDictos Thank you for your detail comment!
I still want to understand more about the nuget server.

> https://nuget.pkg.github.com/ceetronsolutions/index.json 

This is a public server?
It not match the user nor the repo-> `OPM/ResInsight`

Should I open a nuget server? or if I have a user in gha, let say talregev, should I replace the 
https://nuget.pkg.github.com/talregev/index.json

and where the user `magnesj` came from? 
taken from: `${{ env.USERNAME }}`

And as I understand this parameter is build in inside gha:
`${{ secrets.GH_PACKAGES_TOKEN }}`

Thank you for your help.

**Comment by JasonDictos** [comment]
If your GitHub url is

GitHub.com/MyNam/project

Then USERNAME is MyName

**Comment by HunterZ** [comment]
> Can we think on other alternative?

I ended up using actions/cache@v4 with the following key setup (I use CMake manifest mode) which hashes over anything that seems like it might affect validity of the vcpkg build products:
```yml
          key:
            cache-build-${{ matrix.triplet }}-${{ hashFiles('CMakeFiles.txt', 'CMakePresets.json', 'vcpkg.json', 'out/build/*/vcpkg_installed/compiler-file-hash-cache.json', 'out/build/*/vcpkg_installed/status') }}
          restore-keys: |
            cache-build-${{ matrix.triplet }}-
```

**Comment by magnesj** [comment]
> [@JasonDictos](https://github.com/JasonDictos) Thank you for your detail comment! I still want to understand more about the nuget server.
> 
> > https://nuget.pkg.github.com/ceetronsolutions/index.json
> 
> This is a public server? It not match the user nor the repo-> `OPM/ResInsight`
> 
> Should I open a nuget server? or if I have a user in gha, let say talregev, should I replace the https://nuget.pkg.github.com/talregev/index.json
> 
> and where the user `magnesj` came from? taken from: `${{ env.USERNAME }}`
> 
> And as I understand this parameter is build in inside gha: `${{ secrets.GH_PACKAGES_TOKEN }}`
> 
> Thank you for your help.

**Related links**
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-nuget-registry
https://docs.github.com/en/billing/managing-billing-for-your-products/managing-billing-for-github-packages/about-billing-for-github-packages

The NuGet packages are hosted at the top-level GitHub page (not on inside a repository) either on a personal or organization site. Here is a snapshot from the packages available at the `Packages` tab from my `CeetronSolutions` organization site.

![Image](https://github.com/user-attachments/assets/6c25ee27-0485-4e10-a67d-5b55874df994)

**Comment by JasonDictos** [comment]
> ```
> 
> <?xml version="1.0" encoding="utf-8"?>
> <configuration>
>   <packageSources>
>     <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
>     <add key="GitHubPackages" value="https://nuget.pkg.github.com/%GH_PACKAGES_USER%/index.json" />
>   </packageSources>
>   <packageSourceCredentials>
>     <GitHubPackages>
>         <add key="Username" value="%GH_PACKAGES_USER%" />
>         <add key="ClearTextPassword" value="%GH_PACKAGES_TOKEN%" />
>       </GitHubPackages>
>   </packageSourceCredentials>
>   <apikeys>
>     <add key="https://nuget.pkg.github.com/%GH_PACKAGES_USER%/index.json" value="%GH_PACKAGES_TOKEN%" />
>   </apikeys>
> </configuration>        
> So by loading the secret from /run/secrets/gh_pkg_token into the GH_PACKAGES_TOKEN_ENV, and by setting your github user name env GH_PACKAGES_USER nuget will authenticate...

I'm sorry but this doesn't work; problem is the NugGet config expects the value for the apikey to be an encrypted value, this causes this error, you will have to authenticate once and have it encrypt it to update the config:
```
nuget setapikey $GH_PACKAGES_TOKEN -Source https://nuget.pkg.github.com/EENCloud/index.json 
```

That will set the api key to an encrypted value...

**Comment by magnesj** [comment]
@jackjansen  vcpkg maintainer suggests NuGet as cache, see https://github.com/curl/curl/pull/17200#issuecomment-2839854264

**Comment by rustyconover** [comment]
> [@jackjansen](https://github.com/jackjansen) vcpkg maintainer suggests NuGet as cache, see [curl/curl#17200 (comment)](https://github.com/curl/curl/pull/17200#issuecomment-2839854264)

For anyone exploring this approach, please note that accessing the NuGet cache via vcpkg currently requires a compatible Mono (C# runtime) installation.

It would be great to see support for a lightweight, statically linked alternative to Mono or the AWS CLI for interacting with cache APIs.

Additionally, improved native integration of cache functionality within vcpkg — avoiding frequent external process spawning — could help performance, especially in CPU-constrained CI environments where process creation can become a bottleneck.

**Comment by JasonDictos** [comment]
@rustyconover agreed! Our image wernt from 800MB to 1.1GB just to support NuGet/mono-complete/dotnet-sdk-9 on our Fedora docker images...

**Comment by Derpius** [comment]
Not what I'd call "production ready", but we've written a lightweight action which leverages the built-in filesystem binary cache provider and `@actions/cache` to facilitate per-package caching in GHA: https://github.com/TAServers/vcpkg-cache

Didn't want to add a dependency on NuGet just to cache dependencies

**Comment by talregev** [comment]
> Not what I'd call "production ready", but we've written a lightweight action which leverages the built-in filesystem binary cache provider and `@actions/cache` to facilitate per-package caching in GHA: https://github.com/TAServers/vcpkg-cache
> 
> Didn't want to add a dependency on NuGet just to cache dependencies

Cool Idea! Can you add an example how to use it?

**Comment by jackjansen** [comment]
@Derpius that would be very nice... I really can't be bothered to learn NuGet and all that just to get vcpkg caching working...

**Comment by Derpius** [comment]
> Cool Idea! Can you add an example how to use it?

@talregev sure, writing a simple readme atm, but for now:

Configure env vars for the job:

```yaml
env:
  VCPKG_FEATURE_FLAGS: "binarycaching" # Not sure if this is required, but explicitly setting the binary caching feature flag
  VCPKG_ARCHIVE_PATH: "vcpkg-cache" # Can be any relative path you want
```

Add the cache workflow like so, before you run CMake configure (or whatever triggers your `vcpkg install`):
```yaml
- name: Restore vcpkg cache
  uses: TAServers/vcpkg-cache@master
  with:
    token: ${{ secrets.GITHUB_TOKEN }}
    archive-path: ${{ env.VCPKG_ARCHIVE_PATH }}
```

Write binary caches to your chosen directory in `GITHUB_WORKSPACE`:
```yaml
- name: CMake Configure
  env:
    VCPKG_BINARY_SOURCES: "clear;files,${{ env.GITHUB_WORKSPACE }}/${{ env.VCPKG_ARCHIVE_PATH }},readwrite"
  run: # Run cmake configure
```

Relative to `GITHUB_WORKSPACE` as it's a Docker action, and that gets mounted to `/github/workspace` in the container by default.

The filesystem cache provider already computes ABI hashes and stores per package, and the post- action runs on failures and cancellations guaranteeing that the cache is stored. This gives you basically the same capabilities as the now-removed GHA cache provider

**Comment by Derpius** [comment]
Set up with proper tagging: https://github.com/marketplace/actions/vcpkg-cache

**Comment by stripe2933** [comment]
> Set up with proper tagging: https://github.com/marketplace/actions/vcpkg-cache

Seems not working https://github.com/stripe2933/vk-gltf-viewer/commit/6a370e660e866ca1b79e160b10553928451a4985 (and not supporting except for x64 Linux)

**Comment by Derpius** [comment]
@stripe2933 had a look:

- It’s not working outside of x64 Linux due to Docker actions just not being supported by GitHub on those platforms…
  - Solution is just for me to make it a Node action. Was using Deno cause I wanted to try it out and wasn’t planning on wider adoption 😅 
- The 404 when trying to list caches is due to missing the `actions: read` permission on the workflow fairly sure.
  - Solution should be for you to add a permissions section to your workflow (be sure to add `contents: read` for checkout too): https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
  - I’ll update the readme and add some error handling which says this

**Comment by talregev** [comment]
Can you make it work on windows too? 🙏🏻
Thank you for the cool gh action plugin! 😎

**Comment by Derpius** [comment]
Switching it to a standard Node.js action should fix it on Windows (and arm64 Linux based on those other build failures)

A bit disappointing that Docker actions aren’t more widely supported. Having the dependencies self-contained is much cleaner imo (instead of ambiently having nodejs around on the default runner images)

**Comment by Derpius** [comment]
@talregev @stripe2933 I've converted it to a standard Node.js action, so it should be working on all runners now

Solved a bunch of other issues (namely me hardcoding our repo name and org like an idiot and cache version mismatches for the same key). Waiting on a full run in our pipeline to confirm it's still working on Linux

> [!IMPORTANT]
> The archive path is no longer relative to `$GITHUB_WORKSPACE` as it's no longer running in Docker, so the archive path you pass to the action should be the same path given to vcpkg **without prepending `$GITHUB_WORKSPACE`**

**Comment by stripe2933** [comment]
Tested with updated `TAServers/vcpkg-cache@v2`, successfully restored cache in macOS and Linux runners. Also tested it can handle the same OS/compiler with different architecture (it distinguishes x64 and arm64 arch). Thank you! 😊 Unfortunately, it is still not working in Windows runner. It can save the cached binary, but cannot restore it.

First attempt: https://github.com/stripe2933/vk-gltf-viewer/actions/runs/14853068174/attempts/1
Second attempt: https://github.com/stripe2933/vk-gltf-viewer/actions/runs/14853068174/attempts/2

|Runner configuration|Attempt 1|Attempt 2|Cache successful?|
|:---:|:---:|:---:|:---:|
|windows-latest,msvc|10m 28s|9m 54s||
|windows-latest,mingw-clang|11m 17s|12m 15s||
|ubuntu-latest,clang|9m 59s|3m 50s|✅|
|ubuntu-24.04-arm,clang|10m 25s|4m 15s|✅|
|macos-15,clang|5m 12s|2m 10s|✅|

Also unlike documentation, setting `VCPKG_ARCHIVE_PATH` as relative path such like `vcpkg-cache` does not work.

```
%VCPKG_BINARY_SOURCES%: error: invalid argument: binary config 'files' path arguments for binary config strings must be absolute
  on expression: clear;files,vcpkg-cache,readwrite
                             ^
-- Running vcpkg install - failed
```

> The archive path is no longer relative to $GITHUB_WORKSPACE as it's no longer running in Docker, so the archive path you pass to the action should be the same path given to vcpkg without prepending $GITHUB_WORKSPACE

Could you clarify what it means?

**Comment by Derpius** [comment]
@stripe2933 taking a look at the windows failures now

> Also unlike documentation, setting VCPKG_ARCHIVE_PATH as relative path such like vcpkg-cache does not work.

I did update the full example to use an absolute path, but didn’t update the short example at the top. Either way there should be a warning saying that the path must be absolute for vcpkg, will add 👍🏻 

Relative paths worked before as it was always joining it onto GITHUB_WORKSPACE

> Could you clarify what it means?

Sure:
- With Docker-based actions, GitHub mounts the path defined by `GITHUB_WORKSPACE` into the container at `/github/workspace` as the only way to access the workflow’s filesystem. This meant that the archive path had to be relative to `GITHUB_WORKSPACE` in order to see the files
- With Node-based actions, the entire filesystem of the workflow is accessible and so the path no longer has to be in GITHUB_WORKSPACE
  - And shouldn’t to avoid unnecessary cache misses across OSes, cause the vcpkg ABI hash will handle compatibility: https://github.com/osy/actions-cache/blob/main/tips-and-workarounds.md#cross-os-cache

**Comment by Derpius** [comment]
Need to normalise the paths 😄 

<img width="635" alt="Image" src="https://github.com/user-attachments/assets/01fa3b76-6553-41ae-b86e-7e34a0f3ade1" />

For context on why I’m now using the full path as the cache key prefix: https://github.com/actions/cache?tab=readme-ov-file#cache-version

I have no idea why this is a thing, when users are quite capable of adding the required granularity to their cache key to avoid restoring an incompatible hash. Couldn’t find a workaround for restoring a cache to a new location on disk causing a version mismatch

**Comment by Derpius** [comment]
@stripe2933 `v3` should work on windows now. Key changes:

- Archive path is no longer configurable. Read the absolute path from `steps.<vcpkg-cache step id>.outputs.path` and pass that to vcpkg. e.g. `VCPKG_BINARY_SOURCES: "clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite"`
  - The edge cases and platform-specific quirks were too much to realistically expect users of the action to worry about
  - It now always stores the cache in a `.vcpkg-cache` folder relative to the working directory
  - If you need to change the cache location from the default working directory, set the `working-directory: ...` on the step
- Fairly comprehensive integration tests for Ubuntu and Windows runners to ensure compatibility going forwards

**Comment by FangCunWuChang** [comment]
I hit this, it dragged down over 40 minutes of my pipeline time.

**Comment by Derpius** [comment]
@stripe2933 I noticed some erroneous cache misses in your most recent run with`v3`. I think this was due to exceeding the max 100 items per page as I didn't add pagination. Latest version should fix that (and the failed submissions on save due to not detecting that a cache entry already exists)

**Comment by maliavko** [comment]
> [@stripe2933](https://github.com/stripe2933) I noticed some erroneous cache misses in your most recent run with`v3`. I think this was due to exceeding the max 100 items per page as I didn't add pagination. Latest version should fix that (and the failed submissions on save due to not detecting that a cache entry already exists)

Today I decided to learn something new and setup a github workflow for the first time for my windows project. In the end of the fifth hour, hitting my head into the wall trying to get this bloody cache working I stumbled to this holy thread guys) Thanks, it works like a charm.

**Comment by sohitgore** [comment]
Im building inside a docker container and using this [comment](https://github.com/microsoft/vcpkg/issues/45073#issuecomment-2828284201) to save and restore cache.
Im mounting the `~/.cache/vcpkg/archives` inside the container, but vcpkg is not taking it.

I see the `nuget` solution by @JasonDictos but wondering why the above solution is not working...

**Comment by talregev** [comment]
> Im building inside a docker container and using this [comment](https://github.com/microsoft/vcpkg/issues/45073#issuecomment-2828284201) to save and restore cache. Im mounting the `~/.cache/vcpkg/archives` inside the container, but vcpkg is not taking it.
> 
> I see the `nuget` solution by [@JasonDictos](https://github.com/JasonDictos) but wondering why the above solution is not working...

run vcpkg with `--debug` flag and it will show you why it not take / restore the cache.

**Comment by sohitgore** [comment]
> > Im building inside a docker container and using this [comment](https://github.com/microsoft/vcpkg/issues/45073#issuecomment-2828284201) to save and restore cache. Im mounting the `~/.cache/vcpkg/archives` inside the container, but vcpkg is not taking it.
> > I see the `nuget` solution by [@JasonDictos](https://github.com/JasonDictos) but wondering why the above solution is not working...
> 
> run vcpkg with `--debug` flag and it will show you why it not take / restore the cache.

vcpkg `--debug` log dont provide any relevant information
the actions/cache is able to retrieve the cache `Cache restored successfully`
I am mounting the cache dir inside container correctly and even checked its content and size
`391M	/root/.cache/vcpkg/archives`

**Comment by FangCunWuChang** [comment]
So does anyone have any clues to solve this trouble？

**Comment by JasonDictos** [comment]
> So does anyone have any clues to solve this trouble？

You need to switch to [nuget](https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-nuget?pivots=shell-powershell)

**Comment by rustyconover** [comment]
I've just switched to using the S3 cache provider with Cloudflare R2.

**Comment by FangCunWuChang** [comment]
I followed [this](https://learn.microsoft.com/en-us/vcpkg/consume/binary-caching-github-packages?pivots=linux-runner) then using GitHub Packages as binary cache. And it works.  
For Ubuntu 24.04, you should install `mono` manually like [this](https://www.mono-project.com/download/stable/#download-lin).

**Comment by jackjansen** [comment]
For anyone getting to this issue through Google: the currently (December 2025) preferred way to set up the vcpkg cache is using Github Packages, and the vcpkg documentation has been updated to reflect this.

It's a PITA to set up but it works.
