### ISSUE TITLE
Vcpkg fails to install anything - File does not have the expected hash

### ISSUE THREAD

**Issue by parsa** [microsoft/vcpkg#4663]
Steps to reproduce:
* `vcpkg install --triplet x64-windows boost` (or any other package)
Expected outcome: Boost (or any other package) would install
Actual outcome: An error message complaining about hash mismatch for the installed 7-zip is displayed

Output:
```
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\Repos\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
File does not have the expected hash:
             url : [ https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 ]
       File path : [ C:\Repos\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg.part ]
   Expected hash : [ 8c75314102e68d2b2347d592f8e3eb05812e1ebb525decbac472231633753f1d4ca31c8e6881a36144a8da26b2571305b3ae3f4e2b85fc4a290aeda63d1a13b8 ]
     Actual hash : [ a9dfaaafd15d98a2ac83682867ec5766720acf6e99d40d1a00d480692752603bf3f3742623f0ea85647a92374df405f331afd6021c5cf36af43ee8db198129c0 ]
```

Detail:
* OS: Windows 10
* Vcpkg commit: 1c01a56dc8aa66c3769c29fce09dbcf8938cc17a

Full Output:
```
PS C:\Repos\vcpkg> vcpkg install --triplet x64-windows boost
The following packages will be built and installed:
    boost[core]:x64-windows
  * boost-accumulators[core]:x64-windows
  * boost-algorithm[core]:x64-windows
  * boost-align[core]:x64-windows
  * boost-any[core]:x64-windows
  * boost-array[core]:x64-windows
  * boost-asio[core]:x64-windows
  * boost-assert[core]:x64-windows
  * boost-assign[core]:x64-windows
  * boost-atomic[core]:x64-windows
  * boost-beast[core]:x64-windows
  * boost-bimap[core]:x64-windows
  * boost-bind[core]:x64-windows
  * boost-build[core]:x64-windows
  * boost-callable-traits[core]:x64-windows
  * boost-chrono[core]:x64-windows
  * boost-circular-buffer[core]:x64-windows
  * boost-compatibility[core]:x64-windows
  * boost-compute[core]:x64-windows
  * boost-concept-check[core]:x64-windows
  * boost-config[core]:x64-windows
  * boost-container[core]:x64-windows
  * boost-container-hash[core]:x64-windows
  * boost-context[core]:x64-windows
  * boost-contract[core]:x64-windows
  * boost-conversion[core]:x64-windows
  * boost-convert[core]:x64-windows
  * boost-core[core]:x64-windows
  * boost-coroutine[core]:x64-windows
  * boost-coroutine2[core]:x64-windows
  * boost-crc[core]:x64-windows
  * boost-date-time[core]:x64-windows
  * boost-detail[core]:x64-windows
  * boost-disjoint-sets[core]:x64-windows
  * boost-dll[core]:x64-windows
  * boost-dynamic-bitset[core]:x64-windows
  * boost-endian[core]:x64-windows
  * boost-exception[core]:x64-windows
  * boost-fiber[core]:x64-windows
  * boost-filesystem[core]:x64-windows
  * boost-flyweight[core]:x64-windows
  * boost-foreach[core]:x64-windows
  * boost-format[core]:x64-windows
  * boost-function[core]:x64-windows
  * boost-function-types[core]:x64-windows
  * boost-functional[core]:x64-windows
  * boost-fusion[core]:x64-windows
  * boost-geometry[core]:x64-windows
  * boost-gil[core]:x64-windows
  * boost-graph[core]:x64-windows
  * boost-graph-parallel[core]:x64-windows
  * boost-hana[core]:x64-windows
  * boost-hana-msvc[core]:x64-windows
  * boost-heap[core]:x64-windows
  * boost-hof[core]:x64-windows
  * boost-icl[core]:x64-windows
  * boost-integer[core]:x64-windows
  * boost-interprocess[core]:x64-windows
  * boost-interval[core]:x64-windows
  * boost-intrusive[core]:x64-windows
  * boost-io[core]:x64-windows
  * boost-iostreams[core]:x64-windows
  * boost-iterator[core]:x64-windows
  * boost-lambda[core]:x64-windows
  * boost-lexical-cast[core]:x64-windows
  * boost-local-function[core]:x64-windows
  * boost-locale[core]:x64-windows
  * boost-lockfree[core]:x64-windows
  * boost-log[core]:x64-windows
  * boost-logic[core]:x64-windows
  * boost-math[core]:x64-windows
  * boost-metaparse[core]:x64-windows
  * boost-modular-build-helper[core]:x64-windows
  * boost-move[core]:x64-windows
  * boost-mp11[core]:x64-windows
  * boost-mpl[core]:x64-windows
  * boost-msm[core]:x64-windows
  * boost-multi-array[core]:x64-windows
  * boost-multi-index[core]:x64-windows
  * boost-multiprecision[core]:x64-windows
  * boost-numeric-conversion[core]:x64-windows
  * boost-odeint[core]:x64-windows
  * boost-optional[core]:x64-windows
  * boost-parameter[core]:x64-windows
  * boost-phoenix[core]:x64-windows
  * boost-poly-collection[core]:x64-windows
  * boost-polygon[core]:x64-windows
  * boost-pool[core]:x64-windows
  * boost-predef[core]:x64-windows
  * boost-preprocessor[core]:x64-windows
  * boost-process[core]:x64-windows
  * boost-program-options[core]:x64-windows
  * boost-property-map[core]:x64-windows
  * boost-property-tree[core]:x64-windows
  * boost-proto[core]:x64-windows
  * boost-ptr-container[core]:x64-windows
  * boost-python[core]:x64-windows
  * boost-qvm[core]:x64-windows
  * boost-random[core]:x64-windows
  * boost-range[core]:x64-windows
  * boost-ratio[core]:x64-windows
  * boost-rational[core]:x64-windows
  * boost-regex[core]:x64-windows
  * boost-scope-exit[core]:x64-windows
  * boost-serialization[core]:x64-windows
  * boost-signals[core]:x64-windows
  * boost-signals2[core]:x64-windows
  * boost-smart-ptr[core]:x64-windows
  * boost-sort[core]:x64-windows
  * boost-spirit[core]:x64-windows
  * boost-stacktrace[core]:x64-windows
  * boost-statechart[core]:x64-windows
  * boost-static-assert[core]:x64-windows
  * boost-system[core]:x64-windows
  * boost-test[core]:x64-windows
  * boost-thread[core]:x64-windows
  * boost-throw-exception[core]:x64-windows
  * boost-timer[core]:x64-windows
  * boost-tokenizer[core]:x64-windows
  * boost-tti[core]:x64-windows
  * boost-tuple[core]:x64-windows
  * boost-type-erasure[core]:x64-windows
  * boost-type-index[core]:x64-windows
  * boost-type-traits[core]:x64-windows
  * boost-typeof[core]:x64-windows
  * boost-ublas[core]:x64-windows
  * boost-units[core]:x64-windows
  * boost-unordered[core]:x64-windows
  * boost-utility[core]:x64-windows
  * boost-uuid[core]:x64-windows
  * boost-variant[core]:x64-windows
  * boost-vcpkg-helpers[core]:x64-windows
  * boost-vmd[core]:x64-windows
  * boost-wave[core]:x64-windows
  * boost-winapi[core]:x64-windows
  * boost-xpressive[core]:x64-windows
  * boost-yap[core]:x64-windows
  * bzip2[core]:x64-windows
  * liblzma[core]:x64-windows
  * openssl[core]:x64-windows
  * openssl-windows[core]:x64-windows
  * python3[core]:x64-windows
  * zlib[core]:x64-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/143: boost-vcpkg-helpers:x64-windows
Building package boost-vcpkg-helpers[core]:x64-windows...
A suitable version of cmake was not found (required v3.11.4). Downloading portable cmake v3.11.4...
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\Repos\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
File does not have the expected hash:
             url : [ https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 ]
       File path : [ C:\Repos\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg.part ]
   Expected hash : [ 8c75314102e68d2b2347d592f8e3eb05812e1ebb525decbac472231633753f1d4ca31c8e6881a36144a8da26b2571305b3ae3f4e2b85fc4a290aeda63d1a13b8 ]
     Actual hash : [ a9dfaaafd15d98a2ac83682867ec5766720acf6e99d40d1a00d480692752603bf3f3742623f0ea85647a92374df405f331afd6021c5cf36af43ee8db198129c0 ]
```

**Comment by Rastaban** [comment]
That's annoyhing, I just tried the above command on a clean machine and was unable to reproduce the issue.

```
 A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> E:\vcpkg\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
Downloading 7zip... done.
Extracting 7zip...
```

Does it still repro?  I ask only because it could have been an intermittent issue in the nuget service that is now resolved so it worked for me but not for you earlier.

**Comment by szx917** [comment]
same here
OS: win10 x64

```
>vcpkg install curl
The following packages will be built and installed:
    curl[core,ssl]:x86-windows
  * openssl[core]:x86-windows
  * openssl-windows[core]:x86-windows
  * zlib[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/4: zlib:x86-windows
Building package zlib[core]:x86-windows...
A suitable version of cmake was not found (required v3.11.4). Downloading portable cmake v3.11.4...
Extracting cmake...
A suitable version of 7zip was not found (required v18.1.0). Downloading portable 7zip v18.1.0...
Downloading 7zip...
  https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 -> C:\Users\Jane Wang\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg
File does not have the expected hash:
             url : [ https://www.nuget.org/api/v2/package/7-Zip.CommandLine/18.1.0 ]
       File path : [ C:\Users\****\vcpkg\downloads\7-zip.commandline.18.1.0.nupkg.part ]
   Expected hash : [ 8c75314102e68d2b2347d592f8e3eb05812e1ebb525decbac472231633753f1d4ca31c8e6881a36144a8da26b2571305b3ae3f4e2b85fc4a290aeda63d1a13b8 ]
     Actual hash : [ a9dfaaafd15d98a2ac83682867ec5766720acf6e99d40d1a00d480692752603bf3f3742623f0ea85647a92374df405f331afd6021c5cf36af43ee8db198129c0 ]
```

**Comment by szx917** [comment]
And the downloaded file name actually is `7-zip.commandline.18.1.0.nupkg.part`

**Comment by Awia00** [comment]
I'm experiencing the same issue. Tried 
vcpkg commit: 9ad166279c913cf0becc56865d05ed5806fad8aa
Fails at 7-Zip.Commandline/18.1.0 extraction.

**Comment by hjabird** [comment]
This can be temporarily  and  foolishly 'fixed' by replacing the hash value in vcpkg/scripts/vcpkgTools (tool name="7zip" os="windows") with the actual hash. I'm pretty sure that it such an act ranks highly in the list of security sins.

**Comment by ijean** [comment]
I can confirm, same problem, on a clean Windows 10 x64 machine.

**Comment by parsa** [comment]
@Rastaban tried again on a clean VM and it does still reproduce. Same exact hashes. Also I my machine I just changed the hash in `scripts/vcpkgTools.xml` and the issue went away and Boost installed just fine.

**Comment by derekseiple** [comment]
I can confirm the same failure as well.

To work around this I copied the original `7-zip.commandline.18.1.0.nupkg` (the one with the correct hash) that I had from another install location into the `vcpkg/downloads` directory. It was then able to install packages as normal.

This doesn't help though if you can't get your hands on the right file...

**Comment by ras0219-msft** [comment]
Thank you everyone for quickly jumping in and reporting this!

I've just pushed 068032bc to master, which downgrades the version of 7-zip to a previous version while we work on some internal changes to fix this more permanently for 18.1.0.

The root cause of the issue is that NuGet.org decided to modify the existing published nupkg files and inject signature files into them, which changes their hash. Our system to protect users from malicious files detected this change and correctly refused to use the un-validated executable.

Unfortunately, it isn't as simple as changing the expected hash, because existing users will still have the older file downloaded. We also can't just rename the file, because `nuget.exe` demands that the file be named in a very specific way.

As mentioned above, we're working on fixing this properly as a high priority, but 068032bc will fix the issue for now.

Thanks again!

**Comment by jherico** [comment]
Unfortunately the hotfix is causing a new problem.  

```

**Comment by ras0219-msft** [comment]
Thanks for the further investigation.

I was able to confirm some strange behavior (though not this particular issue) when using the old 7zip as well. I've pushed a different workaround (273b8ce3d0d3533f3b959a7ecf4b0aa1eef22cab) that's a bit more permanent by mapping the new hash in the tool back to the old hash.

The reason to map the new hash to the old hash is to improve compatibility for existing users which might `git pull` but forget to `./bootstrap-vcpkg.bat` -- they'll see everything keep working as before, because they already have the old version downloaded. For new users, they will definitely be bootstrapping, so the new file's hash will get (hackily) mapped to the old hash and the check will pass.

A proper fix is still desirable, but this particular duct tape should hold for longer since it's using the same (latest available) version of 7zip as before.

**Comment by Farwaykorse** [comment]
This issue still appears for anyone who has not ran `.\bootstrap-vcpkg.bat` since the patch.
It is not something I'd do when there is no update warning.

**Comment by degski** [comment]
@ras0219-msft @Farwaykorse Yes, version should be increased so at least  message to run `.\bootstrap-vcpkg.bat` pops up.

@ras0219-msft The nuget versioning is wacky, 7zip versioning is format `YY,MM`, i.e. `18.01`, and not `number.number`.

**Comment by Adraesh** [comment]
Hello, I have the same issue, I am trying to run .\bootstrap-vcpkg.bat but it failed due to toolsrc/ folder not existing.

I got vcpkg 1.50 through VS 2017 Nuget Package Manager.

Thank you in advance.

**Comment by aybassiouny** [comment]
This seems to be an issue especially when going back in time to get earlier versions of libraries.

**Comment by Rhvarrier** [comment]
This issue is still present in 2020.01 version

**Comment by Russo11** [comment]
Among many other converters, I would like to highlight AnyConv. It is simple, fast, and supports many file formats. [anyconv.com](https://anyconv.com/)

**Comment by chatyan** [comment]
same problem when i install boost-compatibility

**.\vcpkg install boost-compatibility
Computing installation plan...
The following packages will be built and installed:
    boost-compatibility[core]:x86-windows
Starting package 1/1: boost-compatibility:x86-windows
Building package boost-compatibility[core]:x86-windows...
-- Downloading https://github.com/boostorg/compatibility/archive/boost-1.73.0.tar.gz...
-- Using source at D:/Work 2019/GIT Code/vcpkg/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Work 2019/GIT Code/vcpkg/downloads/boost_LICENSE_1_0.txt
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):


  File does not have expected hash:

          File path: [ D:/Work 2019/GIT Code/vcpkg/downloads/boost_LICENSE_1_0.txt ]
      Expected hash: [ d6078467835dba8932314c1c1e945569a64b065474d7aced27c9a7acc391d52e9f234138ed9f1aa9cd576f25f12f557e0b733c14891d42c16ecdc4a7bd4d60b8 ]
        Actual hash: [ b3e1ca08971b1c3e8cb11a854d094cea3a5fd2c95cf9e985b5212a4bde7975cc3ae15455e8d9e7dc3f2a47b1285b0a34798fc6e194d4ec2db4ceb76547bf07bb ]

  Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:110 (test_hash)
  installed/x86-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
  scripts/ports.cmake:76 (include)


Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

D:\Work 2019\GIT Code\vcpkg>.\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

D:\Work 2019\GIT Code\vcpkg>.\vcpkg install boost-compatibility
Computing installation plan...
The following packages will be built and installed:
    boost-compatibility[core]:x86-windows
Starting package 1/1: boost-compatibility:x86-windows
Building package boost-compatibility[core]:x86-windows...
-- Using cached D:/Work 2019/GIT Code/vcpkg/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Using source at D:/Work 2019/GIT Code/vcpkg/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Work 2019/GIT Code/vcpkg/downloads/boost_LICENSE_1_0.txt
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):


  File does not have expected hash:

          File path: [ D:/Work 2019/GIT Code/vcpkg/downloads/boost_LICENSE_1_0.txt ]
      Expected hash: [ d6078467835dba8932314c1c1e945569a64b065474d7aced27c9a7acc391d52e9f234138ed9f1aa9cd576f25f12f557e0b733c14891d42c16ecdc4a7bd4d60b8 ]
        Actual hash: [ b3e1ca08971b1c3e8cb11a854d094cea3a5fd2c95cf9e985b5212a4bde7975cc3ae15455e8d9e7dc3f2a47b1285b0a34798fc6e194d4ec2db4ceb76547bf07bb ]

  Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:110 (test_hash)
  installed/x86-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
  scripts/ports.cmake:76 (include)


Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files above.

D:\Work 2019\GIT Code\vcpkg>./bootstrap-vcpkg.bat
'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

D:\Work 2019\GIT Code\vcpkg>.\bootstrap-vcpkg.bat

Building vcpkg.exe ...

  Using triplet "x86-windows" from "D:\Work 2019\GIT Code\vcpkg\installed\x86-windows\"
  pch.cpp
  archives.cpp
  checks.cpp
  chrono.cpp
  cofffilereader.cpp
  downloads.cpp
  enums.cpp
  files.cpp
  hash.cpp
  json.cpp
  machinetype.cpp
  parse.cpp
  strings.cpp
  stringview.cpp
  system.cpp
  system.print.cpp
  system.process.cpp
  unicode.cpp
  binarycaching.cpp
  binaryparagraph.cpp
  build.cpp
  buildenvironment.cpp
  cmakevars.cpp
  commands.autocomplete.cpp
  commands.buildexternal.cpp
  commands.cache.cpp
  commands.ci.cpp
  commands.ciclean.cpp
  commands.contact.cpp
  commands.cpp
  commands.create.cpp
  commands.dependinfo.cpp
  commands.edit.cpp
  commands.env.cpp
  commands.exportifw.cpp
  commands.import.cpp
  commands.integrate.cpp
  commands.list.cpp
  commands.owns.cpp
  commands.porthistory.cpp
  commands.portsdiff.cpp
  commands.search.cpp
  commands.setinstalled.cpp
  commands.upgrade.cpp
  commands.version.cpp
  commands.xvsinstances.cpp
  dependencies.cpp
  export.cpp
  export.chocolatey.cpp
  export.prefab.cpp
D:\Work 2019\GIT Code\vcpkg\toolsrc\src\vcpkg\export.prefab.cpp(1,1): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数 据丢失 [D:\Work 2019\GIT Code\vcpkg\t
oolsrc\vcpkglib\vcpkglib.vcxproj]
  globalstate.cpp
  help.cpp
  input.cpp
  install.cpp
  logicexpression.cpp
  metrics.cpp
  packagespec.cpp
  paragraphparseresult.cpp
  paragraphs.cpp
  portfileprovider.cpp
  postbuildlint.buildtype.cpp
  postbuildlint.cpp
  remove.cpp
  sourceparagraph.cpp
  statusparagraph.cpp
  statusparagraphs.cpp
  tools.cpp
  triplet.cpp
  update.cpp
  userconfig.cpp
  vcpkgcmdarguments.cpp
  vcpkglib.cpp
  vcpkgpaths.cpp
  versiont.cpp
  visualstudio.cpp
  vcpkglib.vcxproj -> D:\Work 2019\GIT Code\vcpkg\toolsrc\msbuild.x86.release\vcpkglib.lib
  Using triplet "x86-windows" from "D:\Work 2019\GIT Code\vcpkg\installed\x86-windows\"
  vcpkg.cpp
  正在生成代码
  Previous IPDB not found, fall back to full compilation.
  All 17889 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  已完成代码的生成
  vcpkg.vcxproj -> D:\Work 2019\GIT Code\vcpkg\toolsrc\msbuild.x86.release\vcpkg.exe
  Using triplet "x86-windows" from "D:\Work 2019\GIT Code\vcpkg\installed\x86-windows\"
  vcpkgmetricsuploader.cpp
  正在生成代码
  Previous IPDB not found, fall back to full compilation.
  All 3379 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.
  已完成代码的生成
  vcpkgmetricsuploader.vcxproj -> D:\Work 2019\GIT Code\vcpkg\toolsrc\msbuild.x86.release\vcpkgmetricsuploader.exe

Building vcpkg.exe... done.

Telemetry
---------
vcpkg collects usage data in order to help us improve your experience.
The data collected by Microsoft is anonymous.
You can opt-out of telemetry by re-running the bootstrap-vcpkg script with -disableMetrics,
passing --disable-metrics to vcpkg on the command line,
or by setting the VCPKG_DISABLE_METRICS environment variable.

Read more about vcpkg telemetry at docs/about/privacy.md

D:\Work 2019\GIT Code\vcpkg>.\vcpkg update
Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.

D:\Work 2019\GIT Code\vcpkg>.\vcpkg install pcl
Computing installation plan...
The following packages will be built and installed:
  * boost-algorithm[core]:x86-windows
  * boost-any[core]:x86-windows
  * boost-array[core]:x86-windows
  * boost-asio[core]:x86-windows
  * boost-assert[core]:x86-windows
  * boost-atomic[core]:x86-windows
  * boost-bimap[core]:x86-windows
  * boost-bind[core]:x86-windows
  * boost-build[core]:x86-windows
  * boost-chrono[core]:x86-windows
  * boost-circular-buffer[core]:x86-windows
  * boost-compatibility[core]:x86-windows
  * boost-concept-check[core]:x86-windows
  * boost-config[core]:x86-windows
  * boost-container[core]:x86-windows
  * boost-container-hash[core]:x86-windows
  * boost-context[core]:x86-windows
  * boost-conversion[core]:x86-windows
  * boost-core[core]:x86-windows
  * boost-coroutine[core]:x86-windows
  * boost-date-time[core]:x86-windows
  * boost-detail[core]:x86-windows
  * boost-dynamic-bitset[core]:x86-windows
  * boost-endian[core]:x86-windows
  * boost-exception[core]:x86-windows
  * boost-filesystem[core]:x86-windows
  * boost-foreach[core]:x86-windows
  * boost-format[core]:x86-windows
  * boost-function[core]:x86-windows
  * boost-function-types[core]:x86-windows
  * boost-functional[core]:x86-windows
  * boost-fusion[core]:x86-windows
  * boost-graph[core]:x86-windows
  * boost-integer[core]:x86-windows
  * boost-interprocess[core]:x86-windows
  * boost-intrusive[core]:x86-windows
  * boost-io[core]:x86-windows
  * boost-iostreams[core]:x86-windows
  * boost-iterator[core]:x86-windows
  * boost-lambda[core]:x86-windows
  * boost-lexical-cast[core]:x86-windows
  * boost-locale[core]:x86-windows
  * boost-math[core]:x86-windows
  * boost-modular-build-helper[core]:x86-windows
  * boost-move[core]:x86-windows
  * boost-mp11[core]:x86-windows
  * boost-mpl[core]:x86-windows
  * boost-multi-array[core]:x86-windows
  * boost-multi-index[core]:x86-windows
  * boost-multiprecision[core]:x86-windows
  * boost-numeric-conversion[core]:x86-windows
  * boost-optional[core]:x86-windows
  * boost-parameter[core]:x86-windows
  * boost-phoenix[core]:x86-windows
  * boost-pool[core]:x86-windows
  * boost-predef[core]:x86-windows
  * boost-preprocessor[core]:x86-windows
  * boost-property-map[core]:x86-windows
  * boost-property-tree[core]:x86-windows
  * boost-proto[core]:x86-windows
  * boost-ptr-container[core]:x86-windows
  * boost-random[core]:x86-windows
  * boost-range[core]:x86-windows
  * boost-ratio[core]:x86-windows
  * boost-rational[core]:x86-windows
  * boost-regex[core]:x86-windows
  * boost-serialization[core]:x86-windows
  * boost-signals2[core]:x86-windows
  * boost-smart-ptr[core]:x86-windows
  * boost-spirit[core]:x86-windows
  * boost-static-assert[core]:x86-windows
  * boost-system[core]:x86-windows
  * boost-test[core]:x86-windows
  * boost-thread[core]:x86-windows
  * boost-throw-exception[core]:x86-windows
  * boost-tokenizer[core]:x86-windows
  * boost-tti[core]:x86-windows
  * boost-tuple[core]:x86-windows
  * boost-type-index[core]:x86-windows
  * boost-type-traits[core]:x86-windows
  * boost-typeof[core]:x86-windows
  * boost-unordered[core]:x86-windows
  * boost-utility[core]:x86-windows
  * boost-uuid[core]:x86-windows
  * boost-variant[core]:x86-windows
  * boost-winapi[core]:x86-windows
  * boost-xpressive[core]:x86-windows
  * bzip2[core]:x86-windows
  * curl[core,non-http,ssl,sspi,winssl]:x86-windows
  * double-conversion[core]:x86-windows
  * eigen3[core]:x86-windows
  * expat[core]:x86-windows
  * flann[core]:x86-windows
  * freetype[bzip2,core,png]:x86-windows
  * glew[core]:x86-windows
  * hdf5[core,szip,zlib]:x86-windows
  * jsoncpp[core]:x86-windows
  * libharu[core,notiffsymbols]:x86-windows
  * libiconv[core]:x86-windows
  * libjpeg-turbo[core]:x86-windows
  * liblzma[core]:x86-windows
  * libogg[core]:x86-windows
  * libpng[core]:x86-windows
  * libtheora[core]:x86-windows
  * libxml2[core]:x86-windows
  * lz4[core]:x86-windows
  * netcdf-c[core]:x86-windows
  * openssl[core]:x86-windows
  * openssl-windows[core]:x86-windows
    pcl[core]:x86-windows
  * pegtl-2[core]:x86-windows
  * proj4[core,database]:x86-windows
  * pugixml[core]:x86-windows
  * qhull[core]:x86-windows
  * sqlite3[core,tool]:x86-windows
  * szip[core]:x86-windows
  * tiff[core]:x86-windows
  * utfcpp[core]:x86-windows
  * vtk[core]:x86-windows
  * xxhash[core]:x86-windows
  * zlib[core]:x86-windows
  * zstd[core]:x86-windows
Additional packages (*) will be modified to complete this operation.
Starting package 1/122: boost-compatibility:x86-windows
Building package boost-compatibility[core]:x86-windows...
-- Using cached D:/Work 2019/GIT Code/vcpkg/downloads/boostorg-compatibility-boost-1.73.0.tar.gz
-- Using source at D:/Work 2019/GIT Code/vcpkg/buildtrees/boost-compatibility/src/ost-1.73.0-44642da97c
-- Packaging headers
-- Packaging headers done
-- Using cached D:/Work 2019/GIT Code/vcpkg/downloads/boost_LICENSE_1_0.txt
CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:99 (message):


  File does not have expected hash:

          File path: [ D:/Work 2019/GIT Code/vcpkg/downloads/boost_LICENSE_1_0.txt ]
      Expected hash: [ d6078467835dba8932314c1c1e945569a64b065474d7aced27c9a7acc391d52e9f234138ed9f1aa9cd576f25f12f557e0b733c14891d42c16ecdc4a7bd4d60b8 ]
        Actual hash: [ b3e1ca08971b1c3e8cb11a854d094cea3a5fd2c95cf9e985b5212a4bde7975cc3ae15455e8d9e7dc3f2a47b1285b0a34798fc6e194d4ec2db4ceb76547bf07bb ]

  Please delete the file and retry if this file should be downloaded again.

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:110 (test_hash)
  installed/x86-windows/share/boost-vcpkg-helpers/boost-modular-headers.cmake:17 (vcpkg_download_distfile)
  ports/boost-compatibility/portfile.cmake:12 (boost_modular_headers)
  scripts/ports.cmake:76 (include)


Error: Building package boost-compatibility:x86-windows failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with `.\vcpkg update`, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
  Package: boost-compatibility:x86-windows
  Vcpkg version: 2020.02.04-nohash

Additionally, attach any relevant sections from the log files a**bove.

**Comment by akourtis98** [comment]
For me it was solved by running the command with admin privileges...

**Comment by malidiab** [comment]
updating vcpkg fixes the problem to me 2020.06.15-

**Comment by Nikmeh922** [comment]
> I can confirm the same failure as well.
> 
> To work around this I copied the original `7-zip.commandline.18.1.0.nupkg` (the one with the correct hash) that I had on hand from another install location into the `vcpkg/downloads` directory. It was then able to install packages as normal.
> 
> This doesn't help though if you can't get your hands on the right file...

Thank you. This helped a lot!!!

**Comment by parsa** [comment]
> Thank you everyone for quickly jumping in and reporting this!
> 
> I've just pushed [068032b](https://github.com/microsoft/vcpkg/commit/068032bc548817a04709970f76268a6d7b1767c7) to master, which downgrades the version of 7-zip to a previous version while we work on some internal changes to fix this more permanently for 18.1.0.
> 
> The root cause of the issue is that NuGet.org decided to modify the existing published nupkg files and inject signature files into them, which changes their hash. Our system to protect users from malicious files detected this change and correctly refused to use the un-validated executable.
> 
> Unfortunately, it isn't as simple as changing the expected hash, because existing users will still have the older file downloaded. We also can't just rename the file, because `nuget.exe` demands that the file be named in a very specific way.
> 
> As mentioned above, we're working on fixing this properly as a high priority, but [068032b](https://github.com/microsoft/vcpkg/commit/068032bc548817a04709970f76268a6d7b1767c7) will fix the issue for now.
> 
> Thanks again!

This issue has been long solved for me, and I don't think the follow-ups describe the same issue. If my opinion as the person who opened this issue counts, this issue can be closed.

**Comment by PhoebeHui** [comment]
I agree, thank you parsa for your response! closing this issue now.

**Comment by fly2sky2018** [comment]
I solve the preblem
1)download this files 
https://raw.githubusercontent.com/boostorg/boost/boost-1.75.0/LICENSE_1_0.txt
https://raw.githubusercontent.com/boostorg/boost/boost-1.75.0/boostcpp.jam
2)skip the hash test
add skip code at the vcpkg_download_distfile.camke
