### ISSUE TITLE
[libxml2] include path moved, regression

### ISSUE THREAD

**Issue by zerocom38** [microsoft/vcpkg#47155]
**Describe the bug**
The include path of libxml2 has been changed. It's not part of the main include path anymore: `...\installed\x64-windows\include\libxml`, now it's only inside a libxml2 subdirectory: `...\installed\x64-windows\include\libxml2\libxml`. Is this a supposed change or a regression?  Other libraries, like OpenSSL, are still located in the main path.

**Environment**
- OS: Windows

**To Reproduce**
1. ./vcpkg install libxml2

**Comment by dg0yt** [comment]
> Is this a supposed change or a regression?

It didn't "move", but #47074 removed the *redundant* copy in the non-standard location which existed for a `# TODO: Fix usage in all dependent ports hardcoding the wrong include path.` This TODO is resolved.

I expected this to come as a surprise for users which do not use pkgconfig or cmake. That's why I added an explict note: https://github.com/microsoft/vcpkg/pull/47074/files#r2299928810. But the general direction of ports is "respect upstream's choice" AFAICT.

Your options:
- Pin the previous version. (Temporary solution.)
- Add the proper include dir in your (msbuild) project.
- Adopt or fix use of CMake or pkg-config.
- Use an extra port which depends on `libxml` and copies the headers into the "convenience location". https://github.com/microsoft/vcpkg/issues/47155#issuecomment-3698656594

**Comment by zerocom38** [comment]
Thank you for clarifying. I'm using Rust with the vcpkg crate to find the dependencies. The vcpkg crate adds the main vcpkg include path, which works fine for libraries like openssl, libpng or libavcodec, but now fails for libxml. On all other platforms, the include files are just added into the include directory (which would be `path/include/libxml`), but libxml2 on Windows now becomes `path/include/libxml2/libxml`. Looks kind of redundant to me.

**Comment by dg0yt** [comment]
> libxml2 on Windows now becomes `path/include/libxml2/libxml`. Looks kind of redundant to me.

This is nothing specific about Windows or vcpkg. It is about libxml2 (common with other GTK/gnome libs). Debian install libxml2 the same way:
https://packages.debian.org/sid/amd64/libxml2-dev/filelist

> The vcpkg crate adds the main vcpkg include path, which works fine for libraries like openssl, libpng or libavcodec,

This sounds like poor guessing, similar to uninformed CMake find modules. We know that this works for some simple cases but fails as a general mechanism. Without proper use of CMake or pkg-config, reverse dependencies will miss specific include directories, the full set of transitive link libraries, and the macro definitions to control visibiltity/dllimport decorations.

(libxml2 has varying dependencies subject to configuration. It may even have C++ linkage when built with icu. Everything is done to properly carry this to CMake and pkg-config.

**Comment by zerocom38** [comment]
I totally agree. The way vcpkg crate finds dependencies is just guessing, and it hasn't seen any updates in the past 4 years. But it's widely used in Rust crates (almost 200 million downloads).
I raised this issue because I wasn't sure if the directory change was intentional. It sounds like it was, so we can close the issue, and I'll look for a solution in the libxml2 Rust crate.

**Comment by GitMensch** [comment]
Yes, people who use msbuilld now fail to build (CIs broken, users running into same issue)...

It seems the only proper solution (other than pinning) is to create an extra libxml-headers package that depends on libxml - but that will still fail all the build setups from the previous decade (also true if they don't pinned the version).

Not sure how the msbuild should look like that it is still portable (use of vcpkg yes/no placing into a project specific auxiliary header folder yes/no) either.

**Comment by GitMensch** [comment]
Are we still not able to pin versions using the vcpkg tool and need to create a manifest just for that (https://learn.microsoft.com/en-us/vcpkg/consume/lock-package-versions)? If this is the case then this regression is even worse...

**Comment by dg0yt** [comment]
> to create an extra libxml-headers package that depends on libxml - but that will still fail all the build setups from the previous decade

No, it doesn't need to fail. It just needs to check if the redundant headers are already present in CURRENT_INSTALLED_DIR before copying from the official location to CURRENT_PACKAGES_DIR.

**Comment by dg0yt** [comment]
> Are we still not able to pin versions using the vcpkg tool and need to create a manifest just for that

There is no versioning and pinning in classic mode. There is overlay ports, and there is `git checkout REV -- PATH`.

And when using CI in classic mode, you could add explicit copying to the pipeline.

**Comment by GitMensch** [comment]
A new package can also check for the minimal libxml2 version in the first place. What I've meant is that _existing_ builds and CIs all need to be adjusted *even in a minor libxml2 version update* (but I'm not following their version scheme).

Please elaborate on the git checkout REV option and "overlay ports", documenting workarounds (solutions seems to not use msbuild directly any more) in this ticket. Thank you.

**Comment by trueqbit** [comment]
I think this should be addressed in vcpkg itself somehow.

I am exporting a nuget package containing the the dependencies for each project. This nuget package is then added to the projects of a Visual C++ Solution. When creating the nuget package, vcpkg copies the files _vcpkg.props_ and _vcpkg.targets_ into the _scripts/buildsystems/msbuild_ sub folder, which in turn are consumed by the _.vcxproj_ files. I guess the _.props_ and _.targets_ files will have to look for the package sub folder.

Meanwhile I could live with a custom overlay port, which I do use anyway.

**Comment by dg0yt** [comment]
> vcpkg copies the files _vcpkg.props_ and _vcpkg.targets_ into the _scripts/buildsystems/msbuild_ sub folder, which in turn are consumed by the _.vcxproj_ files. I guess the _.props_ and _.targets_ files will have to look for the package sub folder.

IIRC there is an issue for this.

**Comment by trueqbit** [comment]
> > vcpkg copies the files _vcpkg.props_ and _vcpkg.targets_ into the _scripts/buildsystems/msbuild_ sub folder, which in turn are consumed by the _.vcxproj_ files. I guess the _.props_ and _.targets_ files will have to look for the package sub folder.
> 
> IIRC there is an issue for this.

Superficial search skills don't yield anything useful. Could you link it here if you remember the ticket... :)

**Comment by korDen** [comment]
we can't use anything past 7.5.0 version  7, this "cleanup" broke include paths and the code that includes libxml2 no longer compiles

**Comment by GitMensch** [comment]
@korDen: yes - the cleanup means that you have to change all the projects to include the libxml2 path up-front... or, if you use msbuild change its invocation (so build / CI scripts) set/extend the CL variable: `set CL=/I "%VCPKG_ROOT%\installed\${{ matrix.arch }}-windows\include\libxml2"`.

**Comment by dg0yt** [comment]
Uninformed build systems are ... uninformed.
To fill the gap with a "libxml2-legacy" overlay port:

`vcpkg.json`:
~~~json
{
  "name": "libxml2-legacy",
  "version-string": "unsupported",
  "description": "Promoting uninformed usage patterns",
  "license": "MIT",
  "dependencies": [
    {
      "name": "libxml2",
      "default-features": false
    }
  ]
}
~~~

`portfile.cmake`:
~~~cmake
file(INSTALL "${CURRENT_INSTALLED_DIR}/include/libxml2/libxml" DESTINATION  "${CURRENT_PACKAGES_DIR}/include")
set(VCPKG_POLICY_SKIP_COPYRIGHT_CHECK enabled)
~~~

**Comment by GitMensch** [comment]
Sounds exactly as requested above - thanks. It seems like libxml2-legacy should be added to the default ports, then people _only_ need to use it in their vcpkg list which sounds like the most reasonable approach until all the build environments are fixed.
